/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
	"time"
)

// checks if the CzechBankIdProviderOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CzechBankIdProviderOutput{}

// CzechBankIdProviderOutput Exposed properties for the `czech-bank-id` Provider which do not directly map to the normalized IdentityData model.
type CzechBankIdProviderOutput struct {
	// The subject identifier for the verified individual.
	SubjectIdentifier NullableString `json:"subjectIdentifier,omitempty"`
	// The individual's full name.
	FullName NullableString `json:"fullName,omitempty"`
	// The individual's given or first name.
	GivenName NullableString `json:"givenName,omitempty"`
	// The individual's family or last name.
	FamilyName NullableString `json:"familyName,omitempty"`
	// The individual's middle name.
	MiddleName NullableString `json:"middleName,omitempty"`
	// Nickname used by a physical person              A casual name, not necessarily the legal given name.
	Nickname NullableString `json:"nickname,omitempty"`
	// The individual's preferred username.              The user has chosen this as the preferred name for logins.
	PreferredUsername NullableString `json:"preferredUsername,omitempty"`
	// The individual's gender.              Possible values: - Male - Female - Other              Only returned for Identify verifications.
	Gender NullableString `json:"gender,omitempty"`
	// The individual's date of birth.              This is a string because the value may have reduced precision, such as only a year.
	DateOfBirth NullableString `json:"dateOfBirth,omitempty"`
	// The individual's Czech birth number.              This value is written without the traditional forward slash. Czech birth numbers are Czech public-authority identifiers administered through the Ministry of Interior's birth-number register. The Ministry can assign one to Czech citizens and to foreign nationals with temporary or permanent residence in the Czech Republic. For foreign nationals, this is still a Czech birth number in the Czech format, not an identity number from another country.              The common current format is YYXXDDSSSC: - YY: Two digit birth year - XX: Encoded birth month, see below for encoding logic - DD: Birth day - SSS: Sequence number - C: Modulo-11 checksum digit. Not present for people born before 1954. The encoded month is MM for men, MM + 50 for women, and can be MM + 20 for men or MM + 70 for women when additional number ranges are needed. Older numbers for people born before 1954 can use YYXXDDSSS and do not use the modulo-11 checksum.              Only returned for Identify verifications.
	BirthNumber NullableString `json:"birthNumber,omitempty"`
	// The individual's age.
	Age NullableInt32 `json:"age,omitempty"`
	// Whether the individual is an adult.              In the Czech Republic, legal majority (adulthood) is reached at 18 years old. Only returned for Identify Plus verifications.
	IsAdult NullableBool `json:"isAdult,omitempty"`
	// The individual's date of death, if available.
	DateOfDeath NullableString `json:"dateOfDeath,omitempty"`
	// The individual's place of birth.              Only returned for Identify Plus verifications.
	BirthPlace NullableString `json:"birthPlace,omitempty"`
	// The individual's country of birth.              Only returned for Identify Plus verifications.
	BirthCountry NullableString `json:"birthCountry,omitempty"`
	// The individual's primary nationality.              The value is an ISO 3166-1 alpha-2 country code. Only returned for Identify Plus verifications.
	PrimaryNationality NullableString `json:"primaryNationality,omitempty"`
	// The individual's nationalities.
	Nationalities []string `json:"nationalities,omitempty"`
	// The individual's marital status.              Possible values: - COHABITATION - MARRIED - DIVORCED - REGISTERED_PARTNERSHIP - REGISTERED_PARTNERSHIP_CANCELED - WIDOWED - SINGLE - PARTNERSHIP - PARTNERSHIP_CANCELED - SEPARATED - REGISTERED_PARTNERSHIP_WIDOWED - LAPSED_MARRIAGE - UNKNOWN              Only returned for Identify Plus verifications.
	MaritalStatus NullableString `json:"maritalStatus,omitempty"`
	// The individual's email address.
	Email NullableString `json:"email,omitempty"`
	// Whether the individual's email address has been verified.
	EmailVerified NullableBool `json:"emailVerified,omitempty"`
	// The individual's phone number.              This value is normalized to E.164 format.
	PhoneNumber NullableString `json:"phoneNumber,omitempty"`
	// Whether the individual's phone number has been verified.
	PhoneNumberVerified NullableBool `json:"phoneNumberVerified,omitempty"`
	// Whether the individual is a politically exposed person.              This follows Czech anti-money-laundering rules, indicating a person that is at risk for corruption, bribery or money laundering activities. Mandatory screening of these individuals is required for compliance. Typically set for people such as the Prime Minister, ministers, etc.
	IsPoliticallyExposedPerson NullableBool `json:"isPoliticallyExposedPerson,omitempty"`
	// Whether the individual is a person with limited legal capacity.
	LimitedLegalCapacity NullableBool `json:"limitedLegalCapacity,omitempty"`
	// Metadata about how the identity information was verified for Anti Money Laundering scope.              Only returned for Identify AML verifications.
	Verification NullableCzechBankIdVerification `json:"verification,omitempty"`
	// The individual's addresses.              This can include permanent residence and contact addresses. Only returned for Identify verifications.
	Addresses []CzechBankIdAddress `json:"addresses,omitempty"`
	// The individual's identity documents.              This can include document type, country, number, issuer, and validity dates. Only returned for Identify Plus verifications.
	IdCards []CzechBankIdCard `json:"idCards,omitempty"`
	// The UTC date and time when the identity data was last updated.
	UpdatedAt NullableTime `json:"updatedAt,omitempty"`
	// The individual's time zone.              This is represented as a zoneinfo/IANA Time Zone Database value.
	ZoneInfo NullableString `json:"zoneInfo,omitempty"`
	// The individual's locale.              This is represented as a BCP 47/RFC 5646 language tag. Some values may use an underscore separator, such as cs_CZ.
	Locale NullableString `json:"locale,omitempty"`
	// The individual's title prefixes and suffixes.              Only returned for Identify verifications.
	Titles []CzechBankIdTitle `json:"titles,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CzechBankIdProviderOutput CzechBankIdProviderOutput

// NewCzechBankIdProviderOutput instantiates a new CzechBankIdProviderOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCzechBankIdProviderOutput() *CzechBankIdProviderOutput {
	this := CzechBankIdProviderOutput{}
	return &this
}

// NewCzechBankIdProviderOutputWithDefaults instantiates a new CzechBankIdProviderOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCzechBankIdProviderOutputWithDefaults() *CzechBankIdProviderOutput {
	this := CzechBankIdProviderOutput{}
	return &this
}

// GetSubjectIdentifier returns the SubjectIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetSubjectIdentifier() string {
	if o == nil || IsNil(o.SubjectIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.SubjectIdentifier.Get()
}

// GetSubjectIdentifierOk returns a tuple with the SubjectIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetSubjectIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubjectIdentifier.Get(), o.SubjectIdentifier.IsSet()
}

// HasSubjectIdentifier returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasSubjectIdentifier() bool {
	if o != nil && o.SubjectIdentifier.IsSet() {
		return true
	}

	return false
}

// SetSubjectIdentifier gets a reference to the given NullableString and assigns it to the SubjectIdentifier field.
func (o *CzechBankIdProviderOutput) SetSubjectIdentifier(v string) {
	o.SubjectIdentifier.Set(&v)
}
// SetSubjectIdentifierNil sets the value for SubjectIdentifier to be an explicit nil
func (o *CzechBankIdProviderOutput) SetSubjectIdentifierNil() {
	o.SubjectIdentifier.Set(nil)
}

// UnsetSubjectIdentifier ensures that no value is present for SubjectIdentifier, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetSubjectIdentifier() {
	o.SubjectIdentifier.Unset()
}

// GetFullName returns the FullName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetFullName() string {
	if o == nil || IsNil(o.FullName.Get()) {
		var ret string
		return ret
	}
	return *o.FullName.Get()
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FullName.Get(), o.FullName.IsSet()
}

// HasFullName returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasFullName() bool {
	if o != nil && o.FullName.IsSet() {
		return true
	}

	return false
}

// SetFullName gets a reference to the given NullableString and assigns it to the FullName field.
func (o *CzechBankIdProviderOutput) SetFullName(v string) {
	o.FullName.Set(&v)
}
// SetFullNameNil sets the value for FullName to be an explicit nil
func (o *CzechBankIdProviderOutput) SetFullNameNil() {
	o.FullName.Set(nil)
}

// UnsetFullName ensures that no value is present for FullName, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetFullName() {
	o.FullName.Unset()
}

// GetGivenName returns the GivenName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetGivenName() string {
	if o == nil || IsNil(o.GivenName.Get()) {
		var ret string
		return ret
	}
	return *o.GivenName.Get()
}

// GetGivenNameOk returns a tuple with the GivenName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetGivenNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GivenName.Get(), o.GivenName.IsSet()
}

// HasGivenName returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasGivenName() bool {
	if o != nil && o.GivenName.IsSet() {
		return true
	}

	return false
}

// SetGivenName gets a reference to the given NullableString and assigns it to the GivenName field.
func (o *CzechBankIdProviderOutput) SetGivenName(v string) {
	o.GivenName.Set(&v)
}
// SetGivenNameNil sets the value for GivenName to be an explicit nil
func (o *CzechBankIdProviderOutput) SetGivenNameNil() {
	o.GivenName.Set(nil)
}

// UnsetGivenName ensures that no value is present for GivenName, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetGivenName() {
	o.GivenName.Unset()
}

// GetFamilyName returns the FamilyName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetFamilyName() string {
	if o == nil || IsNil(o.FamilyName.Get()) {
		var ret string
		return ret
	}
	return *o.FamilyName.Get()
}

// GetFamilyNameOk returns a tuple with the FamilyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetFamilyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FamilyName.Get(), o.FamilyName.IsSet()
}

// HasFamilyName returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasFamilyName() bool {
	if o != nil && o.FamilyName.IsSet() {
		return true
	}

	return false
}

// SetFamilyName gets a reference to the given NullableString and assigns it to the FamilyName field.
func (o *CzechBankIdProviderOutput) SetFamilyName(v string) {
	o.FamilyName.Set(&v)
}
// SetFamilyNameNil sets the value for FamilyName to be an explicit nil
func (o *CzechBankIdProviderOutput) SetFamilyNameNil() {
	o.FamilyName.Set(nil)
}

// UnsetFamilyName ensures that no value is present for FamilyName, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetFamilyName() {
	o.FamilyName.Unset()
}

// GetMiddleName returns the MiddleName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetMiddleName() string {
	if o == nil || IsNil(o.MiddleName.Get()) {
		var ret string
		return ret
	}
	return *o.MiddleName.Get()
}

// GetMiddleNameOk returns a tuple with the MiddleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetMiddleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MiddleName.Get(), o.MiddleName.IsSet()
}

// HasMiddleName returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasMiddleName() bool {
	if o != nil && o.MiddleName.IsSet() {
		return true
	}

	return false
}

// SetMiddleName gets a reference to the given NullableString and assigns it to the MiddleName field.
func (o *CzechBankIdProviderOutput) SetMiddleName(v string) {
	o.MiddleName.Set(&v)
}
// SetMiddleNameNil sets the value for MiddleName to be an explicit nil
func (o *CzechBankIdProviderOutput) SetMiddleNameNil() {
	o.MiddleName.Set(nil)
}

// UnsetMiddleName ensures that no value is present for MiddleName, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetMiddleName() {
	o.MiddleName.Unset()
}

// GetNickname returns the Nickname field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetNickname() string {
	if o == nil || IsNil(o.Nickname.Get()) {
		var ret string
		return ret
	}
	return *o.Nickname.Get()
}

// GetNicknameOk returns a tuple with the Nickname field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetNicknameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nickname.Get(), o.Nickname.IsSet()
}

// HasNickname returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasNickname() bool {
	if o != nil && o.Nickname.IsSet() {
		return true
	}

	return false
}

// SetNickname gets a reference to the given NullableString and assigns it to the Nickname field.
func (o *CzechBankIdProviderOutput) SetNickname(v string) {
	o.Nickname.Set(&v)
}
// SetNicknameNil sets the value for Nickname to be an explicit nil
func (o *CzechBankIdProviderOutput) SetNicknameNil() {
	o.Nickname.Set(nil)
}

// UnsetNickname ensures that no value is present for Nickname, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetNickname() {
	o.Nickname.Unset()
}

// GetPreferredUsername returns the PreferredUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetPreferredUsername() string {
	if o == nil || IsNil(o.PreferredUsername.Get()) {
		var ret string
		return ret
	}
	return *o.PreferredUsername.Get()
}

// GetPreferredUsernameOk returns a tuple with the PreferredUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetPreferredUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreferredUsername.Get(), o.PreferredUsername.IsSet()
}

// HasPreferredUsername returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasPreferredUsername() bool {
	if o != nil && o.PreferredUsername.IsSet() {
		return true
	}

	return false
}

// SetPreferredUsername gets a reference to the given NullableString and assigns it to the PreferredUsername field.
func (o *CzechBankIdProviderOutput) SetPreferredUsername(v string) {
	o.PreferredUsername.Set(&v)
}
// SetPreferredUsernameNil sets the value for PreferredUsername to be an explicit nil
func (o *CzechBankIdProviderOutput) SetPreferredUsernameNil() {
	o.PreferredUsername.Set(nil)
}

// UnsetPreferredUsername ensures that no value is present for PreferredUsername, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetPreferredUsername() {
	o.PreferredUsername.Unset()
}

// GetGender returns the Gender field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetGender() string {
	if o == nil || IsNil(o.Gender.Get()) {
		var ret string
		return ret
	}
	return *o.Gender.Get()
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetGenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gender.Get(), o.Gender.IsSet()
}

// HasGender returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasGender() bool {
	if o != nil && o.Gender.IsSet() {
		return true
	}

	return false
}

// SetGender gets a reference to the given NullableString and assigns it to the Gender field.
func (o *CzechBankIdProviderOutput) SetGender(v string) {
	o.Gender.Set(&v)
}
// SetGenderNil sets the value for Gender to be an explicit nil
func (o *CzechBankIdProviderOutput) SetGenderNil() {
	o.Gender.Set(nil)
}

// UnsetGender ensures that no value is present for Gender, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetGender() {
	o.Gender.Unset()
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetDateOfBirth() string {
	if o == nil || IsNil(o.DateOfBirth.Get()) {
		var ret string
		return ret
	}
	return *o.DateOfBirth.Get()
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetDateOfBirthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfBirth.Get(), o.DateOfBirth.IsSet()
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasDateOfBirth() bool {
	if o != nil && o.DateOfBirth.IsSet() {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given NullableString and assigns it to the DateOfBirth field.
func (o *CzechBankIdProviderOutput) SetDateOfBirth(v string) {
	o.DateOfBirth.Set(&v)
}
// SetDateOfBirthNil sets the value for DateOfBirth to be an explicit nil
func (o *CzechBankIdProviderOutput) SetDateOfBirthNil() {
	o.DateOfBirth.Set(nil)
}

// UnsetDateOfBirth ensures that no value is present for DateOfBirth, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetDateOfBirth() {
	o.DateOfBirth.Unset()
}

// GetBirthNumber returns the BirthNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetBirthNumber() string {
	if o == nil || IsNil(o.BirthNumber.Get()) {
		var ret string
		return ret
	}
	return *o.BirthNumber.Get()
}

// GetBirthNumberOk returns a tuple with the BirthNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetBirthNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BirthNumber.Get(), o.BirthNumber.IsSet()
}

// HasBirthNumber returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasBirthNumber() bool {
	if o != nil && o.BirthNumber.IsSet() {
		return true
	}

	return false
}

// SetBirthNumber gets a reference to the given NullableString and assigns it to the BirthNumber field.
func (o *CzechBankIdProviderOutput) SetBirthNumber(v string) {
	o.BirthNumber.Set(&v)
}
// SetBirthNumberNil sets the value for BirthNumber to be an explicit nil
func (o *CzechBankIdProviderOutput) SetBirthNumberNil() {
	o.BirthNumber.Set(nil)
}

// UnsetBirthNumber ensures that no value is present for BirthNumber, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetBirthNumber() {
	o.BirthNumber.Unset()
}

// GetAge returns the Age field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetAge() int32 {
	if o == nil || IsNil(o.Age.Get()) {
		var ret int32
		return ret
	}
	return *o.Age.Get()
}

// GetAgeOk returns a tuple with the Age field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetAgeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Age.Get(), o.Age.IsSet()
}

// HasAge returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasAge() bool {
	if o != nil && o.Age.IsSet() {
		return true
	}

	return false
}

// SetAge gets a reference to the given NullableInt32 and assigns it to the Age field.
func (o *CzechBankIdProviderOutput) SetAge(v int32) {
	o.Age.Set(&v)
}
// SetAgeNil sets the value for Age to be an explicit nil
func (o *CzechBankIdProviderOutput) SetAgeNil() {
	o.Age.Set(nil)
}

// UnsetAge ensures that no value is present for Age, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetAge() {
	o.Age.Unset()
}

// GetIsAdult returns the IsAdult field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetIsAdult() bool {
	if o == nil || IsNil(o.IsAdult.Get()) {
		var ret bool
		return ret
	}
	return *o.IsAdult.Get()
}

// GetIsAdultOk returns a tuple with the IsAdult field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetIsAdultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsAdult.Get(), o.IsAdult.IsSet()
}

// HasIsAdult returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasIsAdult() bool {
	if o != nil && o.IsAdult.IsSet() {
		return true
	}

	return false
}

// SetIsAdult gets a reference to the given NullableBool and assigns it to the IsAdult field.
func (o *CzechBankIdProviderOutput) SetIsAdult(v bool) {
	o.IsAdult.Set(&v)
}
// SetIsAdultNil sets the value for IsAdult to be an explicit nil
func (o *CzechBankIdProviderOutput) SetIsAdultNil() {
	o.IsAdult.Set(nil)
}

// UnsetIsAdult ensures that no value is present for IsAdult, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetIsAdult() {
	o.IsAdult.Unset()
}

// GetDateOfDeath returns the DateOfDeath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetDateOfDeath() string {
	if o == nil || IsNil(o.DateOfDeath.Get()) {
		var ret string
		return ret
	}
	return *o.DateOfDeath.Get()
}

// GetDateOfDeathOk returns a tuple with the DateOfDeath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetDateOfDeathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfDeath.Get(), o.DateOfDeath.IsSet()
}

// HasDateOfDeath returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasDateOfDeath() bool {
	if o != nil && o.DateOfDeath.IsSet() {
		return true
	}

	return false
}

// SetDateOfDeath gets a reference to the given NullableString and assigns it to the DateOfDeath field.
func (o *CzechBankIdProviderOutput) SetDateOfDeath(v string) {
	o.DateOfDeath.Set(&v)
}
// SetDateOfDeathNil sets the value for DateOfDeath to be an explicit nil
func (o *CzechBankIdProviderOutput) SetDateOfDeathNil() {
	o.DateOfDeath.Set(nil)
}

// UnsetDateOfDeath ensures that no value is present for DateOfDeath, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetDateOfDeath() {
	o.DateOfDeath.Unset()
}

// GetBirthPlace returns the BirthPlace field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetBirthPlace() string {
	if o == nil || IsNil(o.BirthPlace.Get()) {
		var ret string
		return ret
	}
	return *o.BirthPlace.Get()
}

// GetBirthPlaceOk returns a tuple with the BirthPlace field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetBirthPlaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BirthPlace.Get(), o.BirthPlace.IsSet()
}

// HasBirthPlace returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasBirthPlace() bool {
	if o != nil && o.BirthPlace.IsSet() {
		return true
	}

	return false
}

// SetBirthPlace gets a reference to the given NullableString and assigns it to the BirthPlace field.
func (o *CzechBankIdProviderOutput) SetBirthPlace(v string) {
	o.BirthPlace.Set(&v)
}
// SetBirthPlaceNil sets the value for BirthPlace to be an explicit nil
func (o *CzechBankIdProviderOutput) SetBirthPlaceNil() {
	o.BirthPlace.Set(nil)
}

// UnsetBirthPlace ensures that no value is present for BirthPlace, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetBirthPlace() {
	o.BirthPlace.Unset()
}

// GetBirthCountry returns the BirthCountry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetBirthCountry() string {
	if o == nil || IsNil(o.BirthCountry.Get()) {
		var ret string
		return ret
	}
	return *o.BirthCountry.Get()
}

// GetBirthCountryOk returns a tuple with the BirthCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetBirthCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BirthCountry.Get(), o.BirthCountry.IsSet()
}

// HasBirthCountry returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasBirthCountry() bool {
	if o != nil && o.BirthCountry.IsSet() {
		return true
	}

	return false
}

// SetBirthCountry gets a reference to the given NullableString and assigns it to the BirthCountry field.
func (o *CzechBankIdProviderOutput) SetBirthCountry(v string) {
	o.BirthCountry.Set(&v)
}
// SetBirthCountryNil sets the value for BirthCountry to be an explicit nil
func (o *CzechBankIdProviderOutput) SetBirthCountryNil() {
	o.BirthCountry.Set(nil)
}

// UnsetBirthCountry ensures that no value is present for BirthCountry, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetBirthCountry() {
	o.BirthCountry.Unset()
}

// GetPrimaryNationality returns the PrimaryNationality field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetPrimaryNationality() string {
	if o == nil || IsNil(o.PrimaryNationality.Get()) {
		var ret string
		return ret
	}
	return *o.PrimaryNationality.Get()
}

// GetPrimaryNationalityOk returns a tuple with the PrimaryNationality field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetPrimaryNationalityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrimaryNationality.Get(), o.PrimaryNationality.IsSet()
}

// HasPrimaryNationality returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasPrimaryNationality() bool {
	if o != nil && o.PrimaryNationality.IsSet() {
		return true
	}

	return false
}

// SetPrimaryNationality gets a reference to the given NullableString and assigns it to the PrimaryNationality field.
func (o *CzechBankIdProviderOutput) SetPrimaryNationality(v string) {
	o.PrimaryNationality.Set(&v)
}
// SetPrimaryNationalityNil sets the value for PrimaryNationality to be an explicit nil
func (o *CzechBankIdProviderOutput) SetPrimaryNationalityNil() {
	o.PrimaryNationality.Set(nil)
}

// UnsetPrimaryNationality ensures that no value is present for PrimaryNationality, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetPrimaryNationality() {
	o.PrimaryNationality.Unset()
}

// GetNationalities returns the Nationalities field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetNationalities() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Nationalities
}

// GetNationalitiesOk returns a tuple with the Nationalities field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetNationalitiesOk() ([]string, bool) {
	if o == nil || IsNil(o.Nationalities) {
		return nil, false
	}
	return o.Nationalities, true
}

// HasNationalities returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasNationalities() bool {
	if o != nil && !IsNil(o.Nationalities) {
		return true
	}

	return false
}

// SetNationalities gets a reference to the given []string and assigns it to the Nationalities field.
func (o *CzechBankIdProviderOutput) SetNationalities(v []string) {
	o.Nationalities = v
}

// GetMaritalStatus returns the MaritalStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetMaritalStatus() string {
	if o == nil || IsNil(o.MaritalStatus.Get()) {
		var ret string
		return ret
	}
	return *o.MaritalStatus.Get()
}

// GetMaritalStatusOk returns a tuple with the MaritalStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetMaritalStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaritalStatus.Get(), o.MaritalStatus.IsSet()
}

// HasMaritalStatus returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasMaritalStatus() bool {
	if o != nil && o.MaritalStatus.IsSet() {
		return true
	}

	return false
}

// SetMaritalStatus gets a reference to the given NullableString and assigns it to the MaritalStatus field.
func (o *CzechBankIdProviderOutput) SetMaritalStatus(v string) {
	o.MaritalStatus.Set(&v)
}
// SetMaritalStatusNil sets the value for MaritalStatus to be an explicit nil
func (o *CzechBankIdProviderOutput) SetMaritalStatusNil() {
	o.MaritalStatus.Set(nil)
}

// UnsetMaritalStatus ensures that no value is present for MaritalStatus, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetMaritalStatus() {
	o.MaritalStatus.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *CzechBankIdProviderOutput) SetEmail(v string) {
	o.Email.Set(&v)
}
// SetEmailNil sets the value for Email to be an explicit nil
func (o *CzechBankIdProviderOutput) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetEmail() {
	o.Email.Unset()
}

// GetEmailVerified returns the EmailVerified field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetEmailVerified() bool {
	if o == nil || IsNil(o.EmailVerified.Get()) {
		var ret bool
		return ret
	}
	return *o.EmailVerified.Get()
}

// GetEmailVerifiedOk returns a tuple with the EmailVerified field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetEmailVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmailVerified.Get(), o.EmailVerified.IsSet()
}

// HasEmailVerified returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasEmailVerified() bool {
	if o != nil && o.EmailVerified.IsSet() {
		return true
	}

	return false
}

// SetEmailVerified gets a reference to the given NullableBool and assigns it to the EmailVerified field.
func (o *CzechBankIdProviderOutput) SetEmailVerified(v bool) {
	o.EmailVerified.Set(&v)
}
// SetEmailVerifiedNil sets the value for EmailVerified to be an explicit nil
func (o *CzechBankIdProviderOutput) SetEmailVerifiedNil() {
	o.EmailVerified.Set(nil)
}

// UnsetEmailVerified ensures that no value is present for EmailVerified, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetEmailVerified() {
	o.EmailVerified.Unset()
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneNumber.Get()
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneNumber.Get(), o.PhoneNumber.IsSet()
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber.IsSet() {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given NullableString and assigns it to the PhoneNumber field.
func (o *CzechBankIdProviderOutput) SetPhoneNumber(v string) {
	o.PhoneNumber.Set(&v)
}
// SetPhoneNumberNil sets the value for PhoneNumber to be an explicit nil
func (o *CzechBankIdProviderOutput) SetPhoneNumberNil() {
	o.PhoneNumber.Set(nil)
}

// UnsetPhoneNumber ensures that no value is present for PhoneNumber, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetPhoneNumber() {
	o.PhoneNumber.Unset()
}

// GetPhoneNumberVerified returns the PhoneNumberVerified field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetPhoneNumberVerified() bool {
	if o == nil || IsNil(o.PhoneNumberVerified.Get()) {
		var ret bool
		return ret
	}
	return *o.PhoneNumberVerified.Get()
}

// GetPhoneNumberVerifiedOk returns a tuple with the PhoneNumberVerified field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetPhoneNumberVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneNumberVerified.Get(), o.PhoneNumberVerified.IsSet()
}

// HasPhoneNumberVerified returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasPhoneNumberVerified() bool {
	if o != nil && o.PhoneNumberVerified.IsSet() {
		return true
	}

	return false
}

// SetPhoneNumberVerified gets a reference to the given NullableBool and assigns it to the PhoneNumberVerified field.
func (o *CzechBankIdProviderOutput) SetPhoneNumberVerified(v bool) {
	o.PhoneNumberVerified.Set(&v)
}
// SetPhoneNumberVerifiedNil sets the value for PhoneNumberVerified to be an explicit nil
func (o *CzechBankIdProviderOutput) SetPhoneNumberVerifiedNil() {
	o.PhoneNumberVerified.Set(nil)
}

// UnsetPhoneNumberVerified ensures that no value is present for PhoneNumberVerified, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetPhoneNumberVerified() {
	o.PhoneNumberVerified.Unset()
}

// GetIsPoliticallyExposedPerson returns the IsPoliticallyExposedPerson field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetIsPoliticallyExposedPerson() bool {
	if o == nil || IsNil(o.IsPoliticallyExposedPerson.Get()) {
		var ret bool
		return ret
	}
	return *o.IsPoliticallyExposedPerson.Get()
}

// GetIsPoliticallyExposedPersonOk returns a tuple with the IsPoliticallyExposedPerson field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetIsPoliticallyExposedPersonOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsPoliticallyExposedPerson.Get(), o.IsPoliticallyExposedPerson.IsSet()
}

// HasIsPoliticallyExposedPerson returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasIsPoliticallyExposedPerson() bool {
	if o != nil && o.IsPoliticallyExposedPerson.IsSet() {
		return true
	}

	return false
}

// SetIsPoliticallyExposedPerson gets a reference to the given NullableBool and assigns it to the IsPoliticallyExposedPerson field.
func (o *CzechBankIdProviderOutput) SetIsPoliticallyExposedPerson(v bool) {
	o.IsPoliticallyExposedPerson.Set(&v)
}
// SetIsPoliticallyExposedPersonNil sets the value for IsPoliticallyExposedPerson to be an explicit nil
func (o *CzechBankIdProviderOutput) SetIsPoliticallyExposedPersonNil() {
	o.IsPoliticallyExposedPerson.Set(nil)
}

// UnsetIsPoliticallyExposedPerson ensures that no value is present for IsPoliticallyExposedPerson, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetIsPoliticallyExposedPerson() {
	o.IsPoliticallyExposedPerson.Unset()
}

// GetLimitedLegalCapacity returns the LimitedLegalCapacity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetLimitedLegalCapacity() bool {
	if o == nil || IsNil(o.LimitedLegalCapacity.Get()) {
		var ret bool
		return ret
	}
	return *o.LimitedLegalCapacity.Get()
}

// GetLimitedLegalCapacityOk returns a tuple with the LimitedLegalCapacity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetLimitedLegalCapacityOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.LimitedLegalCapacity.Get(), o.LimitedLegalCapacity.IsSet()
}

// HasLimitedLegalCapacity returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasLimitedLegalCapacity() bool {
	if o != nil && o.LimitedLegalCapacity.IsSet() {
		return true
	}

	return false
}

// SetLimitedLegalCapacity gets a reference to the given NullableBool and assigns it to the LimitedLegalCapacity field.
func (o *CzechBankIdProviderOutput) SetLimitedLegalCapacity(v bool) {
	o.LimitedLegalCapacity.Set(&v)
}
// SetLimitedLegalCapacityNil sets the value for LimitedLegalCapacity to be an explicit nil
func (o *CzechBankIdProviderOutput) SetLimitedLegalCapacityNil() {
	o.LimitedLegalCapacity.Set(nil)
}

// UnsetLimitedLegalCapacity ensures that no value is present for LimitedLegalCapacity, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetLimitedLegalCapacity() {
	o.LimitedLegalCapacity.Unset()
}

// GetVerification returns the Verification field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetVerification() CzechBankIdVerification {
	if o == nil || IsNil(o.Verification.Get()) {
		var ret CzechBankIdVerification
		return ret
	}
	return *o.Verification.Get()
}

// GetVerificationOk returns a tuple with the Verification field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetVerificationOk() (*CzechBankIdVerification, bool) {
	if o == nil {
		return nil, false
	}
	return o.Verification.Get(), o.Verification.IsSet()
}

// HasVerification returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasVerification() bool {
	if o != nil && o.Verification.IsSet() {
		return true
	}

	return false
}

// SetVerification gets a reference to the given NullableCzechBankIdVerification and assigns it to the Verification field.
func (o *CzechBankIdProviderOutput) SetVerification(v CzechBankIdVerification) {
	o.Verification.Set(&v)
}
// SetVerificationNil sets the value for Verification to be an explicit nil
func (o *CzechBankIdProviderOutput) SetVerificationNil() {
	o.Verification.Set(nil)
}

// UnsetVerification ensures that no value is present for Verification, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetVerification() {
	o.Verification.Unset()
}

// GetAddresses returns the Addresses field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetAddresses() []CzechBankIdAddress {
	if o == nil {
		var ret []CzechBankIdAddress
		return ret
	}
	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetAddressesOk() ([]CzechBankIdAddress, bool) {
	if o == nil || IsNil(o.Addresses) {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasAddresses() bool {
	if o != nil && !IsNil(o.Addresses) {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []CzechBankIdAddress and assigns it to the Addresses field.
func (o *CzechBankIdProviderOutput) SetAddresses(v []CzechBankIdAddress) {
	o.Addresses = v
}

// GetIdCards returns the IdCards field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetIdCards() []CzechBankIdCard {
	if o == nil {
		var ret []CzechBankIdCard
		return ret
	}
	return o.IdCards
}

// GetIdCardsOk returns a tuple with the IdCards field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetIdCardsOk() ([]CzechBankIdCard, bool) {
	if o == nil || IsNil(o.IdCards) {
		return nil, false
	}
	return o.IdCards, true
}

// HasIdCards returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasIdCards() bool {
	if o != nil && !IsNil(o.IdCards) {
		return true
	}

	return false
}

// SetIdCards gets a reference to the given []CzechBankIdCard and assigns it to the IdCards field.
func (o *CzechBankIdProviderOutput) SetIdCards(v []CzechBankIdCard) {
	o.IdCards = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *CzechBankIdProviderOutput) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}
// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *CzechBankIdProviderOutput) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetZoneInfo returns the ZoneInfo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetZoneInfo() string {
	if o == nil || IsNil(o.ZoneInfo.Get()) {
		var ret string
		return ret
	}
	return *o.ZoneInfo.Get()
}

// GetZoneInfoOk returns a tuple with the ZoneInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetZoneInfoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ZoneInfo.Get(), o.ZoneInfo.IsSet()
}

// HasZoneInfo returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasZoneInfo() bool {
	if o != nil && o.ZoneInfo.IsSet() {
		return true
	}

	return false
}

// SetZoneInfo gets a reference to the given NullableString and assigns it to the ZoneInfo field.
func (o *CzechBankIdProviderOutput) SetZoneInfo(v string) {
	o.ZoneInfo.Set(&v)
}
// SetZoneInfoNil sets the value for ZoneInfo to be an explicit nil
func (o *CzechBankIdProviderOutput) SetZoneInfoNil() {
	o.ZoneInfo.Set(nil)
}

// UnsetZoneInfo ensures that no value is present for ZoneInfo, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetZoneInfo() {
	o.ZoneInfo.Unset()
}

// GetLocale returns the Locale field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetLocale() string {
	if o == nil || IsNil(o.Locale.Get()) {
		var ret string
		return ret
	}
	return *o.Locale.Get()
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locale.Get(), o.Locale.IsSet()
}

// HasLocale returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasLocale() bool {
	if o != nil && o.Locale.IsSet() {
		return true
	}

	return false
}

// SetLocale gets a reference to the given NullableString and assigns it to the Locale field.
func (o *CzechBankIdProviderOutput) SetLocale(v string) {
	o.Locale.Set(&v)
}
// SetLocaleNil sets the value for Locale to be an explicit nil
func (o *CzechBankIdProviderOutput) SetLocaleNil() {
	o.Locale.Set(nil)
}

// UnsetLocale ensures that no value is present for Locale, not even an explicit nil
func (o *CzechBankIdProviderOutput) UnsetLocale() {
	o.Locale.Unset()
}

// GetTitles returns the Titles field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdProviderOutput) GetTitles() []CzechBankIdTitle {
	if o == nil {
		var ret []CzechBankIdTitle
		return ret
	}
	return o.Titles
}

// GetTitlesOk returns a tuple with the Titles field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdProviderOutput) GetTitlesOk() ([]CzechBankIdTitle, bool) {
	if o == nil || IsNil(o.Titles) {
		return nil, false
	}
	return o.Titles, true
}

// HasTitles returns a boolean if a field has been set.
func (o *CzechBankIdProviderOutput) HasTitles() bool {
	if o != nil && !IsNil(o.Titles) {
		return true
	}

	return false
}

// SetTitles gets a reference to the given []CzechBankIdTitle and assigns it to the Titles field.
func (o *CzechBankIdProviderOutput) SetTitles(v []CzechBankIdTitle) {
	o.Titles = v
}

func (o CzechBankIdProviderOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CzechBankIdProviderOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.SubjectIdentifier.IsSet() {
		toSerialize["subjectIdentifier"] = o.SubjectIdentifier.Get()
	}
	if o.FullName.IsSet() {
		toSerialize["fullName"] = o.FullName.Get()
	}
	if o.GivenName.IsSet() {
		toSerialize["givenName"] = o.GivenName.Get()
	}
	if o.FamilyName.IsSet() {
		toSerialize["familyName"] = o.FamilyName.Get()
	}
	if o.MiddleName.IsSet() {
		toSerialize["middleName"] = o.MiddleName.Get()
	}
	if o.Nickname.IsSet() {
		toSerialize["nickname"] = o.Nickname.Get()
	}
	if o.PreferredUsername.IsSet() {
		toSerialize["preferredUsername"] = o.PreferredUsername.Get()
	}
	if o.Gender.IsSet() {
		toSerialize["gender"] = o.Gender.Get()
	}
	if o.DateOfBirth.IsSet() {
		toSerialize["dateOfBirth"] = o.DateOfBirth.Get()
	}
	if o.BirthNumber.IsSet() {
		toSerialize["birthNumber"] = o.BirthNumber.Get()
	}
	if o.Age.IsSet() {
		toSerialize["age"] = o.Age.Get()
	}
	if o.IsAdult.IsSet() {
		toSerialize["isAdult"] = o.IsAdult.Get()
	}
	if o.DateOfDeath.IsSet() {
		toSerialize["dateOfDeath"] = o.DateOfDeath.Get()
	}
	if o.BirthPlace.IsSet() {
		toSerialize["birthPlace"] = o.BirthPlace.Get()
	}
	if o.BirthCountry.IsSet() {
		toSerialize["birthCountry"] = o.BirthCountry.Get()
	}
	if o.PrimaryNationality.IsSet() {
		toSerialize["primaryNationality"] = o.PrimaryNationality.Get()
	}
	if o.Nationalities != nil {
		toSerialize["nationalities"] = o.Nationalities
	}
	if o.MaritalStatus.IsSet() {
		toSerialize["maritalStatus"] = o.MaritalStatus.Get()
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	if o.EmailVerified.IsSet() {
		toSerialize["emailVerified"] = o.EmailVerified.Get()
	}
	if o.PhoneNumber.IsSet() {
		toSerialize["phoneNumber"] = o.PhoneNumber.Get()
	}
	if o.PhoneNumberVerified.IsSet() {
		toSerialize["phoneNumberVerified"] = o.PhoneNumberVerified.Get()
	}
	if o.IsPoliticallyExposedPerson.IsSet() {
		toSerialize["isPoliticallyExposedPerson"] = o.IsPoliticallyExposedPerson.Get()
	}
	if o.LimitedLegalCapacity.IsSet() {
		toSerialize["limitedLegalCapacity"] = o.LimitedLegalCapacity.Get()
	}
	if o.Verification.IsSet() {
		toSerialize["verification"] = o.Verification.Get()
	}
	if o.Addresses != nil {
		toSerialize["addresses"] = o.Addresses
	}
	if o.IdCards != nil {
		toSerialize["idCards"] = o.IdCards
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updatedAt"] = o.UpdatedAt.Get()
	}
	if o.ZoneInfo.IsSet() {
		toSerialize["zoneInfo"] = o.ZoneInfo.Get()
	}
	if o.Locale.IsSet() {
		toSerialize["locale"] = o.Locale.Get()
	}
	if o.Titles != nil {
		toSerialize["titles"] = o.Titles
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CzechBankIdProviderOutput) UnmarshalJSON(data []byte) (err error) {
	varCzechBankIdProviderOutput := _CzechBankIdProviderOutput{}

	err = json.Unmarshal(data, &varCzechBankIdProviderOutput)

	if err != nil {
		return err
	}

	*o = CzechBankIdProviderOutput(varCzechBankIdProviderOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "subjectIdentifier")
		delete(additionalProperties, "fullName")
		delete(additionalProperties, "givenName")
		delete(additionalProperties, "familyName")
		delete(additionalProperties, "middleName")
		delete(additionalProperties, "nickname")
		delete(additionalProperties, "preferredUsername")
		delete(additionalProperties, "gender")
		delete(additionalProperties, "dateOfBirth")
		delete(additionalProperties, "birthNumber")
		delete(additionalProperties, "age")
		delete(additionalProperties, "isAdult")
		delete(additionalProperties, "dateOfDeath")
		delete(additionalProperties, "birthPlace")
		delete(additionalProperties, "birthCountry")
		delete(additionalProperties, "primaryNationality")
		delete(additionalProperties, "nationalities")
		delete(additionalProperties, "maritalStatus")
		delete(additionalProperties, "email")
		delete(additionalProperties, "emailVerified")
		delete(additionalProperties, "phoneNumber")
		delete(additionalProperties, "phoneNumberVerified")
		delete(additionalProperties, "isPoliticallyExposedPerson")
		delete(additionalProperties, "limitedLegalCapacity")
		delete(additionalProperties, "verification")
		delete(additionalProperties, "addresses")
		delete(additionalProperties, "idCards")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "zoneInfo")
		delete(additionalProperties, "locale")
		delete(additionalProperties, "titles")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCzechBankIdProviderOutput struct {
	value *CzechBankIdProviderOutput
	isSet bool
}

func (v NullableCzechBankIdProviderOutput) Get() *CzechBankIdProviderOutput {
	return v.value
}

func (v *NullableCzechBankIdProviderOutput) Set(val *CzechBankIdProviderOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableCzechBankIdProviderOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableCzechBankIdProviderOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCzechBankIdProviderOutput(val *CzechBankIdProviderOutput) *NullableCzechBankIdProviderOutput {
	return &NullableCzechBankIdProviderOutput{value: val, isSet: true}
}

func (v NullableCzechBankIdProviderOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCzechBankIdProviderOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


