/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
	"fmt"
)

// checks if the CzechBankIdCard type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CzechBankIdCard{}

// CzechBankIdCard struct for CzechBankIdCard
type CzechBankIdCard struct {
	// The identity document type code.              Possible values are:              - ID - Identity card - P - Passport - DL - Driving license - IR - Residence permit - VS - Visa permit label - PS - Residential label - IX - Book with residence permit - IE - Form with temporary residence - OP - Identity card – without machine readable zone - CA - Passport of the Czech Republic resident – without machine readable zone - UNKNOWN - Unknown id card type
	Type string `json:"type"`
	// The localized identity document type description.
	Description NullableString `json:"description,omitempty"`
	// The country for which the identity document is valid.
	Country string `json:"country"`
	// The identity document number.
	Number string `json:"number"`
	// The identity document expiration date.
	ValidTo string `json:"validTo"`
	// The office that issued the identity document.
	Issuer NullableString `json:"issuer,omitempty"`
	// The identity document issue date.
	IssueDate NullableString `json:"issueDate,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CzechBankIdCard CzechBankIdCard

// NewCzechBankIdCard instantiates a new CzechBankIdCard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCzechBankIdCard(type_ string, country string, number string, validTo string) *CzechBankIdCard {
	this := CzechBankIdCard{}
	this.Type = type_
	this.Country = country
	this.Number = number
	this.ValidTo = validTo
	return &this
}

// NewCzechBankIdCardWithDefaults instantiates a new CzechBankIdCard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCzechBankIdCardWithDefaults() *CzechBankIdCard {
	this := CzechBankIdCard{}
	return &this
}

// GetType returns the Type field value
func (o *CzechBankIdCard) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CzechBankIdCard) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CzechBankIdCard) SetType(v string) {
	o.Type = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdCard) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdCard) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CzechBankIdCard) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CzechBankIdCard) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CzechBankIdCard) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CzechBankIdCard) UnsetDescription() {
	o.Description.Unset()
}

// GetCountry returns the Country field value
func (o *CzechBankIdCard) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *CzechBankIdCard) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *CzechBankIdCard) SetCountry(v string) {
	o.Country = v
}

// GetNumber returns the Number field value
func (o *CzechBankIdCard) GetNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Number
}

// GetNumberOk returns a tuple with the Number field value
// and a boolean to check if the value has been set.
func (o *CzechBankIdCard) GetNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Number, true
}

// SetNumber sets field value
func (o *CzechBankIdCard) SetNumber(v string) {
	o.Number = v
}

// GetValidTo returns the ValidTo field value
func (o *CzechBankIdCard) GetValidTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ValidTo
}

// GetValidToOk returns a tuple with the ValidTo field value
// and a boolean to check if the value has been set.
func (o *CzechBankIdCard) GetValidToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidTo, true
}

// SetValidTo sets field value
func (o *CzechBankIdCard) SetValidTo(v string) {
	o.ValidTo = v
}

// GetIssuer returns the Issuer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdCard) GetIssuer() string {
	if o == nil || IsNil(o.Issuer.Get()) {
		var ret string
		return ret
	}
	return *o.Issuer.Get()
}

// GetIssuerOk returns a tuple with the Issuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdCard) GetIssuerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Issuer.Get(), o.Issuer.IsSet()
}

// HasIssuer returns a boolean if a field has been set.
func (o *CzechBankIdCard) HasIssuer() bool {
	if o != nil && o.Issuer.IsSet() {
		return true
	}

	return false
}

// SetIssuer gets a reference to the given NullableString and assigns it to the Issuer field.
func (o *CzechBankIdCard) SetIssuer(v string) {
	o.Issuer.Set(&v)
}
// SetIssuerNil sets the value for Issuer to be an explicit nil
func (o *CzechBankIdCard) SetIssuerNil() {
	o.Issuer.Set(nil)
}

// UnsetIssuer ensures that no value is present for Issuer, not even an explicit nil
func (o *CzechBankIdCard) UnsetIssuer() {
	o.Issuer.Unset()
}

// GetIssueDate returns the IssueDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdCard) GetIssueDate() string {
	if o == nil || IsNil(o.IssueDate.Get()) {
		var ret string
		return ret
	}
	return *o.IssueDate.Get()
}

// GetIssueDateOk returns a tuple with the IssueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdCard) GetIssueDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IssueDate.Get(), o.IssueDate.IsSet()
}

// HasIssueDate returns a boolean if a field has been set.
func (o *CzechBankIdCard) HasIssueDate() bool {
	if o != nil && o.IssueDate.IsSet() {
		return true
	}

	return false
}

// SetIssueDate gets a reference to the given NullableString and assigns it to the IssueDate field.
func (o *CzechBankIdCard) SetIssueDate(v string) {
	o.IssueDate.Set(&v)
}
// SetIssueDateNil sets the value for IssueDate to be an explicit nil
func (o *CzechBankIdCard) SetIssueDateNil() {
	o.IssueDate.Set(nil)
}

// UnsetIssueDate ensures that no value is present for IssueDate, not even an explicit nil
func (o *CzechBankIdCard) UnsetIssueDate() {
	o.IssueDate.Unset()
}

func (o CzechBankIdCard) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CzechBankIdCard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["country"] = o.Country
	toSerialize["number"] = o.Number
	toSerialize["validTo"] = o.ValidTo
	if o.Issuer.IsSet() {
		toSerialize["issuer"] = o.Issuer.Get()
	}
	if o.IssueDate.IsSet() {
		toSerialize["issueDate"] = o.IssueDate.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CzechBankIdCard) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"country",
		"number",
		"validTo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCzechBankIdCard := _CzechBankIdCard{}

	err = json.Unmarshal(data, &varCzechBankIdCard)

	if err != nil {
		return err
	}

	*o = CzechBankIdCard(varCzechBankIdCard)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "description")
		delete(additionalProperties, "country")
		delete(additionalProperties, "number")
		delete(additionalProperties, "validTo")
		delete(additionalProperties, "issuer")
		delete(additionalProperties, "issueDate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCzechBankIdCard struct {
	value *CzechBankIdCard
	isSet bool
}

func (v NullableCzechBankIdCard) Get() *CzechBankIdCard {
	return v.value
}

func (v *NullableCzechBankIdCard) Set(val *CzechBankIdCard) {
	v.value = val
	v.isSet = true
}

func (v NullableCzechBankIdCard) IsSet() bool {
	return v.isSet
}

func (v *NullableCzechBankIdCard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCzechBankIdCard(val *CzechBankIdCard) *NullableCzechBankIdCard {
	return &NullableCzechBankIdCard{value: val, isSet: true}
}

func (v NullableCzechBankIdCard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCzechBankIdCard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


