/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the UgandaNidMatch2ProviderOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UgandaNidMatch2ProviderOutput{}

// UgandaNidMatch2ProviderOutput Exposed properties for the `uganda-nid-match-2` Provider which do not directly map to the normalized IdentityData model.
type UgandaNidMatch2ProviderOutput struct {
	// Outcome of verifying the national identification number in the NIRA database.
	NationalIdNumber NullableUgandaNidMatch2NationalIdNumberField `json:"nationalIdNumber,omitempty"`
	// Outcome of comparing the submitted card number with the NIRA database.
	SecondaryIdNumber NullableUgandaNidMatch2SecondaryIdNumberField `json:"secondaryIdNumber,omitempty"`
	// Outcome of comparing the submitted date of birth with the NIRA database.
	DateOfBirth NullableUgandaNidMatch2DateOfBirthField `json:"dateOfBirth,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UgandaNidMatch2ProviderOutput UgandaNidMatch2ProviderOutput

// NewUgandaNidMatch2ProviderOutput instantiates a new UgandaNidMatch2ProviderOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUgandaNidMatch2ProviderOutput() *UgandaNidMatch2ProviderOutput {
	this := UgandaNidMatch2ProviderOutput{}
	return &this
}

// NewUgandaNidMatch2ProviderOutputWithDefaults instantiates a new UgandaNidMatch2ProviderOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUgandaNidMatch2ProviderOutputWithDefaults() *UgandaNidMatch2ProviderOutput {
	this := UgandaNidMatch2ProviderOutput{}
	return &this
}

// GetNationalIdNumber returns the NationalIdNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UgandaNidMatch2ProviderOutput) GetNationalIdNumber() UgandaNidMatch2NationalIdNumberField {
	if o == nil || IsNil(o.NationalIdNumber.Get()) {
		var ret UgandaNidMatch2NationalIdNumberField
		return ret
	}
	return *o.NationalIdNumber.Get()
}

// GetNationalIdNumberOk returns a tuple with the NationalIdNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UgandaNidMatch2ProviderOutput) GetNationalIdNumberOk() (*UgandaNidMatch2NationalIdNumberField, bool) {
	if o == nil {
		return nil, false
	}
	return o.NationalIdNumber.Get(), o.NationalIdNumber.IsSet()
}

// HasNationalIdNumber returns a boolean if a field has been set.
func (o *UgandaNidMatch2ProviderOutput) HasNationalIdNumber() bool {
	if o != nil && o.NationalIdNumber.IsSet() {
		return true
	}

	return false
}

// SetNationalIdNumber gets a reference to the given NullableUgandaNidMatch2NationalIdNumberField and assigns it to the NationalIdNumber field.
func (o *UgandaNidMatch2ProviderOutput) SetNationalIdNumber(v UgandaNidMatch2NationalIdNumberField) {
	o.NationalIdNumber.Set(&v)
}
// SetNationalIdNumberNil sets the value for NationalIdNumber to be an explicit nil
func (o *UgandaNidMatch2ProviderOutput) SetNationalIdNumberNil() {
	o.NationalIdNumber.Set(nil)
}

// UnsetNationalIdNumber ensures that no value is present for NationalIdNumber, not even an explicit nil
func (o *UgandaNidMatch2ProviderOutput) UnsetNationalIdNumber() {
	o.NationalIdNumber.Unset()
}

// GetSecondaryIdNumber returns the SecondaryIdNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UgandaNidMatch2ProviderOutput) GetSecondaryIdNumber() UgandaNidMatch2SecondaryIdNumberField {
	if o == nil || IsNil(o.SecondaryIdNumber.Get()) {
		var ret UgandaNidMatch2SecondaryIdNumberField
		return ret
	}
	return *o.SecondaryIdNumber.Get()
}

// GetSecondaryIdNumberOk returns a tuple with the SecondaryIdNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UgandaNidMatch2ProviderOutput) GetSecondaryIdNumberOk() (*UgandaNidMatch2SecondaryIdNumberField, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecondaryIdNumber.Get(), o.SecondaryIdNumber.IsSet()
}

// HasSecondaryIdNumber returns a boolean if a field has been set.
func (o *UgandaNidMatch2ProviderOutput) HasSecondaryIdNumber() bool {
	if o != nil && o.SecondaryIdNumber.IsSet() {
		return true
	}

	return false
}

// SetSecondaryIdNumber gets a reference to the given NullableUgandaNidMatch2SecondaryIdNumberField and assigns it to the SecondaryIdNumber field.
func (o *UgandaNidMatch2ProviderOutput) SetSecondaryIdNumber(v UgandaNidMatch2SecondaryIdNumberField) {
	o.SecondaryIdNumber.Set(&v)
}
// SetSecondaryIdNumberNil sets the value for SecondaryIdNumber to be an explicit nil
func (o *UgandaNidMatch2ProviderOutput) SetSecondaryIdNumberNil() {
	o.SecondaryIdNumber.Set(nil)
}

// UnsetSecondaryIdNumber ensures that no value is present for SecondaryIdNumber, not even an explicit nil
func (o *UgandaNidMatch2ProviderOutput) UnsetSecondaryIdNumber() {
	o.SecondaryIdNumber.Unset()
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UgandaNidMatch2ProviderOutput) GetDateOfBirth() UgandaNidMatch2DateOfBirthField {
	if o == nil || IsNil(o.DateOfBirth.Get()) {
		var ret UgandaNidMatch2DateOfBirthField
		return ret
	}
	return *o.DateOfBirth.Get()
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UgandaNidMatch2ProviderOutput) GetDateOfBirthOk() (*UgandaNidMatch2DateOfBirthField, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfBirth.Get(), o.DateOfBirth.IsSet()
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *UgandaNidMatch2ProviderOutput) HasDateOfBirth() bool {
	if o != nil && o.DateOfBirth.IsSet() {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given NullableUgandaNidMatch2DateOfBirthField and assigns it to the DateOfBirth field.
func (o *UgandaNidMatch2ProviderOutput) SetDateOfBirth(v UgandaNidMatch2DateOfBirthField) {
	o.DateOfBirth.Set(&v)
}
// SetDateOfBirthNil sets the value for DateOfBirth to be an explicit nil
func (o *UgandaNidMatch2ProviderOutput) SetDateOfBirthNil() {
	o.DateOfBirth.Set(nil)
}

// UnsetDateOfBirth ensures that no value is present for DateOfBirth, not even an explicit nil
func (o *UgandaNidMatch2ProviderOutput) UnsetDateOfBirth() {
	o.DateOfBirth.Unset()
}

func (o UgandaNidMatch2ProviderOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UgandaNidMatch2ProviderOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.NationalIdNumber.IsSet() {
		toSerialize["nationalIdNumber"] = o.NationalIdNumber.Get()
	}
	if o.SecondaryIdNumber.IsSet() {
		toSerialize["secondaryIdNumber"] = o.SecondaryIdNumber.Get()
	}
	if o.DateOfBirth.IsSet() {
		toSerialize["dateOfBirth"] = o.DateOfBirth.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UgandaNidMatch2ProviderOutput) UnmarshalJSON(data []byte) (err error) {
	varUgandaNidMatch2ProviderOutput := _UgandaNidMatch2ProviderOutput{}

	err = json.Unmarshal(data, &varUgandaNidMatch2ProviderOutput)

	if err != nil {
		return err
	}

	*o = UgandaNidMatch2ProviderOutput(varUgandaNidMatch2ProviderOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "nationalIdNumber")
		delete(additionalProperties, "secondaryIdNumber")
		delete(additionalProperties, "dateOfBirth")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUgandaNidMatch2ProviderOutput struct {
	value *UgandaNidMatch2ProviderOutput
	isSet bool
}

func (v NullableUgandaNidMatch2ProviderOutput) Get() *UgandaNidMatch2ProviderOutput {
	return v.value
}

func (v *NullableUgandaNidMatch2ProviderOutput) Set(val *UgandaNidMatch2ProviderOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableUgandaNidMatch2ProviderOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableUgandaNidMatch2ProviderOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUgandaNidMatch2ProviderOutput(val *UgandaNidMatch2ProviderOutput) *NullableUgandaNidMatch2ProviderOutput {
	return &NullableUgandaNidMatch2ProviderOutput{value: val, isSet: true}
}

func (v NullableUgandaNidMatch2ProviderOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUgandaNidMatch2ProviderOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


