/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
	"fmt"
)

// checks if the KoreaTelcoMatchProviderOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KoreaTelcoMatchProviderOutput{}

// KoreaTelcoMatchProviderOutput Exposed properties for the `korea-telco-match` Provider which do not directly map to the normalized IdentityData model.
type KoreaTelcoMatchProviderOutput struct {
	// The verified phone number as submitted by the relying party.
	PhoneNumber string `json:"phoneNumber"`
	// The mobile carrier used for verification. Possible values: <list type=\"bullet\"><item><description>Lgu</description></item><item><description>Skt</description></item><item><description>Kt</description></item></list>
	TeleType string `json:"teleType"`
	// The RaonSecure result code returned by the carrier verification system. \"0000\" indicates a successful match.              Common error codes: - \"0000\": Successful match - \"0001\": Identity Verification Failed - Verification Information Mismatch (General) - \"0002\": Identity Verification Failed - Unable to Verify Phone Number - \"0004\": Identity Verification Failed - Date of Birth Verification Error - \"0005\": Identity Verification Failed - Gender Verification Error - \"0006\": Identity Verification Failed - Name Verification Error - \"0009\": Identity Verification Failed - Device OS Mismatch
	ResultCode string `json:"resultCode"`
	AdditionalProperties map[string]interface{}
}

type _KoreaTelcoMatchProviderOutput KoreaTelcoMatchProviderOutput

// NewKoreaTelcoMatchProviderOutput instantiates a new KoreaTelcoMatchProviderOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKoreaTelcoMatchProviderOutput(phoneNumber string, teleType string, resultCode string) *KoreaTelcoMatchProviderOutput {
	this := KoreaTelcoMatchProviderOutput{}
	this.PhoneNumber = phoneNumber
	this.TeleType = teleType
	this.ResultCode = resultCode
	return &this
}

// NewKoreaTelcoMatchProviderOutputWithDefaults instantiates a new KoreaTelcoMatchProviderOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKoreaTelcoMatchProviderOutputWithDefaults() *KoreaTelcoMatchProviderOutput {
	this := KoreaTelcoMatchProviderOutput{}
	return &this
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *KoreaTelcoMatchProviderOutput) GetPhoneNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *KoreaTelcoMatchProviderOutput) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *KoreaTelcoMatchProviderOutput) SetPhoneNumber(v string) {
	o.PhoneNumber = v
}

// GetTeleType returns the TeleType field value
func (o *KoreaTelcoMatchProviderOutput) GetTeleType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TeleType
}

// GetTeleTypeOk returns a tuple with the TeleType field value
// and a boolean to check if the value has been set.
func (o *KoreaTelcoMatchProviderOutput) GetTeleTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeleType, true
}

// SetTeleType sets field value
func (o *KoreaTelcoMatchProviderOutput) SetTeleType(v string) {
	o.TeleType = v
}

// GetResultCode returns the ResultCode field value
func (o *KoreaTelcoMatchProviderOutput) GetResultCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResultCode
}

// GetResultCodeOk returns a tuple with the ResultCode field value
// and a boolean to check if the value has been set.
func (o *KoreaTelcoMatchProviderOutput) GetResultCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultCode, true
}

// SetResultCode sets field value
func (o *KoreaTelcoMatchProviderOutput) SetResultCode(v string) {
	o.ResultCode = v
}

func (o KoreaTelcoMatchProviderOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KoreaTelcoMatchProviderOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phoneNumber"] = o.PhoneNumber
	toSerialize["teleType"] = o.TeleType
	toSerialize["resultCode"] = o.ResultCode

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KoreaTelcoMatchProviderOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phoneNumber",
		"teleType",
		"resultCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKoreaTelcoMatchProviderOutput := _KoreaTelcoMatchProviderOutput{}

	err = json.Unmarshal(data, &varKoreaTelcoMatchProviderOutput)

	if err != nil {
		return err
	}

	*o = KoreaTelcoMatchProviderOutput(varKoreaTelcoMatchProviderOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "phoneNumber")
		delete(additionalProperties, "teleType")
		delete(additionalProperties, "resultCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKoreaTelcoMatchProviderOutput struct {
	value *KoreaTelcoMatchProviderOutput
	isSet bool
}

func (v NullableKoreaTelcoMatchProviderOutput) Get() *KoreaTelcoMatchProviderOutput {
	return v.value
}

func (v *NullableKoreaTelcoMatchProviderOutput) Set(val *KoreaTelcoMatchProviderOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableKoreaTelcoMatchProviderOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableKoreaTelcoMatchProviderOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKoreaTelcoMatchProviderOutput(val *KoreaTelcoMatchProviderOutput) *NullableKoreaTelcoMatchProviderOutput {
	return &NullableKoreaTelcoMatchProviderOutput{value: val, isSet: true}
}

func (v NullableKoreaTelcoMatchProviderOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKoreaTelcoMatchProviderOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


