/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the CzechBankIdAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CzechBankIdAddress{}

// CzechBankIdAddress struct for CzechBankIdAddress
type CzechBankIdAddress struct {
	// The address type.              Possible values are: - PERMANENT_RESIDENCE - SECONDARY_RESIDENCE - UNKNOWN
	Type NullableString `json:"type,omitempty"`
	// The street name.              This is usually present, but unused for small villages.
	Street NullableString `json:"street,omitempty"`
	// The address land registry number.              This is usually present, but unused for small houses.
	BuildingApartment NullableString `json:"buildingApartment,omitempty"`
	// The additional address house number.              This is usually present, but unused for small villages.
	StreetNumber NullableString `json:"streetNumber,omitempty"`
	// The house evidence number.              This is rarely used in suburbs. An evidence number is used for addresses that are residential, temporary or non-residential buildings, e.g. cabins, garages etc.
	EvidenceNumber NullableString `json:"evidenceNumber,omitempty"`
	// The city name.
	City NullableString `json:"city,omitempty"`
	// The city area name.              This is usually present.
	CityArea NullableString `json:"cityArea,omitempty"`
	// The zip of the address.
	Zipcode NullableString `json:"zipcode,omitempty"`
	// The country code in ISO 3166-1 alpha-2 format.
	Country NullableString `json:"country,omitempty"`
	// The address identifier in the Czech RUIAN address register.              RUIAN is the Czech Register of Territorial Identification, Addresses, and Real Estate. This value identifies the address record in that register and can be used to reconcile the address against Czech government address data.
	RuianReference NullableString `json:"ruianReference,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CzechBankIdAddress CzechBankIdAddress

// NewCzechBankIdAddress instantiates a new CzechBankIdAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCzechBankIdAddress() *CzechBankIdAddress {
	this := CzechBankIdAddress{}
	return &this
}

// NewCzechBankIdAddressWithDefaults instantiates a new CzechBankIdAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCzechBankIdAddressWithDefaults() *CzechBankIdAddress {
	this := CzechBankIdAddress{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdAddress) GetType() string {
	if o == nil || IsNil(o.Type.Get()) {
		var ret string
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdAddress) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *CzechBankIdAddress) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableString and assigns it to the Type field.
func (o *CzechBankIdAddress) SetType(v string) {
	o.Type.Set(&v)
}
// SetTypeNil sets the value for Type to be an explicit nil
func (o *CzechBankIdAddress) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *CzechBankIdAddress) UnsetType() {
	o.Type.Unset()
}

// GetStreet returns the Street field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdAddress) GetStreet() string {
	if o == nil || IsNil(o.Street.Get()) {
		var ret string
		return ret
	}
	return *o.Street.Get()
}

// GetStreetOk returns a tuple with the Street field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdAddress) GetStreetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Street.Get(), o.Street.IsSet()
}

// HasStreet returns a boolean if a field has been set.
func (o *CzechBankIdAddress) HasStreet() bool {
	if o != nil && o.Street.IsSet() {
		return true
	}

	return false
}

// SetStreet gets a reference to the given NullableString and assigns it to the Street field.
func (o *CzechBankIdAddress) SetStreet(v string) {
	o.Street.Set(&v)
}
// SetStreetNil sets the value for Street to be an explicit nil
func (o *CzechBankIdAddress) SetStreetNil() {
	o.Street.Set(nil)
}

// UnsetStreet ensures that no value is present for Street, not even an explicit nil
func (o *CzechBankIdAddress) UnsetStreet() {
	o.Street.Unset()
}

// GetBuildingApartment returns the BuildingApartment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdAddress) GetBuildingApartment() string {
	if o == nil || IsNil(o.BuildingApartment.Get()) {
		var ret string
		return ret
	}
	return *o.BuildingApartment.Get()
}

// GetBuildingApartmentOk returns a tuple with the BuildingApartment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdAddress) GetBuildingApartmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BuildingApartment.Get(), o.BuildingApartment.IsSet()
}

// HasBuildingApartment returns a boolean if a field has been set.
func (o *CzechBankIdAddress) HasBuildingApartment() bool {
	if o != nil && o.BuildingApartment.IsSet() {
		return true
	}

	return false
}

// SetBuildingApartment gets a reference to the given NullableString and assigns it to the BuildingApartment field.
func (o *CzechBankIdAddress) SetBuildingApartment(v string) {
	o.BuildingApartment.Set(&v)
}
// SetBuildingApartmentNil sets the value for BuildingApartment to be an explicit nil
func (o *CzechBankIdAddress) SetBuildingApartmentNil() {
	o.BuildingApartment.Set(nil)
}

// UnsetBuildingApartment ensures that no value is present for BuildingApartment, not even an explicit nil
func (o *CzechBankIdAddress) UnsetBuildingApartment() {
	o.BuildingApartment.Unset()
}

// GetStreetNumber returns the StreetNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdAddress) GetStreetNumber() string {
	if o == nil || IsNil(o.StreetNumber.Get()) {
		var ret string
		return ret
	}
	return *o.StreetNumber.Get()
}

// GetStreetNumberOk returns a tuple with the StreetNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdAddress) GetStreetNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StreetNumber.Get(), o.StreetNumber.IsSet()
}

// HasStreetNumber returns a boolean if a field has been set.
func (o *CzechBankIdAddress) HasStreetNumber() bool {
	if o != nil && o.StreetNumber.IsSet() {
		return true
	}

	return false
}

// SetStreetNumber gets a reference to the given NullableString and assigns it to the StreetNumber field.
func (o *CzechBankIdAddress) SetStreetNumber(v string) {
	o.StreetNumber.Set(&v)
}
// SetStreetNumberNil sets the value for StreetNumber to be an explicit nil
func (o *CzechBankIdAddress) SetStreetNumberNil() {
	o.StreetNumber.Set(nil)
}

// UnsetStreetNumber ensures that no value is present for StreetNumber, not even an explicit nil
func (o *CzechBankIdAddress) UnsetStreetNumber() {
	o.StreetNumber.Unset()
}

// GetEvidenceNumber returns the EvidenceNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdAddress) GetEvidenceNumber() string {
	if o == nil || IsNil(o.EvidenceNumber.Get()) {
		var ret string
		return ret
	}
	return *o.EvidenceNumber.Get()
}

// GetEvidenceNumberOk returns a tuple with the EvidenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdAddress) GetEvidenceNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EvidenceNumber.Get(), o.EvidenceNumber.IsSet()
}

// HasEvidenceNumber returns a boolean if a field has been set.
func (o *CzechBankIdAddress) HasEvidenceNumber() bool {
	if o != nil && o.EvidenceNumber.IsSet() {
		return true
	}

	return false
}

// SetEvidenceNumber gets a reference to the given NullableString and assigns it to the EvidenceNumber field.
func (o *CzechBankIdAddress) SetEvidenceNumber(v string) {
	o.EvidenceNumber.Set(&v)
}
// SetEvidenceNumberNil sets the value for EvidenceNumber to be an explicit nil
func (o *CzechBankIdAddress) SetEvidenceNumberNil() {
	o.EvidenceNumber.Set(nil)
}

// UnsetEvidenceNumber ensures that no value is present for EvidenceNumber, not even an explicit nil
func (o *CzechBankIdAddress) UnsetEvidenceNumber() {
	o.EvidenceNumber.Unset()
}

// GetCity returns the City field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdAddress) GetCity() string {
	if o == nil || IsNil(o.City.Get()) {
		var ret string
		return ret
	}
	return *o.City.Get()
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdAddress) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.City.Get(), o.City.IsSet()
}

// HasCity returns a boolean if a field has been set.
func (o *CzechBankIdAddress) HasCity() bool {
	if o != nil && o.City.IsSet() {
		return true
	}

	return false
}

// SetCity gets a reference to the given NullableString and assigns it to the City field.
func (o *CzechBankIdAddress) SetCity(v string) {
	o.City.Set(&v)
}
// SetCityNil sets the value for City to be an explicit nil
func (o *CzechBankIdAddress) SetCityNil() {
	o.City.Set(nil)
}

// UnsetCity ensures that no value is present for City, not even an explicit nil
func (o *CzechBankIdAddress) UnsetCity() {
	o.City.Unset()
}

// GetCityArea returns the CityArea field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdAddress) GetCityArea() string {
	if o == nil || IsNil(o.CityArea.Get()) {
		var ret string
		return ret
	}
	return *o.CityArea.Get()
}

// GetCityAreaOk returns a tuple with the CityArea field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdAddress) GetCityAreaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CityArea.Get(), o.CityArea.IsSet()
}

// HasCityArea returns a boolean if a field has been set.
func (o *CzechBankIdAddress) HasCityArea() bool {
	if o != nil && o.CityArea.IsSet() {
		return true
	}

	return false
}

// SetCityArea gets a reference to the given NullableString and assigns it to the CityArea field.
func (o *CzechBankIdAddress) SetCityArea(v string) {
	o.CityArea.Set(&v)
}
// SetCityAreaNil sets the value for CityArea to be an explicit nil
func (o *CzechBankIdAddress) SetCityAreaNil() {
	o.CityArea.Set(nil)
}

// UnsetCityArea ensures that no value is present for CityArea, not even an explicit nil
func (o *CzechBankIdAddress) UnsetCityArea() {
	o.CityArea.Unset()
}

// GetZipcode returns the Zipcode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdAddress) GetZipcode() string {
	if o == nil || IsNil(o.Zipcode.Get()) {
		var ret string
		return ret
	}
	return *o.Zipcode.Get()
}

// GetZipcodeOk returns a tuple with the Zipcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdAddress) GetZipcodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Zipcode.Get(), o.Zipcode.IsSet()
}

// HasZipcode returns a boolean if a field has been set.
func (o *CzechBankIdAddress) HasZipcode() bool {
	if o != nil && o.Zipcode.IsSet() {
		return true
	}

	return false
}

// SetZipcode gets a reference to the given NullableString and assigns it to the Zipcode field.
func (o *CzechBankIdAddress) SetZipcode(v string) {
	o.Zipcode.Set(&v)
}
// SetZipcodeNil sets the value for Zipcode to be an explicit nil
func (o *CzechBankIdAddress) SetZipcodeNil() {
	o.Zipcode.Set(nil)
}

// UnsetZipcode ensures that no value is present for Zipcode, not even an explicit nil
func (o *CzechBankIdAddress) UnsetZipcode() {
	o.Zipcode.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdAddress) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdAddress) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *CzechBankIdAddress) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *CzechBankIdAddress) SetCountry(v string) {
	o.Country.Set(&v)
}
// SetCountryNil sets the value for Country to be an explicit nil
func (o *CzechBankIdAddress) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *CzechBankIdAddress) UnsetCountry() {
	o.Country.Unset()
}

// GetRuianReference returns the RuianReference field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechBankIdAddress) GetRuianReference() string {
	if o == nil || IsNil(o.RuianReference.Get()) {
		var ret string
		return ret
	}
	return *o.RuianReference.Get()
}

// GetRuianReferenceOk returns a tuple with the RuianReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechBankIdAddress) GetRuianReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RuianReference.Get(), o.RuianReference.IsSet()
}

// HasRuianReference returns a boolean if a field has been set.
func (o *CzechBankIdAddress) HasRuianReference() bool {
	if o != nil && o.RuianReference.IsSet() {
		return true
	}

	return false
}

// SetRuianReference gets a reference to the given NullableString and assigns it to the RuianReference field.
func (o *CzechBankIdAddress) SetRuianReference(v string) {
	o.RuianReference.Set(&v)
}
// SetRuianReferenceNil sets the value for RuianReference to be an explicit nil
func (o *CzechBankIdAddress) SetRuianReferenceNil() {
	o.RuianReference.Set(nil)
}

// UnsetRuianReference ensures that no value is present for RuianReference, not even an explicit nil
func (o *CzechBankIdAddress) UnsetRuianReference() {
	o.RuianReference.Unset()
}

func (o CzechBankIdAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CzechBankIdAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	if o.Street.IsSet() {
		toSerialize["street"] = o.Street.Get()
	}
	if o.BuildingApartment.IsSet() {
		toSerialize["buildingApartment"] = o.BuildingApartment.Get()
	}
	if o.StreetNumber.IsSet() {
		toSerialize["streetNumber"] = o.StreetNumber.Get()
	}
	if o.EvidenceNumber.IsSet() {
		toSerialize["evidenceNumber"] = o.EvidenceNumber.Get()
	}
	if o.City.IsSet() {
		toSerialize["city"] = o.City.Get()
	}
	if o.CityArea.IsSet() {
		toSerialize["cityArea"] = o.CityArea.Get()
	}
	if o.Zipcode.IsSet() {
		toSerialize["zipcode"] = o.Zipcode.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if o.RuianReference.IsSet() {
		toSerialize["ruianReference"] = o.RuianReference.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CzechBankIdAddress) UnmarshalJSON(data []byte) (err error) {
	varCzechBankIdAddress := _CzechBankIdAddress{}

	err = json.Unmarshal(data, &varCzechBankIdAddress)

	if err != nil {
		return err
	}

	*o = CzechBankIdAddress(varCzechBankIdAddress)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "street")
		delete(additionalProperties, "buildingApartment")
		delete(additionalProperties, "streetNumber")
		delete(additionalProperties, "evidenceNumber")
		delete(additionalProperties, "city")
		delete(additionalProperties, "cityArea")
		delete(additionalProperties, "zipcode")
		delete(additionalProperties, "country")
		delete(additionalProperties, "ruianReference")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCzechBankIdAddress struct {
	value *CzechBankIdAddress
	isSet bool
}

func (v NullableCzechBankIdAddress) Get() *CzechBankIdAddress {
	return v.value
}

func (v *NullableCzechBankIdAddress) Set(val *CzechBankIdAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableCzechBankIdAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableCzechBankIdAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCzechBankIdAddress(val *CzechBankIdAddress) *NullableCzechBankIdAddress {
	return &NullableCzechBankIdAddress{value: val, isSet: true}
}

func (v NullableCzechBankIdAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCzechBankIdAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


