/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListProviderContractsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListProviderContractsResponse{}

// ListProviderContractsResponse struct for ListProviderContractsResponse
type ListProviderContractsResponse struct {
	// Contracts for all Providers available to your App, filtered by your App's current test mode setting.
	ProviderContracts []ProviderContract `json:"providerContracts"`
}

type _ListProviderContractsResponse ListProviderContractsResponse

// NewListProviderContractsResponse instantiates a new ListProviderContractsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListProviderContractsResponse(providerContracts []ProviderContract) *ListProviderContractsResponse {
	this := ListProviderContractsResponse{}
	this.ProviderContracts = providerContracts
	return &this
}

// NewListProviderContractsResponseWithDefaults instantiates a new ListProviderContractsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListProviderContractsResponseWithDefaults() *ListProviderContractsResponse {
	this := ListProviderContractsResponse{}
	return &this
}

// GetProviderContracts returns the ProviderContracts field value
func (o *ListProviderContractsResponse) GetProviderContracts() []ProviderContract {
	if o == nil {
		var ret []ProviderContract
		return ret
	}

	return o.ProviderContracts
}

// GetProviderContractsOk returns a tuple with the ProviderContracts field value
// and a boolean to check if the value has been set.
func (o *ListProviderContractsResponse) GetProviderContractsOk() ([]ProviderContract, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProviderContracts, true
}

// SetProviderContracts sets field value
func (o *ListProviderContractsResponse) SetProviderContracts(v []ProviderContract) {
	o.ProviderContracts = v
}

func (o ListProviderContractsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListProviderContractsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["providerContracts"] = o.ProviderContracts
	return toSerialize, nil
}

func (o *ListProviderContractsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"providerContracts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListProviderContractsResponse := _ListProviderContractsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListProviderContractsResponse)

	if err != nil {
		return err
	}

	*o = ListProviderContractsResponse(varListProviderContractsResponse)

	return err
}

type NullableListProviderContractsResponse struct {
	value *ListProviderContractsResponse
	isSet bool
}

func (v NullableListProviderContractsResponse) Get() *ListProviderContractsResponse {
	return v.value
}

func (v *NullableListProviderContractsResponse) Set(val *ListProviderContractsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListProviderContractsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListProviderContractsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListProviderContractsResponse(val *ListProviderContractsResponse) *NullableListProviderContractsResponse {
	return &NullableListProviderContractsResponse{value: val, isSet: true}
}

func (v NullableListProviderContractsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListProviderContractsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


