/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the ClearProviderOutputDocument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClearProviderOutputDocument{}

// ClearProviderOutputDocument struct for ClearProviderOutputDocument
type ClearProviderOutputDocument struct {
	// The nationality scanned from the document, normalized to an ISO 3166-1 alpha-2 country code.
	Nationality NullableString `json:"nationality,omitempty"`
	// The document type scanned by CLEAR.              Known values: - drivers_license - paper_passport - passport_card - id_card - visa - health_care_card - other
	DocumentType NullableString `json:"documentType,omitempty"`
	// The ISO 3166-1 alpha-2 country code of issue.
	IssuingCountry NullableString `json:"issuingCountry,omitempty"`
	// The ISO 3166 subdivision issuer of the document.
	IssuingSubdivision NullableString `json:"issuingSubdivision,omitempty"`
	// The document number scanned from the document.
	DocumentNumber NullableString `json:"documentNumber,omitempty"`
	// The document expiration date.
	DateOfExpiry NullableString `json:"dateOfExpiry,omitempty"`
	// The gender scanned from the document. CLEAR does not publish a closed set of possible values for this field.
	Gender NullableString `json:"gender,omitempty"`
	// The address scanned from the document.
	Address NullableClearProviderOutputAddress `json:"address,omitempty"`
	// The date of birth scanned from the document.
	DateOfBirth NullableString `json:"dateOfBirth,omitempty"`
	// The first name scanned from the document.
	FirstName NullableString `json:"firstName,omitempty"`
	// The last name scanned from the document.
	LastName NullableString `json:"lastName,omitempty"`
	// The middle name scanned from the document.
	MiddleName NullableString `json:"middleName,omitempty"`
	// The full name scanned from the document.
	FullName NullableString `json:"fullName,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ClearProviderOutputDocument ClearProviderOutputDocument

// NewClearProviderOutputDocument instantiates a new ClearProviderOutputDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClearProviderOutputDocument() *ClearProviderOutputDocument {
	this := ClearProviderOutputDocument{}
	return &this
}

// NewClearProviderOutputDocumentWithDefaults instantiates a new ClearProviderOutputDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClearProviderOutputDocumentWithDefaults() *ClearProviderOutputDocument {
	this := ClearProviderOutputDocument{}
	return &this
}

// GetNationality returns the Nationality field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClearProviderOutputDocument) GetNationality() string {
	if o == nil || IsNil(o.Nationality.Get()) {
		var ret string
		return ret
	}
	return *o.Nationality.Get()
}

// GetNationalityOk returns a tuple with the Nationality field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClearProviderOutputDocument) GetNationalityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nationality.Get(), o.Nationality.IsSet()
}

// HasNationality returns a boolean if a field has been set.
func (o *ClearProviderOutputDocument) HasNationality() bool {
	if o != nil && o.Nationality.IsSet() {
		return true
	}

	return false
}

// SetNationality gets a reference to the given NullableString and assigns it to the Nationality field.
func (o *ClearProviderOutputDocument) SetNationality(v string) {
	o.Nationality.Set(&v)
}
// SetNationalityNil sets the value for Nationality to be an explicit nil
func (o *ClearProviderOutputDocument) SetNationalityNil() {
	o.Nationality.Set(nil)
}

// UnsetNationality ensures that no value is present for Nationality, not even an explicit nil
func (o *ClearProviderOutputDocument) UnsetNationality() {
	o.Nationality.Unset()
}

// GetDocumentType returns the DocumentType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClearProviderOutputDocument) GetDocumentType() string {
	if o == nil || IsNil(o.DocumentType.Get()) {
		var ret string
		return ret
	}
	return *o.DocumentType.Get()
}

// GetDocumentTypeOk returns a tuple with the DocumentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClearProviderOutputDocument) GetDocumentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DocumentType.Get(), o.DocumentType.IsSet()
}

// HasDocumentType returns a boolean if a field has been set.
func (o *ClearProviderOutputDocument) HasDocumentType() bool {
	if o != nil && o.DocumentType.IsSet() {
		return true
	}

	return false
}

// SetDocumentType gets a reference to the given NullableString and assigns it to the DocumentType field.
func (o *ClearProviderOutputDocument) SetDocumentType(v string) {
	o.DocumentType.Set(&v)
}
// SetDocumentTypeNil sets the value for DocumentType to be an explicit nil
func (o *ClearProviderOutputDocument) SetDocumentTypeNil() {
	o.DocumentType.Set(nil)
}

// UnsetDocumentType ensures that no value is present for DocumentType, not even an explicit nil
func (o *ClearProviderOutputDocument) UnsetDocumentType() {
	o.DocumentType.Unset()
}

// GetIssuingCountry returns the IssuingCountry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClearProviderOutputDocument) GetIssuingCountry() string {
	if o == nil || IsNil(o.IssuingCountry.Get()) {
		var ret string
		return ret
	}
	return *o.IssuingCountry.Get()
}

// GetIssuingCountryOk returns a tuple with the IssuingCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClearProviderOutputDocument) GetIssuingCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IssuingCountry.Get(), o.IssuingCountry.IsSet()
}

// HasIssuingCountry returns a boolean if a field has been set.
func (o *ClearProviderOutputDocument) HasIssuingCountry() bool {
	if o != nil && o.IssuingCountry.IsSet() {
		return true
	}

	return false
}

// SetIssuingCountry gets a reference to the given NullableString and assigns it to the IssuingCountry field.
func (o *ClearProviderOutputDocument) SetIssuingCountry(v string) {
	o.IssuingCountry.Set(&v)
}
// SetIssuingCountryNil sets the value for IssuingCountry to be an explicit nil
func (o *ClearProviderOutputDocument) SetIssuingCountryNil() {
	o.IssuingCountry.Set(nil)
}

// UnsetIssuingCountry ensures that no value is present for IssuingCountry, not even an explicit nil
func (o *ClearProviderOutputDocument) UnsetIssuingCountry() {
	o.IssuingCountry.Unset()
}

// GetIssuingSubdivision returns the IssuingSubdivision field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClearProviderOutputDocument) GetIssuingSubdivision() string {
	if o == nil || IsNil(o.IssuingSubdivision.Get()) {
		var ret string
		return ret
	}
	return *o.IssuingSubdivision.Get()
}

// GetIssuingSubdivisionOk returns a tuple with the IssuingSubdivision field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClearProviderOutputDocument) GetIssuingSubdivisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IssuingSubdivision.Get(), o.IssuingSubdivision.IsSet()
}

// HasIssuingSubdivision returns a boolean if a field has been set.
func (o *ClearProviderOutputDocument) HasIssuingSubdivision() bool {
	if o != nil && o.IssuingSubdivision.IsSet() {
		return true
	}

	return false
}

// SetIssuingSubdivision gets a reference to the given NullableString and assigns it to the IssuingSubdivision field.
func (o *ClearProviderOutputDocument) SetIssuingSubdivision(v string) {
	o.IssuingSubdivision.Set(&v)
}
// SetIssuingSubdivisionNil sets the value for IssuingSubdivision to be an explicit nil
func (o *ClearProviderOutputDocument) SetIssuingSubdivisionNil() {
	o.IssuingSubdivision.Set(nil)
}

// UnsetIssuingSubdivision ensures that no value is present for IssuingSubdivision, not even an explicit nil
func (o *ClearProviderOutputDocument) UnsetIssuingSubdivision() {
	o.IssuingSubdivision.Unset()
}

// GetDocumentNumber returns the DocumentNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClearProviderOutputDocument) GetDocumentNumber() string {
	if o == nil || IsNil(o.DocumentNumber.Get()) {
		var ret string
		return ret
	}
	return *o.DocumentNumber.Get()
}

// GetDocumentNumberOk returns a tuple with the DocumentNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClearProviderOutputDocument) GetDocumentNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DocumentNumber.Get(), o.DocumentNumber.IsSet()
}

// HasDocumentNumber returns a boolean if a field has been set.
func (o *ClearProviderOutputDocument) HasDocumentNumber() bool {
	if o != nil && o.DocumentNumber.IsSet() {
		return true
	}

	return false
}

// SetDocumentNumber gets a reference to the given NullableString and assigns it to the DocumentNumber field.
func (o *ClearProviderOutputDocument) SetDocumentNumber(v string) {
	o.DocumentNumber.Set(&v)
}
// SetDocumentNumberNil sets the value for DocumentNumber to be an explicit nil
func (o *ClearProviderOutputDocument) SetDocumentNumberNil() {
	o.DocumentNumber.Set(nil)
}

// UnsetDocumentNumber ensures that no value is present for DocumentNumber, not even an explicit nil
func (o *ClearProviderOutputDocument) UnsetDocumentNumber() {
	o.DocumentNumber.Unset()
}

// GetDateOfExpiry returns the DateOfExpiry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClearProviderOutputDocument) GetDateOfExpiry() string {
	if o == nil || IsNil(o.DateOfExpiry.Get()) {
		var ret string
		return ret
	}
	return *o.DateOfExpiry.Get()
}

// GetDateOfExpiryOk returns a tuple with the DateOfExpiry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClearProviderOutputDocument) GetDateOfExpiryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfExpiry.Get(), o.DateOfExpiry.IsSet()
}

// HasDateOfExpiry returns a boolean if a field has been set.
func (o *ClearProviderOutputDocument) HasDateOfExpiry() bool {
	if o != nil && o.DateOfExpiry.IsSet() {
		return true
	}

	return false
}

// SetDateOfExpiry gets a reference to the given NullableString and assigns it to the DateOfExpiry field.
func (o *ClearProviderOutputDocument) SetDateOfExpiry(v string) {
	o.DateOfExpiry.Set(&v)
}
// SetDateOfExpiryNil sets the value for DateOfExpiry to be an explicit nil
func (o *ClearProviderOutputDocument) SetDateOfExpiryNil() {
	o.DateOfExpiry.Set(nil)
}

// UnsetDateOfExpiry ensures that no value is present for DateOfExpiry, not even an explicit nil
func (o *ClearProviderOutputDocument) UnsetDateOfExpiry() {
	o.DateOfExpiry.Unset()
}

// GetGender returns the Gender field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClearProviderOutputDocument) GetGender() string {
	if o == nil || IsNil(o.Gender.Get()) {
		var ret string
		return ret
	}
	return *o.Gender.Get()
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClearProviderOutputDocument) GetGenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gender.Get(), o.Gender.IsSet()
}

// HasGender returns a boolean if a field has been set.
func (o *ClearProviderOutputDocument) HasGender() bool {
	if o != nil && o.Gender.IsSet() {
		return true
	}

	return false
}

// SetGender gets a reference to the given NullableString and assigns it to the Gender field.
func (o *ClearProviderOutputDocument) SetGender(v string) {
	o.Gender.Set(&v)
}
// SetGenderNil sets the value for Gender to be an explicit nil
func (o *ClearProviderOutputDocument) SetGenderNil() {
	o.Gender.Set(nil)
}

// UnsetGender ensures that no value is present for Gender, not even an explicit nil
func (o *ClearProviderOutputDocument) UnsetGender() {
	o.Gender.Unset()
}

// GetAddress returns the Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClearProviderOutputDocument) GetAddress() ClearProviderOutputAddress {
	if o == nil || IsNil(o.Address.Get()) {
		var ret ClearProviderOutputAddress
		return ret
	}
	return *o.Address.Get()
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClearProviderOutputDocument) GetAddressOk() (*ClearProviderOutputAddress, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address.Get(), o.Address.IsSet()
}

// HasAddress returns a boolean if a field has been set.
func (o *ClearProviderOutputDocument) HasAddress() bool {
	if o != nil && o.Address.IsSet() {
		return true
	}

	return false
}

// SetAddress gets a reference to the given NullableClearProviderOutputAddress and assigns it to the Address field.
func (o *ClearProviderOutputDocument) SetAddress(v ClearProviderOutputAddress) {
	o.Address.Set(&v)
}
// SetAddressNil sets the value for Address to be an explicit nil
func (o *ClearProviderOutputDocument) SetAddressNil() {
	o.Address.Set(nil)
}

// UnsetAddress ensures that no value is present for Address, not even an explicit nil
func (o *ClearProviderOutputDocument) UnsetAddress() {
	o.Address.Unset()
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClearProviderOutputDocument) GetDateOfBirth() string {
	if o == nil || IsNil(o.DateOfBirth.Get()) {
		var ret string
		return ret
	}
	return *o.DateOfBirth.Get()
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClearProviderOutputDocument) GetDateOfBirthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfBirth.Get(), o.DateOfBirth.IsSet()
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *ClearProviderOutputDocument) HasDateOfBirth() bool {
	if o != nil && o.DateOfBirth.IsSet() {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given NullableString and assigns it to the DateOfBirth field.
func (o *ClearProviderOutputDocument) SetDateOfBirth(v string) {
	o.DateOfBirth.Set(&v)
}
// SetDateOfBirthNil sets the value for DateOfBirth to be an explicit nil
func (o *ClearProviderOutputDocument) SetDateOfBirthNil() {
	o.DateOfBirth.Set(nil)
}

// UnsetDateOfBirth ensures that no value is present for DateOfBirth, not even an explicit nil
func (o *ClearProviderOutputDocument) UnsetDateOfBirth() {
	o.DateOfBirth.Unset()
}

// GetFirstName returns the FirstName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClearProviderOutputDocument) GetFirstName() string {
	if o == nil || IsNil(o.FirstName.Get()) {
		var ret string
		return ret
	}
	return *o.FirstName.Get()
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClearProviderOutputDocument) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirstName.Get(), o.FirstName.IsSet()
}

// HasFirstName returns a boolean if a field has been set.
func (o *ClearProviderOutputDocument) HasFirstName() bool {
	if o != nil && o.FirstName.IsSet() {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given NullableString and assigns it to the FirstName field.
func (o *ClearProviderOutputDocument) SetFirstName(v string) {
	o.FirstName.Set(&v)
}
// SetFirstNameNil sets the value for FirstName to be an explicit nil
func (o *ClearProviderOutputDocument) SetFirstNameNil() {
	o.FirstName.Set(nil)
}

// UnsetFirstName ensures that no value is present for FirstName, not even an explicit nil
func (o *ClearProviderOutputDocument) UnsetFirstName() {
	o.FirstName.Unset()
}

// GetLastName returns the LastName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClearProviderOutputDocument) GetLastName() string {
	if o == nil || IsNil(o.LastName.Get()) {
		var ret string
		return ret
	}
	return *o.LastName.Get()
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClearProviderOutputDocument) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastName.Get(), o.LastName.IsSet()
}

// HasLastName returns a boolean if a field has been set.
func (o *ClearProviderOutputDocument) HasLastName() bool {
	if o != nil && o.LastName.IsSet() {
		return true
	}

	return false
}

// SetLastName gets a reference to the given NullableString and assigns it to the LastName field.
func (o *ClearProviderOutputDocument) SetLastName(v string) {
	o.LastName.Set(&v)
}
// SetLastNameNil sets the value for LastName to be an explicit nil
func (o *ClearProviderOutputDocument) SetLastNameNil() {
	o.LastName.Set(nil)
}

// UnsetLastName ensures that no value is present for LastName, not even an explicit nil
func (o *ClearProviderOutputDocument) UnsetLastName() {
	o.LastName.Unset()
}

// GetMiddleName returns the MiddleName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClearProviderOutputDocument) GetMiddleName() string {
	if o == nil || IsNil(o.MiddleName.Get()) {
		var ret string
		return ret
	}
	return *o.MiddleName.Get()
}

// GetMiddleNameOk returns a tuple with the MiddleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClearProviderOutputDocument) GetMiddleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MiddleName.Get(), o.MiddleName.IsSet()
}

// HasMiddleName returns a boolean if a field has been set.
func (o *ClearProviderOutputDocument) HasMiddleName() bool {
	if o != nil && o.MiddleName.IsSet() {
		return true
	}

	return false
}

// SetMiddleName gets a reference to the given NullableString and assigns it to the MiddleName field.
func (o *ClearProviderOutputDocument) SetMiddleName(v string) {
	o.MiddleName.Set(&v)
}
// SetMiddleNameNil sets the value for MiddleName to be an explicit nil
func (o *ClearProviderOutputDocument) SetMiddleNameNil() {
	o.MiddleName.Set(nil)
}

// UnsetMiddleName ensures that no value is present for MiddleName, not even an explicit nil
func (o *ClearProviderOutputDocument) UnsetMiddleName() {
	o.MiddleName.Unset()
}

// GetFullName returns the FullName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClearProviderOutputDocument) GetFullName() string {
	if o == nil || IsNil(o.FullName.Get()) {
		var ret string
		return ret
	}
	return *o.FullName.Get()
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClearProviderOutputDocument) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FullName.Get(), o.FullName.IsSet()
}

// HasFullName returns a boolean if a field has been set.
func (o *ClearProviderOutputDocument) HasFullName() bool {
	if o != nil && o.FullName.IsSet() {
		return true
	}

	return false
}

// SetFullName gets a reference to the given NullableString and assigns it to the FullName field.
func (o *ClearProviderOutputDocument) SetFullName(v string) {
	o.FullName.Set(&v)
}
// SetFullNameNil sets the value for FullName to be an explicit nil
func (o *ClearProviderOutputDocument) SetFullNameNil() {
	o.FullName.Set(nil)
}

// UnsetFullName ensures that no value is present for FullName, not even an explicit nil
func (o *ClearProviderOutputDocument) UnsetFullName() {
	o.FullName.Unset()
}

func (o ClearProviderOutputDocument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClearProviderOutputDocument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Nationality.IsSet() {
		toSerialize["nationality"] = o.Nationality.Get()
	}
	if o.DocumentType.IsSet() {
		toSerialize["documentType"] = o.DocumentType.Get()
	}
	if o.IssuingCountry.IsSet() {
		toSerialize["issuingCountry"] = o.IssuingCountry.Get()
	}
	if o.IssuingSubdivision.IsSet() {
		toSerialize["issuingSubdivision"] = o.IssuingSubdivision.Get()
	}
	if o.DocumentNumber.IsSet() {
		toSerialize["documentNumber"] = o.DocumentNumber.Get()
	}
	if o.DateOfExpiry.IsSet() {
		toSerialize["dateOfExpiry"] = o.DateOfExpiry.Get()
	}
	if o.Gender.IsSet() {
		toSerialize["gender"] = o.Gender.Get()
	}
	if o.Address.IsSet() {
		toSerialize["address"] = o.Address.Get()
	}
	if o.DateOfBirth.IsSet() {
		toSerialize["dateOfBirth"] = o.DateOfBirth.Get()
	}
	if o.FirstName.IsSet() {
		toSerialize["firstName"] = o.FirstName.Get()
	}
	if o.LastName.IsSet() {
		toSerialize["lastName"] = o.LastName.Get()
	}
	if o.MiddleName.IsSet() {
		toSerialize["middleName"] = o.MiddleName.Get()
	}
	if o.FullName.IsSet() {
		toSerialize["fullName"] = o.FullName.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClearProviderOutputDocument) UnmarshalJSON(data []byte) (err error) {
	varClearProviderOutputDocument := _ClearProviderOutputDocument{}

	err = json.Unmarshal(data, &varClearProviderOutputDocument)

	if err != nil {
		return err
	}

	*o = ClearProviderOutputDocument(varClearProviderOutputDocument)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "nationality")
		delete(additionalProperties, "documentType")
		delete(additionalProperties, "issuingCountry")
		delete(additionalProperties, "issuingSubdivision")
		delete(additionalProperties, "documentNumber")
		delete(additionalProperties, "dateOfExpiry")
		delete(additionalProperties, "gender")
		delete(additionalProperties, "address")
		delete(additionalProperties, "dateOfBirth")
		delete(additionalProperties, "firstName")
		delete(additionalProperties, "lastName")
		delete(additionalProperties, "middleName")
		delete(additionalProperties, "fullName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClearProviderOutputDocument struct {
	value *ClearProviderOutputDocument
	isSet bool
}

func (v NullableClearProviderOutputDocument) Get() *ClearProviderOutputDocument {
	return v.value
}

func (v *NullableClearProviderOutputDocument) Set(val *ClearProviderOutputDocument) {
	v.value = val
	v.isSet = true
}

func (v NullableClearProviderOutputDocument) IsSet() bool {
	return v.isSet
}

func (v *NullableClearProviderOutputDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClearProviderOutputDocument(val *ClearProviderOutputDocument) *NullableClearProviderOutputDocument {
	return &NullableClearProviderOutputDocument{value: val, isSet: true}
}

func (v NullableClearProviderOutputDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClearProviderOutputDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


