/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the NigeriaNinMatch2PhoneNumberField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NigeriaNinMatch2PhoneNumberField{}

// NigeriaNinMatch2PhoneNumberField struct for NigeriaNinMatch2PhoneNumberField
type NigeriaNinMatch2PhoneNumberField struct {
	// The phone number as submitted for this check.              Format: - International E.164
	InputValue NullableString `json:"inputValue,omitempty"`
	// The outcome of comparing the submitted phone number to the issuer record.              Possible values: - Exact Match - No Match - Not Provided - Not Returned
	Outcome NullableString `json:"outcome,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NigeriaNinMatch2PhoneNumberField NigeriaNinMatch2PhoneNumberField

// NewNigeriaNinMatch2PhoneNumberField instantiates a new NigeriaNinMatch2PhoneNumberField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNigeriaNinMatch2PhoneNumberField() *NigeriaNinMatch2PhoneNumberField {
	this := NigeriaNinMatch2PhoneNumberField{}
	return &this
}

// NewNigeriaNinMatch2PhoneNumberFieldWithDefaults instantiates a new NigeriaNinMatch2PhoneNumberField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNigeriaNinMatch2PhoneNumberFieldWithDefaults() *NigeriaNinMatch2PhoneNumberField {
	this := NigeriaNinMatch2PhoneNumberField{}
	return &this
}

// GetInputValue returns the InputValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NigeriaNinMatch2PhoneNumberField) GetInputValue() string {
	if o == nil || IsNil(o.InputValue.Get()) {
		var ret string
		return ret
	}
	return *o.InputValue.Get()
}

// GetInputValueOk returns a tuple with the InputValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NigeriaNinMatch2PhoneNumberField) GetInputValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InputValue.Get(), o.InputValue.IsSet()
}

// HasInputValue returns a boolean if a field has been set.
func (o *NigeriaNinMatch2PhoneNumberField) HasInputValue() bool {
	if o != nil && o.InputValue.IsSet() {
		return true
	}

	return false
}

// SetInputValue gets a reference to the given NullableString and assigns it to the InputValue field.
func (o *NigeriaNinMatch2PhoneNumberField) SetInputValue(v string) {
	o.InputValue.Set(&v)
}
// SetInputValueNil sets the value for InputValue to be an explicit nil
func (o *NigeriaNinMatch2PhoneNumberField) SetInputValueNil() {
	o.InputValue.Set(nil)
}

// UnsetInputValue ensures that no value is present for InputValue, not even an explicit nil
func (o *NigeriaNinMatch2PhoneNumberField) UnsetInputValue() {
	o.InputValue.Unset()
}

// GetOutcome returns the Outcome field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NigeriaNinMatch2PhoneNumberField) GetOutcome() string {
	if o == nil || IsNil(o.Outcome.Get()) {
		var ret string
		return ret
	}
	return *o.Outcome.Get()
}

// GetOutcomeOk returns a tuple with the Outcome field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NigeriaNinMatch2PhoneNumberField) GetOutcomeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Outcome.Get(), o.Outcome.IsSet()
}

// HasOutcome returns a boolean if a field has been set.
func (o *NigeriaNinMatch2PhoneNumberField) HasOutcome() bool {
	if o != nil && o.Outcome.IsSet() {
		return true
	}

	return false
}

// SetOutcome gets a reference to the given NullableString and assigns it to the Outcome field.
func (o *NigeriaNinMatch2PhoneNumberField) SetOutcome(v string) {
	o.Outcome.Set(&v)
}
// SetOutcomeNil sets the value for Outcome to be an explicit nil
func (o *NigeriaNinMatch2PhoneNumberField) SetOutcomeNil() {
	o.Outcome.Set(nil)
}

// UnsetOutcome ensures that no value is present for Outcome, not even an explicit nil
func (o *NigeriaNinMatch2PhoneNumberField) UnsetOutcome() {
	o.Outcome.Unset()
}

func (o NigeriaNinMatch2PhoneNumberField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NigeriaNinMatch2PhoneNumberField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.InputValue.IsSet() {
		toSerialize["inputValue"] = o.InputValue.Get()
	}
	if o.Outcome.IsSet() {
		toSerialize["outcome"] = o.Outcome.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NigeriaNinMatch2PhoneNumberField) UnmarshalJSON(data []byte) (err error) {
	varNigeriaNinMatch2PhoneNumberField := _NigeriaNinMatch2PhoneNumberField{}

	err = json.Unmarshal(data, &varNigeriaNinMatch2PhoneNumberField)

	if err != nil {
		return err
	}

	*o = NigeriaNinMatch2PhoneNumberField(varNigeriaNinMatch2PhoneNumberField)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "inputValue")
		delete(additionalProperties, "outcome")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNigeriaNinMatch2PhoneNumberField struct {
	value *NigeriaNinMatch2PhoneNumberField
	isSet bool
}

func (v NullableNigeriaNinMatch2PhoneNumberField) Get() *NigeriaNinMatch2PhoneNumberField {
	return v.value
}

func (v *NullableNigeriaNinMatch2PhoneNumberField) Set(val *NigeriaNinMatch2PhoneNumberField) {
	v.value = val
	v.isSet = true
}

func (v NullableNigeriaNinMatch2PhoneNumberField) IsSet() bool {
	return v.isSet
}

func (v *NullableNigeriaNinMatch2PhoneNumberField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNigeriaNinMatch2PhoneNumberField(val *NigeriaNinMatch2PhoneNumberField) *NullableNigeriaNinMatch2PhoneNumberField {
	return &NullableNigeriaNinMatch2PhoneNumberField{value: val, isSet: true}
}

func (v NullableNigeriaNinMatch2PhoneNumberField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNigeriaNinMatch2PhoneNumberField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


