/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the BrazilBiometricVerificationOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BrazilBiometricVerificationOutput{}

// BrazilBiometricVerificationOutput struct for BrazilBiometricVerificationOutput
type BrazilBiometricVerificationOutput struct {
	// The probability of the selfie verification being successful.              Possible values: - VeryLow - Low - High - VeryHigh
	SelfieVerificationProbability NullableString `json:"selfieVerificationProbability,omitempty"`
	// The outcome of the selfie verification.              Possible values: - Real - Fake - BadQuality
	SelfieLivenessOutcome NullableString `json:"selfieLivenessOutcome,omitempty"`
	// Whether the government database had biometrics available for the individual.              Also false in some cases biometrics are available but not sufficient for selfie verification.
	DatabaseSelfieAvailable NullableBool `json:"databaseSelfieAvailable,omitempty"`
	// Similarity match score of selfie verification.              Ranges from 0.0 to 1.0.
	SelfieSimilarityPercentage NullableFloat64 `json:"selfieSimilarityPercentage,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BrazilBiometricVerificationOutput BrazilBiometricVerificationOutput

// NewBrazilBiometricVerificationOutput instantiates a new BrazilBiometricVerificationOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrazilBiometricVerificationOutput() *BrazilBiometricVerificationOutput {
	this := BrazilBiometricVerificationOutput{}
	return &this
}

// NewBrazilBiometricVerificationOutputWithDefaults instantiates a new BrazilBiometricVerificationOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrazilBiometricVerificationOutputWithDefaults() *BrazilBiometricVerificationOutput {
	this := BrazilBiometricVerificationOutput{}
	return &this
}

// GetSelfieVerificationProbability returns the SelfieVerificationProbability field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrazilBiometricVerificationOutput) GetSelfieVerificationProbability() string {
	if o == nil || IsNil(o.SelfieVerificationProbability.Get()) {
		var ret string
		return ret
	}
	return *o.SelfieVerificationProbability.Get()
}

// GetSelfieVerificationProbabilityOk returns a tuple with the SelfieVerificationProbability field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrazilBiometricVerificationOutput) GetSelfieVerificationProbabilityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SelfieVerificationProbability.Get(), o.SelfieVerificationProbability.IsSet()
}

// HasSelfieVerificationProbability returns a boolean if a field has been set.
func (o *BrazilBiometricVerificationOutput) HasSelfieVerificationProbability() bool {
	if o != nil && o.SelfieVerificationProbability.IsSet() {
		return true
	}

	return false
}

// SetSelfieVerificationProbability gets a reference to the given NullableString and assigns it to the SelfieVerificationProbability field.
func (o *BrazilBiometricVerificationOutput) SetSelfieVerificationProbability(v string) {
	o.SelfieVerificationProbability.Set(&v)
}
// SetSelfieVerificationProbabilityNil sets the value for SelfieVerificationProbability to be an explicit nil
func (o *BrazilBiometricVerificationOutput) SetSelfieVerificationProbabilityNil() {
	o.SelfieVerificationProbability.Set(nil)
}

// UnsetSelfieVerificationProbability ensures that no value is present for SelfieVerificationProbability, not even an explicit nil
func (o *BrazilBiometricVerificationOutput) UnsetSelfieVerificationProbability() {
	o.SelfieVerificationProbability.Unset()
}

// GetSelfieLivenessOutcome returns the SelfieLivenessOutcome field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrazilBiometricVerificationOutput) GetSelfieLivenessOutcome() string {
	if o == nil || IsNil(o.SelfieLivenessOutcome.Get()) {
		var ret string
		return ret
	}
	return *o.SelfieLivenessOutcome.Get()
}

// GetSelfieLivenessOutcomeOk returns a tuple with the SelfieLivenessOutcome field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrazilBiometricVerificationOutput) GetSelfieLivenessOutcomeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SelfieLivenessOutcome.Get(), o.SelfieLivenessOutcome.IsSet()
}

// HasSelfieLivenessOutcome returns a boolean if a field has been set.
func (o *BrazilBiometricVerificationOutput) HasSelfieLivenessOutcome() bool {
	if o != nil && o.SelfieLivenessOutcome.IsSet() {
		return true
	}

	return false
}

// SetSelfieLivenessOutcome gets a reference to the given NullableString and assigns it to the SelfieLivenessOutcome field.
func (o *BrazilBiometricVerificationOutput) SetSelfieLivenessOutcome(v string) {
	o.SelfieLivenessOutcome.Set(&v)
}
// SetSelfieLivenessOutcomeNil sets the value for SelfieLivenessOutcome to be an explicit nil
func (o *BrazilBiometricVerificationOutput) SetSelfieLivenessOutcomeNil() {
	o.SelfieLivenessOutcome.Set(nil)
}

// UnsetSelfieLivenessOutcome ensures that no value is present for SelfieLivenessOutcome, not even an explicit nil
func (o *BrazilBiometricVerificationOutput) UnsetSelfieLivenessOutcome() {
	o.SelfieLivenessOutcome.Unset()
}

// GetDatabaseSelfieAvailable returns the DatabaseSelfieAvailable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrazilBiometricVerificationOutput) GetDatabaseSelfieAvailable() bool {
	if o == nil || IsNil(o.DatabaseSelfieAvailable.Get()) {
		var ret bool
		return ret
	}
	return *o.DatabaseSelfieAvailable.Get()
}

// GetDatabaseSelfieAvailableOk returns a tuple with the DatabaseSelfieAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrazilBiometricVerificationOutput) GetDatabaseSelfieAvailableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DatabaseSelfieAvailable.Get(), o.DatabaseSelfieAvailable.IsSet()
}

// HasDatabaseSelfieAvailable returns a boolean if a field has been set.
func (o *BrazilBiometricVerificationOutput) HasDatabaseSelfieAvailable() bool {
	if o != nil && o.DatabaseSelfieAvailable.IsSet() {
		return true
	}

	return false
}

// SetDatabaseSelfieAvailable gets a reference to the given NullableBool and assigns it to the DatabaseSelfieAvailable field.
func (o *BrazilBiometricVerificationOutput) SetDatabaseSelfieAvailable(v bool) {
	o.DatabaseSelfieAvailable.Set(&v)
}
// SetDatabaseSelfieAvailableNil sets the value for DatabaseSelfieAvailable to be an explicit nil
func (o *BrazilBiometricVerificationOutput) SetDatabaseSelfieAvailableNil() {
	o.DatabaseSelfieAvailable.Set(nil)
}

// UnsetDatabaseSelfieAvailable ensures that no value is present for DatabaseSelfieAvailable, not even an explicit nil
func (o *BrazilBiometricVerificationOutput) UnsetDatabaseSelfieAvailable() {
	o.DatabaseSelfieAvailable.Unset()
}

// GetSelfieSimilarityPercentage returns the SelfieSimilarityPercentage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrazilBiometricVerificationOutput) GetSelfieSimilarityPercentage() float64 {
	if o == nil || IsNil(o.SelfieSimilarityPercentage.Get()) {
		var ret float64
		return ret
	}
	return *o.SelfieSimilarityPercentage.Get()
}

// GetSelfieSimilarityPercentageOk returns a tuple with the SelfieSimilarityPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrazilBiometricVerificationOutput) GetSelfieSimilarityPercentageOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.SelfieSimilarityPercentage.Get(), o.SelfieSimilarityPercentage.IsSet()
}

// HasSelfieSimilarityPercentage returns a boolean if a field has been set.
func (o *BrazilBiometricVerificationOutput) HasSelfieSimilarityPercentage() bool {
	if o != nil && o.SelfieSimilarityPercentage.IsSet() {
		return true
	}

	return false
}

// SetSelfieSimilarityPercentage gets a reference to the given NullableFloat64 and assigns it to the SelfieSimilarityPercentage field.
func (o *BrazilBiometricVerificationOutput) SetSelfieSimilarityPercentage(v float64) {
	o.SelfieSimilarityPercentage.Set(&v)
}
// SetSelfieSimilarityPercentageNil sets the value for SelfieSimilarityPercentage to be an explicit nil
func (o *BrazilBiometricVerificationOutput) SetSelfieSimilarityPercentageNil() {
	o.SelfieSimilarityPercentage.Set(nil)
}

// UnsetSelfieSimilarityPercentage ensures that no value is present for SelfieSimilarityPercentage, not even an explicit nil
func (o *BrazilBiometricVerificationOutput) UnsetSelfieSimilarityPercentage() {
	o.SelfieSimilarityPercentage.Unset()
}

func (o BrazilBiometricVerificationOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BrazilBiometricVerificationOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.SelfieVerificationProbability.IsSet() {
		toSerialize["selfieVerificationProbability"] = o.SelfieVerificationProbability.Get()
	}
	if o.SelfieLivenessOutcome.IsSet() {
		toSerialize["selfieLivenessOutcome"] = o.SelfieLivenessOutcome.Get()
	}
	if o.DatabaseSelfieAvailable.IsSet() {
		toSerialize["databaseSelfieAvailable"] = o.DatabaseSelfieAvailable.Get()
	}
	if o.SelfieSimilarityPercentage.IsSet() {
		toSerialize["selfieSimilarityPercentage"] = o.SelfieSimilarityPercentage.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BrazilBiometricVerificationOutput) UnmarshalJSON(data []byte) (err error) {
	varBrazilBiometricVerificationOutput := _BrazilBiometricVerificationOutput{}

	err = json.Unmarshal(data, &varBrazilBiometricVerificationOutput)

	if err != nil {
		return err
	}

	*o = BrazilBiometricVerificationOutput(varBrazilBiometricVerificationOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "selfieVerificationProbability")
		delete(additionalProperties, "selfieLivenessOutcome")
		delete(additionalProperties, "databaseSelfieAvailable")
		delete(additionalProperties, "selfieSimilarityPercentage")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBrazilBiometricVerificationOutput struct {
	value *BrazilBiometricVerificationOutput
	isSet bool
}

func (v NullableBrazilBiometricVerificationOutput) Get() *BrazilBiometricVerificationOutput {
	return v.value
}

func (v *NullableBrazilBiometricVerificationOutput) Set(val *BrazilBiometricVerificationOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableBrazilBiometricVerificationOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableBrazilBiometricVerificationOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrazilBiometricVerificationOutput(val *BrazilBiometricVerificationOutput) *NullableBrazilBiometricVerificationOutput {
	return &NullableBrazilBiometricVerificationOutput{value: val, isSet: true}
}

func (v NullableBrazilBiometricVerificationOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrazilBiometricVerificationOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


