/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the IndonesiaDukcapilMatchNationalIdNumberField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndonesiaDukcapilMatchNationalIdNumberField{}

// IndonesiaDukcapilMatchNationalIdNumberField struct for IndonesiaDukcapilMatchNationalIdNumberField
type IndonesiaDukcapilMatchNationalIdNumberField struct {
	// The NIK (Nomor Induk Kependudukan) submitted for this check.              NIK is Indonesia's unique population identity number, issued by Indonesia's population administration and civil registration authority (Dukcapil) under the Ministry of Home Affairs.              Format: - 16 numeric digits. - Digits 1-2 are the province code. - Digits 3-4 are the regency or city code within that province. - Digits 5-6 are the district code within that regency or city. - Digits 7-12 encode date of birth as DDMMYY. For female NIK holders, the day is increased by 40. - Digits 13-16 are an issuance serial number.
	InputValue NullableString `json:"inputValue,omitempty"`
	// The provider assessment result for the submitted NIK.              Local integration code expects the provider to return 0 or 1 for this assessment.
	Outcome NullableFloat64 `json:"outcome,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IndonesiaDukcapilMatchNationalIdNumberField IndonesiaDukcapilMatchNationalIdNumberField

// NewIndonesiaDukcapilMatchNationalIdNumberField instantiates a new IndonesiaDukcapilMatchNationalIdNumberField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndonesiaDukcapilMatchNationalIdNumberField() *IndonesiaDukcapilMatchNationalIdNumberField {
	this := IndonesiaDukcapilMatchNationalIdNumberField{}
	return &this
}

// NewIndonesiaDukcapilMatchNationalIdNumberFieldWithDefaults instantiates a new IndonesiaDukcapilMatchNationalIdNumberField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndonesiaDukcapilMatchNationalIdNumberFieldWithDefaults() *IndonesiaDukcapilMatchNationalIdNumberField {
	this := IndonesiaDukcapilMatchNationalIdNumberField{}
	return &this
}

// GetInputValue returns the InputValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndonesiaDukcapilMatchNationalIdNumberField) GetInputValue() string {
	if o == nil || IsNil(o.InputValue.Get()) {
		var ret string
		return ret
	}
	return *o.InputValue.Get()
}

// GetInputValueOk returns a tuple with the InputValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndonesiaDukcapilMatchNationalIdNumberField) GetInputValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InputValue.Get(), o.InputValue.IsSet()
}

// HasInputValue returns a boolean if a field has been set.
func (o *IndonesiaDukcapilMatchNationalIdNumberField) HasInputValue() bool {
	if o != nil && o.InputValue.IsSet() {
		return true
	}

	return false
}

// SetInputValue gets a reference to the given NullableString and assigns it to the InputValue field.
func (o *IndonesiaDukcapilMatchNationalIdNumberField) SetInputValue(v string) {
	o.InputValue.Set(&v)
}
// SetInputValueNil sets the value for InputValue to be an explicit nil
func (o *IndonesiaDukcapilMatchNationalIdNumberField) SetInputValueNil() {
	o.InputValue.Set(nil)
}

// UnsetInputValue ensures that no value is present for InputValue, not even an explicit nil
func (o *IndonesiaDukcapilMatchNationalIdNumberField) UnsetInputValue() {
	o.InputValue.Unset()
}

// GetOutcome returns the Outcome field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndonesiaDukcapilMatchNationalIdNumberField) GetOutcome() float64 {
	if o == nil || IsNil(o.Outcome.Get()) {
		var ret float64
		return ret
	}
	return *o.Outcome.Get()
}

// GetOutcomeOk returns a tuple with the Outcome field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndonesiaDukcapilMatchNationalIdNumberField) GetOutcomeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Outcome.Get(), o.Outcome.IsSet()
}

// HasOutcome returns a boolean if a field has been set.
func (o *IndonesiaDukcapilMatchNationalIdNumberField) HasOutcome() bool {
	if o != nil && o.Outcome.IsSet() {
		return true
	}

	return false
}

// SetOutcome gets a reference to the given NullableFloat64 and assigns it to the Outcome field.
func (o *IndonesiaDukcapilMatchNationalIdNumberField) SetOutcome(v float64) {
	o.Outcome.Set(&v)
}
// SetOutcomeNil sets the value for Outcome to be an explicit nil
func (o *IndonesiaDukcapilMatchNationalIdNumberField) SetOutcomeNil() {
	o.Outcome.Set(nil)
}

// UnsetOutcome ensures that no value is present for Outcome, not even an explicit nil
func (o *IndonesiaDukcapilMatchNationalIdNumberField) UnsetOutcome() {
	o.Outcome.Unset()
}

func (o IndonesiaDukcapilMatchNationalIdNumberField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndonesiaDukcapilMatchNationalIdNumberField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.InputValue.IsSet() {
		toSerialize["inputValue"] = o.InputValue.Get()
	}
	if o.Outcome.IsSet() {
		toSerialize["outcome"] = o.Outcome.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IndonesiaDukcapilMatchNationalIdNumberField) UnmarshalJSON(data []byte) (err error) {
	varIndonesiaDukcapilMatchNationalIdNumberField := _IndonesiaDukcapilMatchNationalIdNumberField{}

	err = json.Unmarshal(data, &varIndonesiaDukcapilMatchNationalIdNumberField)

	if err != nil {
		return err
	}

	*o = IndonesiaDukcapilMatchNationalIdNumberField(varIndonesiaDukcapilMatchNationalIdNumberField)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "inputValue")
		delete(additionalProperties, "outcome")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIndonesiaDukcapilMatchNationalIdNumberField struct {
	value *IndonesiaDukcapilMatchNationalIdNumberField
	isSet bool
}

func (v NullableIndonesiaDukcapilMatchNationalIdNumberField) Get() *IndonesiaDukcapilMatchNationalIdNumberField {
	return v.value
}

func (v *NullableIndonesiaDukcapilMatchNationalIdNumberField) Set(val *IndonesiaDukcapilMatchNationalIdNumberField) {
	v.value = val
	v.isSet = true
}

func (v NullableIndonesiaDukcapilMatchNationalIdNumberField) IsSet() bool {
	return v.isSet
}

func (v *NullableIndonesiaDukcapilMatchNationalIdNumberField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndonesiaDukcapilMatchNationalIdNumberField(val *IndonesiaDukcapilMatchNationalIdNumberField) *NullableIndonesiaDukcapilMatchNationalIdNumberField {
	return &NullableIndonesiaDukcapilMatchNationalIdNumberField{value: val, isSet: true}
}

func (v NullableIndonesiaDukcapilMatchNationalIdNumberField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndonesiaDukcapilMatchNationalIdNumberField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


