/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
	"fmt"
)

// checks if the AppleWalletProviderOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppleWalletProviderOutput{}

// AppleWalletProviderOutput Exposed properties for the `apple-wallet` Provider which do not directly map to the normalized IdentityData model.
type AppleWalletProviderOutput struct {
	// The raw output of the mDL exchange performed through Apple Wallet.
	RawMdlOutput MdlOutput `json:"rawMdlOutput"`
	AdditionalProperties map[string]interface{}
}

type _AppleWalletProviderOutput AppleWalletProviderOutput

// NewAppleWalletProviderOutput instantiates a new AppleWalletProviderOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppleWalletProviderOutput(rawMdlOutput MdlOutput) *AppleWalletProviderOutput {
	this := AppleWalletProviderOutput{}
	this.RawMdlOutput = rawMdlOutput
	return &this
}

// NewAppleWalletProviderOutputWithDefaults instantiates a new AppleWalletProviderOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppleWalletProviderOutputWithDefaults() *AppleWalletProviderOutput {
	this := AppleWalletProviderOutput{}
	return &this
}

// GetRawMdlOutput returns the RawMdlOutput field value
func (o *AppleWalletProviderOutput) GetRawMdlOutput() MdlOutput {
	if o == nil {
		var ret MdlOutput
		return ret
	}

	return o.RawMdlOutput
}

// GetRawMdlOutputOk returns a tuple with the RawMdlOutput field value
// and a boolean to check if the value has been set.
func (o *AppleWalletProviderOutput) GetRawMdlOutputOk() (*MdlOutput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RawMdlOutput, true
}

// SetRawMdlOutput sets field value
func (o *AppleWalletProviderOutput) SetRawMdlOutput(v MdlOutput) {
	o.RawMdlOutput = v
}

func (o AppleWalletProviderOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppleWalletProviderOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rawMdlOutput"] = o.RawMdlOutput

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AppleWalletProviderOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rawMdlOutput",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppleWalletProviderOutput := _AppleWalletProviderOutput{}

	err = json.Unmarshal(data, &varAppleWalletProviderOutput)

	if err != nil {
		return err
	}

	*o = AppleWalletProviderOutput(varAppleWalletProviderOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "rawMdlOutput")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAppleWalletProviderOutput struct {
	value *AppleWalletProviderOutput
	isSet bool
}

func (v NullableAppleWalletProviderOutput) Get() *AppleWalletProviderOutput {
	return v.value
}

func (v *NullableAppleWalletProviderOutput) Set(val *AppleWalletProviderOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableAppleWalletProviderOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableAppleWalletProviderOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppleWalletProviderOutput(val *AppleWalletProviderOutput) *NullableAppleWalletProviderOutput {
	return &NullableAppleWalletProviderOutput{value: val, isSet: true}
}

func (v NullableAppleWalletProviderOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppleWalletProviderOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


