/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the EudiAgeVerificationCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EudiAgeVerificationCredential{}

// EudiAgeVerificationCredential An EUDI Age Verification credential, with document type `eu.europa.ec.eudi.av.1`.              This is the age verification credential type defined in the EUDI Wallet framework.
type EudiAgeVerificationCredential struct {
	// Processed age-over claims returned by the credential.
	AgeOver []AgeOverOutput `json:"ageOver,omitempty"`
	// Date when the age verification data expires.
	ExpiryDate NullableString `json:"expiryDate,omitempty"`
	// ISO 3166-1 alpha-2 country code of the country or territory of the issuer of the credential.
	IssuingCountry NullableString `json:"issuingCountry,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EudiAgeVerificationCredential EudiAgeVerificationCredential

// NewEudiAgeVerificationCredential instantiates a new EudiAgeVerificationCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEudiAgeVerificationCredential() *EudiAgeVerificationCredential {
	this := EudiAgeVerificationCredential{}
	return &this
}

// NewEudiAgeVerificationCredentialWithDefaults instantiates a new EudiAgeVerificationCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEudiAgeVerificationCredentialWithDefaults() *EudiAgeVerificationCredential {
	this := EudiAgeVerificationCredential{}
	return &this
}

// GetAgeOver returns the AgeOver field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EudiAgeVerificationCredential) GetAgeOver() []AgeOverOutput {
	if o == nil {
		var ret []AgeOverOutput
		return ret
	}
	return o.AgeOver
}

// GetAgeOverOk returns a tuple with the AgeOver field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EudiAgeVerificationCredential) GetAgeOverOk() ([]AgeOverOutput, bool) {
	if o == nil || IsNil(o.AgeOver) {
		return nil, false
	}
	return o.AgeOver, true
}

// HasAgeOver returns a boolean if a field has been set.
func (o *EudiAgeVerificationCredential) HasAgeOver() bool {
	if o != nil && !IsNil(o.AgeOver) {
		return true
	}

	return false
}

// SetAgeOver gets a reference to the given []AgeOverOutput and assigns it to the AgeOver field.
func (o *EudiAgeVerificationCredential) SetAgeOver(v []AgeOverOutput) {
	o.AgeOver = v
}

// GetExpiryDate returns the ExpiryDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EudiAgeVerificationCredential) GetExpiryDate() string {
	if o == nil || IsNil(o.ExpiryDate.Get()) {
		var ret string
		return ret
	}
	return *o.ExpiryDate.Get()
}

// GetExpiryDateOk returns a tuple with the ExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EudiAgeVerificationCredential) GetExpiryDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiryDate.Get(), o.ExpiryDate.IsSet()
}

// HasExpiryDate returns a boolean if a field has been set.
func (o *EudiAgeVerificationCredential) HasExpiryDate() bool {
	if o != nil && o.ExpiryDate.IsSet() {
		return true
	}

	return false
}

// SetExpiryDate gets a reference to the given NullableString and assigns it to the ExpiryDate field.
func (o *EudiAgeVerificationCredential) SetExpiryDate(v string) {
	o.ExpiryDate.Set(&v)
}
// SetExpiryDateNil sets the value for ExpiryDate to be an explicit nil
func (o *EudiAgeVerificationCredential) SetExpiryDateNil() {
	o.ExpiryDate.Set(nil)
}

// UnsetExpiryDate ensures that no value is present for ExpiryDate, not even an explicit nil
func (o *EudiAgeVerificationCredential) UnsetExpiryDate() {
	o.ExpiryDate.Unset()
}

// GetIssuingCountry returns the IssuingCountry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EudiAgeVerificationCredential) GetIssuingCountry() string {
	if o == nil || IsNil(o.IssuingCountry.Get()) {
		var ret string
		return ret
	}
	return *o.IssuingCountry.Get()
}

// GetIssuingCountryOk returns a tuple with the IssuingCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EudiAgeVerificationCredential) GetIssuingCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IssuingCountry.Get(), o.IssuingCountry.IsSet()
}

// HasIssuingCountry returns a boolean if a field has been set.
func (o *EudiAgeVerificationCredential) HasIssuingCountry() bool {
	if o != nil && o.IssuingCountry.IsSet() {
		return true
	}

	return false
}

// SetIssuingCountry gets a reference to the given NullableString and assigns it to the IssuingCountry field.
func (o *EudiAgeVerificationCredential) SetIssuingCountry(v string) {
	o.IssuingCountry.Set(&v)
}
// SetIssuingCountryNil sets the value for IssuingCountry to be an explicit nil
func (o *EudiAgeVerificationCredential) SetIssuingCountryNil() {
	o.IssuingCountry.Set(nil)
}

// UnsetIssuingCountry ensures that no value is present for IssuingCountry, not even an explicit nil
func (o *EudiAgeVerificationCredential) UnsetIssuingCountry() {
	o.IssuingCountry.Unset()
}

func (o EudiAgeVerificationCredential) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EudiAgeVerificationCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AgeOver != nil {
		toSerialize["ageOver"] = o.AgeOver
	}
	if o.ExpiryDate.IsSet() {
		toSerialize["expiryDate"] = o.ExpiryDate.Get()
	}
	if o.IssuingCountry.IsSet() {
		toSerialize["issuingCountry"] = o.IssuingCountry.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EudiAgeVerificationCredential) UnmarshalJSON(data []byte) (err error) {
	varEudiAgeVerificationCredential := _EudiAgeVerificationCredential{}

	err = json.Unmarshal(data, &varEudiAgeVerificationCredential)

	if err != nil {
		return err
	}

	*o = EudiAgeVerificationCredential(varEudiAgeVerificationCredential)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ageOver")
		delete(additionalProperties, "expiryDate")
		delete(additionalProperties, "issuingCountry")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEudiAgeVerificationCredential struct {
	value *EudiAgeVerificationCredential
	isSet bool
}

func (v NullableEudiAgeVerificationCredential) Get() *EudiAgeVerificationCredential {
	return v.value
}

func (v *NullableEudiAgeVerificationCredential) Set(val *EudiAgeVerificationCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableEudiAgeVerificationCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableEudiAgeVerificationCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEudiAgeVerificationCredential(val *EudiAgeVerificationCredential) *NullableEudiAgeVerificationCredential {
	return &NullableEudiAgeVerificationCredential{value: val, isSet: true}
}

func (v NullableEudiAgeVerificationCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEudiAgeVerificationCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


