/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
	"fmt"
)

// checks if the GoogleWalletProviderOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoogleWalletProviderOutput{}

// GoogleWalletProviderOutput Exposed properties for the `google-wallet` Provider which do not directly map to the normalized IdentityData model.
type GoogleWalletProviderOutput struct {
	// The raw output of the mDL exchange performed through Google Wallet.
	RawMdlOutput MdlOutput `json:"rawMdlOutput"`
	AdditionalProperties map[string]interface{}
}

type _GoogleWalletProviderOutput GoogleWalletProviderOutput

// NewGoogleWalletProviderOutput instantiates a new GoogleWalletProviderOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleWalletProviderOutput(rawMdlOutput MdlOutput) *GoogleWalletProviderOutput {
	this := GoogleWalletProviderOutput{}
	this.RawMdlOutput = rawMdlOutput
	return &this
}

// NewGoogleWalletProviderOutputWithDefaults instantiates a new GoogleWalletProviderOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleWalletProviderOutputWithDefaults() *GoogleWalletProviderOutput {
	this := GoogleWalletProviderOutput{}
	return &this
}

// GetRawMdlOutput returns the RawMdlOutput field value
func (o *GoogleWalletProviderOutput) GetRawMdlOutput() MdlOutput {
	if o == nil {
		var ret MdlOutput
		return ret
	}

	return o.RawMdlOutput
}

// GetRawMdlOutputOk returns a tuple with the RawMdlOutput field value
// and a boolean to check if the value has been set.
func (o *GoogleWalletProviderOutput) GetRawMdlOutputOk() (*MdlOutput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RawMdlOutput, true
}

// SetRawMdlOutput sets field value
func (o *GoogleWalletProviderOutput) SetRawMdlOutput(v MdlOutput) {
	o.RawMdlOutput = v
}

func (o GoogleWalletProviderOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoogleWalletProviderOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rawMdlOutput"] = o.RawMdlOutput

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GoogleWalletProviderOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rawMdlOutput",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGoogleWalletProviderOutput := _GoogleWalletProviderOutput{}

	err = json.Unmarshal(data, &varGoogleWalletProviderOutput)

	if err != nil {
		return err
	}

	*o = GoogleWalletProviderOutput(varGoogleWalletProviderOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "rawMdlOutput")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGoogleWalletProviderOutput struct {
	value *GoogleWalletProviderOutput
	isSet bool
}

func (v NullableGoogleWalletProviderOutput) Get() *GoogleWalletProviderOutput {
	return v.value
}

func (v *NullableGoogleWalletProviderOutput) Set(val *GoogleWalletProviderOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleWalletProviderOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleWalletProviderOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleWalletProviderOutput(val *GoogleWalletProviderOutput) *NullableGoogleWalletProviderOutput {
	return &NullableGoogleWalletProviderOutput{value: val, isSet: true}
}

func (v NullableGoogleWalletProviderOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleWalletProviderOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


