/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the CzechMojeIdAddressOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CzechMojeIdAddressOutput{}

// CzechMojeIdAddressOutput struct for CzechMojeIdAddressOutput
type CzechMojeIdAddressOutput struct {
	// The street address line, including house number.
	StreetAddress NullableString `json:"streetAddress,omitempty"`
	// The city or locality.
	City NullableString `json:"city,omitempty"`
	// The region or state.
	Region NullableString `json:"region,omitempty"`
	// The postal code.
	PostalCode NullableString `json:"postalCode,omitempty"`
	// The ISO 3166-1 alpha-2 country code.
	Country NullableString `json:"country,omitempty"`
	// The full address as a formatted string, with components separated by newlines.
	FormattedAddress NullableString `json:"formattedAddress,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CzechMojeIdAddressOutput CzechMojeIdAddressOutput

// NewCzechMojeIdAddressOutput instantiates a new CzechMojeIdAddressOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCzechMojeIdAddressOutput() *CzechMojeIdAddressOutput {
	this := CzechMojeIdAddressOutput{}
	return &this
}

// NewCzechMojeIdAddressOutputWithDefaults instantiates a new CzechMojeIdAddressOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCzechMojeIdAddressOutputWithDefaults() *CzechMojeIdAddressOutput {
	this := CzechMojeIdAddressOutput{}
	return &this
}

// GetStreetAddress returns the StreetAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechMojeIdAddressOutput) GetStreetAddress() string {
	if o == nil || IsNil(o.StreetAddress.Get()) {
		var ret string
		return ret
	}
	return *o.StreetAddress.Get()
}

// GetStreetAddressOk returns a tuple with the StreetAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechMojeIdAddressOutput) GetStreetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StreetAddress.Get(), o.StreetAddress.IsSet()
}

// HasStreetAddress returns a boolean if a field has been set.
func (o *CzechMojeIdAddressOutput) HasStreetAddress() bool {
	if o != nil && o.StreetAddress.IsSet() {
		return true
	}

	return false
}

// SetStreetAddress gets a reference to the given NullableString and assigns it to the StreetAddress field.
func (o *CzechMojeIdAddressOutput) SetStreetAddress(v string) {
	o.StreetAddress.Set(&v)
}
// SetStreetAddressNil sets the value for StreetAddress to be an explicit nil
func (o *CzechMojeIdAddressOutput) SetStreetAddressNil() {
	o.StreetAddress.Set(nil)
}

// UnsetStreetAddress ensures that no value is present for StreetAddress, not even an explicit nil
func (o *CzechMojeIdAddressOutput) UnsetStreetAddress() {
	o.StreetAddress.Unset()
}

// GetCity returns the City field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechMojeIdAddressOutput) GetCity() string {
	if o == nil || IsNil(o.City.Get()) {
		var ret string
		return ret
	}
	return *o.City.Get()
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechMojeIdAddressOutput) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.City.Get(), o.City.IsSet()
}

// HasCity returns a boolean if a field has been set.
func (o *CzechMojeIdAddressOutput) HasCity() bool {
	if o != nil && o.City.IsSet() {
		return true
	}

	return false
}

// SetCity gets a reference to the given NullableString and assigns it to the City field.
func (o *CzechMojeIdAddressOutput) SetCity(v string) {
	o.City.Set(&v)
}
// SetCityNil sets the value for City to be an explicit nil
func (o *CzechMojeIdAddressOutput) SetCityNil() {
	o.City.Set(nil)
}

// UnsetCity ensures that no value is present for City, not even an explicit nil
func (o *CzechMojeIdAddressOutput) UnsetCity() {
	o.City.Unset()
}

// GetRegion returns the Region field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechMojeIdAddressOutput) GetRegion() string {
	if o == nil || IsNil(o.Region.Get()) {
		var ret string
		return ret
	}
	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechMojeIdAddressOutput) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// HasRegion returns a boolean if a field has been set.
func (o *CzechMojeIdAddressOutput) HasRegion() bool {
	if o != nil && o.Region.IsSet() {
		return true
	}

	return false
}

// SetRegion gets a reference to the given NullableString and assigns it to the Region field.
func (o *CzechMojeIdAddressOutput) SetRegion(v string) {
	o.Region.Set(&v)
}
// SetRegionNil sets the value for Region to be an explicit nil
func (o *CzechMojeIdAddressOutput) SetRegionNil() {
	o.Region.Set(nil)
}

// UnsetRegion ensures that no value is present for Region, not even an explicit nil
func (o *CzechMojeIdAddressOutput) UnsetRegion() {
	o.Region.Unset()
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechMojeIdAddressOutput) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode.Get()) {
		var ret string
		return ret
	}
	return *o.PostalCode.Get()
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechMojeIdAddressOutput) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PostalCode.Get(), o.PostalCode.IsSet()
}

// HasPostalCode returns a boolean if a field has been set.
func (o *CzechMojeIdAddressOutput) HasPostalCode() bool {
	if o != nil && o.PostalCode.IsSet() {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given NullableString and assigns it to the PostalCode field.
func (o *CzechMojeIdAddressOutput) SetPostalCode(v string) {
	o.PostalCode.Set(&v)
}
// SetPostalCodeNil sets the value for PostalCode to be an explicit nil
func (o *CzechMojeIdAddressOutput) SetPostalCodeNil() {
	o.PostalCode.Set(nil)
}

// UnsetPostalCode ensures that no value is present for PostalCode, not even an explicit nil
func (o *CzechMojeIdAddressOutput) UnsetPostalCode() {
	o.PostalCode.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechMojeIdAddressOutput) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechMojeIdAddressOutput) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *CzechMojeIdAddressOutput) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *CzechMojeIdAddressOutput) SetCountry(v string) {
	o.Country.Set(&v)
}
// SetCountryNil sets the value for Country to be an explicit nil
func (o *CzechMojeIdAddressOutput) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *CzechMojeIdAddressOutput) UnsetCountry() {
	o.Country.Unset()
}

// GetFormattedAddress returns the FormattedAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CzechMojeIdAddressOutput) GetFormattedAddress() string {
	if o == nil || IsNil(o.FormattedAddress.Get()) {
		var ret string
		return ret
	}
	return *o.FormattedAddress.Get()
}

// GetFormattedAddressOk returns a tuple with the FormattedAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CzechMojeIdAddressOutput) GetFormattedAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FormattedAddress.Get(), o.FormattedAddress.IsSet()
}

// HasFormattedAddress returns a boolean if a field has been set.
func (o *CzechMojeIdAddressOutput) HasFormattedAddress() bool {
	if o != nil && o.FormattedAddress.IsSet() {
		return true
	}

	return false
}

// SetFormattedAddress gets a reference to the given NullableString and assigns it to the FormattedAddress field.
func (o *CzechMojeIdAddressOutput) SetFormattedAddress(v string) {
	o.FormattedAddress.Set(&v)
}
// SetFormattedAddressNil sets the value for FormattedAddress to be an explicit nil
func (o *CzechMojeIdAddressOutput) SetFormattedAddressNil() {
	o.FormattedAddress.Set(nil)
}

// UnsetFormattedAddress ensures that no value is present for FormattedAddress, not even an explicit nil
func (o *CzechMojeIdAddressOutput) UnsetFormattedAddress() {
	o.FormattedAddress.Unset()
}

func (o CzechMojeIdAddressOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CzechMojeIdAddressOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.StreetAddress.IsSet() {
		toSerialize["streetAddress"] = o.StreetAddress.Get()
	}
	if o.City.IsSet() {
		toSerialize["city"] = o.City.Get()
	}
	if o.Region.IsSet() {
		toSerialize["region"] = o.Region.Get()
	}
	if o.PostalCode.IsSet() {
		toSerialize["postalCode"] = o.PostalCode.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if o.FormattedAddress.IsSet() {
		toSerialize["formattedAddress"] = o.FormattedAddress.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CzechMojeIdAddressOutput) UnmarshalJSON(data []byte) (err error) {
	varCzechMojeIdAddressOutput := _CzechMojeIdAddressOutput{}

	err = json.Unmarshal(data, &varCzechMojeIdAddressOutput)

	if err != nil {
		return err
	}

	*o = CzechMojeIdAddressOutput(varCzechMojeIdAddressOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "streetAddress")
		delete(additionalProperties, "city")
		delete(additionalProperties, "region")
		delete(additionalProperties, "postalCode")
		delete(additionalProperties, "country")
		delete(additionalProperties, "formattedAddress")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCzechMojeIdAddressOutput struct {
	value *CzechMojeIdAddressOutput
	isSet bool
}

func (v NullableCzechMojeIdAddressOutput) Get() *CzechMojeIdAddressOutput {
	return v.value
}

func (v *NullableCzechMojeIdAddressOutput) Set(val *CzechMojeIdAddressOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableCzechMojeIdAddressOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableCzechMojeIdAddressOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCzechMojeIdAddressOutput(val *CzechMojeIdAddressOutput) *NullableCzechMojeIdAddressOutput {
	return &NullableCzechMojeIdAddressOutput{value: val, isSet: true}
}

func (v NullableCzechMojeIdAddressOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCzechMojeIdAddressOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


