/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the Iso180132BiometricGroupTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Iso180132BiometricGroupTemplate{}

// Iso180132BiometricGroupTemplate A group of biometric templates returned for a single biometric category, per ISO 18013-2 Table C.11.
type Iso180132BiometricGroupTemplate struct {
	// Individual biometric templates contained in this group.
	Templates []Iso180132BiometricTemplate `json:"templates,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Iso180132BiometricGroupTemplate Iso180132BiometricGroupTemplate

// NewIso180132BiometricGroupTemplate instantiates a new Iso180132BiometricGroupTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIso180132BiometricGroupTemplate() *Iso180132BiometricGroupTemplate {
	this := Iso180132BiometricGroupTemplate{}
	return &this
}

// NewIso180132BiometricGroupTemplateWithDefaults instantiates a new Iso180132BiometricGroupTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIso180132BiometricGroupTemplateWithDefaults() *Iso180132BiometricGroupTemplate {
	this := Iso180132BiometricGroupTemplate{}
	return &this
}

// GetTemplates returns the Templates field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Iso180132BiometricGroupTemplate) GetTemplates() []Iso180132BiometricTemplate {
	if o == nil {
		var ret []Iso180132BiometricTemplate
		return ret
	}
	return o.Templates
}

// GetTemplatesOk returns a tuple with the Templates field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Iso180132BiometricGroupTemplate) GetTemplatesOk() ([]Iso180132BiometricTemplate, bool) {
	if o == nil || IsNil(o.Templates) {
		return nil, false
	}
	return o.Templates, true
}

// HasTemplates returns a boolean if a field has been set.
func (o *Iso180132BiometricGroupTemplate) HasTemplates() bool {
	if o != nil && !IsNil(o.Templates) {
		return true
	}

	return false
}

// SetTemplates gets a reference to the given []Iso180132BiometricTemplate and assigns it to the Templates field.
func (o *Iso180132BiometricGroupTemplate) SetTemplates(v []Iso180132BiometricTemplate) {
	o.Templates = v
}

func (o Iso180132BiometricGroupTemplate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Iso180132BiometricGroupTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Templates != nil {
		toSerialize["templates"] = o.Templates
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Iso180132BiometricGroupTemplate) UnmarshalJSON(data []byte) (err error) {
	varIso180132BiometricGroupTemplate := _Iso180132BiometricGroupTemplate{}

	err = json.Unmarshal(data, &varIso180132BiometricGroupTemplate)

	if err != nil {
		return err
	}

	*o = Iso180132BiometricGroupTemplate(varIso180132BiometricGroupTemplate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "templates")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIso180132BiometricGroupTemplate struct {
	value *Iso180132BiometricGroupTemplate
	isSet bool
}

func (v NullableIso180132BiometricGroupTemplate) Get() *Iso180132BiometricGroupTemplate {
	return v.value
}

func (v *NullableIso180132BiometricGroupTemplate) Set(val *Iso180132BiometricGroupTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableIso180132BiometricGroupTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableIso180132BiometricGroupTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIso180132BiometricGroupTemplate(val *Iso180132BiometricGroupTemplate) *NullableIso180132BiometricGroupTemplate {
	return &NullableIso180132BiometricGroupTemplate{value: val, isSet: true}
}

func (v NullableIso180132BiometricGroupTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIso180132BiometricGroupTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


