/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the NorwegianBankIdProviderOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NorwegianBankIdProviderOutput{}

// NorwegianBankIdProviderOutput Exposed properties for the `norway-bankid` Provider which do not directly map to the normalized IdentityData model.
type NorwegianBankIdProviderOutput struct {
	// The full name of the individual.
	FullName NullableString `json:"fullName,omitempty"`
	// The date of birth of the individual.
	DateOfBirth NullableString `json:"dateOfBirth,omitempty"`
	// The personal identifier for Norwegian BankID.              This uniquely identifies the individual in the Norwegian BankID system and is considered a stable identifier to use.
	PersonalIdentifier NullableString `json:"personalIdentifier,omitempty"`
	// The 11-digit Norwegian National Identity Number (fødselsnummer) of the verified individual.              This is in the format DDMMYYZZZCC, where: - DDMMYY is the date of birth (In some cases, this is not the date of birth due to no available identity numbers for some dates - ZZZ is an individual number, indicating gender - CC is a checksum character              If ZZZ is even, the individual is female. If ZZZ is odd, the individual is male.
	NationalIdentityNumber NullableString `json:"nationalIdentityNumber,omitempty"`
	// The given name of the individual.
	GivenName NullableString `json:"givenName,omitempty"`
	// The family name of the individual.
	FamilyName NullableString `json:"familyName,omitempty"`
	// The level of assurance (LOA) for the verification.              The LOA refers to the degree of confidence in the claimed identity of a person. The European Digital Identity Framework (EUDI) measures the confidence of the digital identity's verification and authentication strength by a set of requirements for different levels. To learn more, see: https://ec.europa.eu/digital-building-blocks/sites/spaces/DIGITAL/pages/467110081/eIDAS+Levels+of+Assurance              Possible values: - Low: The individual has self asserted their identity and multifactor authentication is not required. - Substantial: The individual has performed either a remote or in-person identity verification and multifactor authentication is required. - High: The individual has performed an in-person identity proofing with an authorized representative and has strong cryptographic authentication requirements such as using a smart card.
	LevelOfAssurance NullableString `json:"levelOfAssurance,omitempty"`
	// The authentication method used by the individual.              Possible values: - urn:bankid:bis - BankID with Biometrics - urn:bankid:bid - Standard BankID with High Assurance
	AuthenticationMethod NullableString `json:"authenticationMethod,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NorwegianBankIdProviderOutput NorwegianBankIdProviderOutput

// NewNorwegianBankIdProviderOutput instantiates a new NorwegianBankIdProviderOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNorwegianBankIdProviderOutput() *NorwegianBankIdProviderOutput {
	this := NorwegianBankIdProviderOutput{}
	return &this
}

// NewNorwegianBankIdProviderOutputWithDefaults instantiates a new NorwegianBankIdProviderOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNorwegianBankIdProviderOutputWithDefaults() *NorwegianBankIdProviderOutput {
	this := NorwegianBankIdProviderOutput{}
	return &this
}

// GetFullName returns the FullName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NorwegianBankIdProviderOutput) GetFullName() string {
	if o == nil || IsNil(o.FullName.Get()) {
		var ret string
		return ret
	}
	return *o.FullName.Get()
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NorwegianBankIdProviderOutput) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FullName.Get(), o.FullName.IsSet()
}

// HasFullName returns a boolean if a field has been set.
func (o *NorwegianBankIdProviderOutput) HasFullName() bool {
	if o != nil && o.FullName.IsSet() {
		return true
	}

	return false
}

// SetFullName gets a reference to the given NullableString and assigns it to the FullName field.
func (o *NorwegianBankIdProviderOutput) SetFullName(v string) {
	o.FullName.Set(&v)
}
// SetFullNameNil sets the value for FullName to be an explicit nil
func (o *NorwegianBankIdProviderOutput) SetFullNameNil() {
	o.FullName.Set(nil)
}

// UnsetFullName ensures that no value is present for FullName, not even an explicit nil
func (o *NorwegianBankIdProviderOutput) UnsetFullName() {
	o.FullName.Unset()
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NorwegianBankIdProviderOutput) GetDateOfBirth() string {
	if o == nil || IsNil(o.DateOfBirth.Get()) {
		var ret string
		return ret
	}
	return *o.DateOfBirth.Get()
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NorwegianBankIdProviderOutput) GetDateOfBirthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfBirth.Get(), o.DateOfBirth.IsSet()
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *NorwegianBankIdProviderOutput) HasDateOfBirth() bool {
	if o != nil && o.DateOfBirth.IsSet() {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given NullableString and assigns it to the DateOfBirth field.
func (o *NorwegianBankIdProviderOutput) SetDateOfBirth(v string) {
	o.DateOfBirth.Set(&v)
}
// SetDateOfBirthNil sets the value for DateOfBirth to be an explicit nil
func (o *NorwegianBankIdProviderOutput) SetDateOfBirthNil() {
	o.DateOfBirth.Set(nil)
}

// UnsetDateOfBirth ensures that no value is present for DateOfBirth, not even an explicit nil
func (o *NorwegianBankIdProviderOutput) UnsetDateOfBirth() {
	o.DateOfBirth.Unset()
}

// GetPersonalIdentifier returns the PersonalIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NorwegianBankIdProviderOutput) GetPersonalIdentifier() string {
	if o == nil || IsNil(o.PersonalIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.PersonalIdentifier.Get()
}

// GetPersonalIdentifierOk returns a tuple with the PersonalIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NorwegianBankIdProviderOutput) GetPersonalIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PersonalIdentifier.Get(), o.PersonalIdentifier.IsSet()
}

// HasPersonalIdentifier returns a boolean if a field has been set.
func (o *NorwegianBankIdProviderOutput) HasPersonalIdentifier() bool {
	if o != nil && o.PersonalIdentifier.IsSet() {
		return true
	}

	return false
}

// SetPersonalIdentifier gets a reference to the given NullableString and assigns it to the PersonalIdentifier field.
func (o *NorwegianBankIdProviderOutput) SetPersonalIdentifier(v string) {
	o.PersonalIdentifier.Set(&v)
}
// SetPersonalIdentifierNil sets the value for PersonalIdentifier to be an explicit nil
func (o *NorwegianBankIdProviderOutput) SetPersonalIdentifierNil() {
	o.PersonalIdentifier.Set(nil)
}

// UnsetPersonalIdentifier ensures that no value is present for PersonalIdentifier, not even an explicit nil
func (o *NorwegianBankIdProviderOutput) UnsetPersonalIdentifier() {
	o.PersonalIdentifier.Unset()
}

// GetNationalIdentityNumber returns the NationalIdentityNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NorwegianBankIdProviderOutput) GetNationalIdentityNumber() string {
	if o == nil || IsNil(o.NationalIdentityNumber.Get()) {
		var ret string
		return ret
	}
	return *o.NationalIdentityNumber.Get()
}

// GetNationalIdentityNumberOk returns a tuple with the NationalIdentityNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NorwegianBankIdProviderOutput) GetNationalIdentityNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NationalIdentityNumber.Get(), o.NationalIdentityNumber.IsSet()
}

// HasNationalIdentityNumber returns a boolean if a field has been set.
func (o *NorwegianBankIdProviderOutput) HasNationalIdentityNumber() bool {
	if o != nil && o.NationalIdentityNumber.IsSet() {
		return true
	}

	return false
}

// SetNationalIdentityNumber gets a reference to the given NullableString and assigns it to the NationalIdentityNumber field.
func (o *NorwegianBankIdProviderOutput) SetNationalIdentityNumber(v string) {
	o.NationalIdentityNumber.Set(&v)
}
// SetNationalIdentityNumberNil sets the value for NationalIdentityNumber to be an explicit nil
func (o *NorwegianBankIdProviderOutput) SetNationalIdentityNumberNil() {
	o.NationalIdentityNumber.Set(nil)
}

// UnsetNationalIdentityNumber ensures that no value is present for NationalIdentityNumber, not even an explicit nil
func (o *NorwegianBankIdProviderOutput) UnsetNationalIdentityNumber() {
	o.NationalIdentityNumber.Unset()
}

// GetGivenName returns the GivenName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NorwegianBankIdProviderOutput) GetGivenName() string {
	if o == nil || IsNil(o.GivenName.Get()) {
		var ret string
		return ret
	}
	return *o.GivenName.Get()
}

// GetGivenNameOk returns a tuple with the GivenName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NorwegianBankIdProviderOutput) GetGivenNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GivenName.Get(), o.GivenName.IsSet()
}

// HasGivenName returns a boolean if a field has been set.
func (o *NorwegianBankIdProviderOutput) HasGivenName() bool {
	if o != nil && o.GivenName.IsSet() {
		return true
	}

	return false
}

// SetGivenName gets a reference to the given NullableString and assigns it to the GivenName field.
func (o *NorwegianBankIdProviderOutput) SetGivenName(v string) {
	o.GivenName.Set(&v)
}
// SetGivenNameNil sets the value for GivenName to be an explicit nil
func (o *NorwegianBankIdProviderOutput) SetGivenNameNil() {
	o.GivenName.Set(nil)
}

// UnsetGivenName ensures that no value is present for GivenName, not even an explicit nil
func (o *NorwegianBankIdProviderOutput) UnsetGivenName() {
	o.GivenName.Unset()
}

// GetFamilyName returns the FamilyName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NorwegianBankIdProviderOutput) GetFamilyName() string {
	if o == nil || IsNil(o.FamilyName.Get()) {
		var ret string
		return ret
	}
	return *o.FamilyName.Get()
}

// GetFamilyNameOk returns a tuple with the FamilyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NorwegianBankIdProviderOutput) GetFamilyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FamilyName.Get(), o.FamilyName.IsSet()
}

// HasFamilyName returns a boolean if a field has been set.
func (o *NorwegianBankIdProviderOutput) HasFamilyName() bool {
	if o != nil && o.FamilyName.IsSet() {
		return true
	}

	return false
}

// SetFamilyName gets a reference to the given NullableString and assigns it to the FamilyName field.
func (o *NorwegianBankIdProviderOutput) SetFamilyName(v string) {
	o.FamilyName.Set(&v)
}
// SetFamilyNameNil sets the value for FamilyName to be an explicit nil
func (o *NorwegianBankIdProviderOutput) SetFamilyNameNil() {
	o.FamilyName.Set(nil)
}

// UnsetFamilyName ensures that no value is present for FamilyName, not even an explicit nil
func (o *NorwegianBankIdProviderOutput) UnsetFamilyName() {
	o.FamilyName.Unset()
}

// GetLevelOfAssurance returns the LevelOfAssurance field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NorwegianBankIdProviderOutput) GetLevelOfAssurance() string {
	if o == nil || IsNil(o.LevelOfAssurance.Get()) {
		var ret string
		return ret
	}
	return *o.LevelOfAssurance.Get()
}

// GetLevelOfAssuranceOk returns a tuple with the LevelOfAssurance field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NorwegianBankIdProviderOutput) GetLevelOfAssuranceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LevelOfAssurance.Get(), o.LevelOfAssurance.IsSet()
}

// HasLevelOfAssurance returns a boolean if a field has been set.
func (o *NorwegianBankIdProviderOutput) HasLevelOfAssurance() bool {
	if o != nil && o.LevelOfAssurance.IsSet() {
		return true
	}

	return false
}

// SetLevelOfAssurance gets a reference to the given NullableString and assigns it to the LevelOfAssurance field.
func (o *NorwegianBankIdProviderOutput) SetLevelOfAssurance(v string) {
	o.LevelOfAssurance.Set(&v)
}
// SetLevelOfAssuranceNil sets the value for LevelOfAssurance to be an explicit nil
func (o *NorwegianBankIdProviderOutput) SetLevelOfAssuranceNil() {
	o.LevelOfAssurance.Set(nil)
}

// UnsetLevelOfAssurance ensures that no value is present for LevelOfAssurance, not even an explicit nil
func (o *NorwegianBankIdProviderOutput) UnsetLevelOfAssurance() {
	o.LevelOfAssurance.Unset()
}

// GetAuthenticationMethod returns the AuthenticationMethod field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NorwegianBankIdProviderOutput) GetAuthenticationMethod() string {
	if o == nil || IsNil(o.AuthenticationMethod.Get()) {
		var ret string
		return ret
	}
	return *o.AuthenticationMethod.Get()
}

// GetAuthenticationMethodOk returns a tuple with the AuthenticationMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NorwegianBankIdProviderOutput) GetAuthenticationMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthenticationMethod.Get(), o.AuthenticationMethod.IsSet()
}

// HasAuthenticationMethod returns a boolean if a field has been set.
func (o *NorwegianBankIdProviderOutput) HasAuthenticationMethod() bool {
	if o != nil && o.AuthenticationMethod.IsSet() {
		return true
	}

	return false
}

// SetAuthenticationMethod gets a reference to the given NullableString and assigns it to the AuthenticationMethod field.
func (o *NorwegianBankIdProviderOutput) SetAuthenticationMethod(v string) {
	o.AuthenticationMethod.Set(&v)
}
// SetAuthenticationMethodNil sets the value for AuthenticationMethod to be an explicit nil
func (o *NorwegianBankIdProviderOutput) SetAuthenticationMethodNil() {
	o.AuthenticationMethod.Set(nil)
}

// UnsetAuthenticationMethod ensures that no value is present for AuthenticationMethod, not even an explicit nil
func (o *NorwegianBankIdProviderOutput) UnsetAuthenticationMethod() {
	o.AuthenticationMethod.Unset()
}

func (o NorwegianBankIdProviderOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NorwegianBankIdProviderOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.FullName.IsSet() {
		toSerialize["fullName"] = o.FullName.Get()
	}
	if o.DateOfBirth.IsSet() {
		toSerialize["dateOfBirth"] = o.DateOfBirth.Get()
	}
	if o.PersonalIdentifier.IsSet() {
		toSerialize["personalIdentifier"] = o.PersonalIdentifier.Get()
	}
	if o.NationalIdentityNumber.IsSet() {
		toSerialize["nationalIdentityNumber"] = o.NationalIdentityNumber.Get()
	}
	if o.GivenName.IsSet() {
		toSerialize["givenName"] = o.GivenName.Get()
	}
	if o.FamilyName.IsSet() {
		toSerialize["familyName"] = o.FamilyName.Get()
	}
	if o.LevelOfAssurance.IsSet() {
		toSerialize["levelOfAssurance"] = o.LevelOfAssurance.Get()
	}
	if o.AuthenticationMethod.IsSet() {
		toSerialize["authenticationMethod"] = o.AuthenticationMethod.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NorwegianBankIdProviderOutput) UnmarshalJSON(data []byte) (err error) {
	varNorwegianBankIdProviderOutput := _NorwegianBankIdProviderOutput{}

	err = json.Unmarshal(data, &varNorwegianBankIdProviderOutput)

	if err != nil {
		return err
	}

	*o = NorwegianBankIdProviderOutput(varNorwegianBankIdProviderOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fullName")
		delete(additionalProperties, "dateOfBirth")
		delete(additionalProperties, "personalIdentifier")
		delete(additionalProperties, "nationalIdentityNumber")
		delete(additionalProperties, "givenName")
		delete(additionalProperties, "familyName")
		delete(additionalProperties, "levelOfAssurance")
		delete(additionalProperties, "authenticationMethod")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNorwegianBankIdProviderOutput struct {
	value *NorwegianBankIdProviderOutput
	isSet bool
}

func (v NullableNorwegianBankIdProviderOutput) Get() *NorwegianBankIdProviderOutput {
	return v.value
}

func (v *NullableNorwegianBankIdProviderOutput) Set(val *NorwegianBankIdProviderOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableNorwegianBankIdProviderOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableNorwegianBankIdProviderOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNorwegianBankIdProviderOutput(val *NorwegianBankIdProviderOutput) *NullableNorwegianBankIdProviderOutput {
	return &NullableNorwegianBankIdProviderOutput{value: val, isSet: true}
}

func (v NullableNorwegianBankIdProviderOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNorwegianBankIdProviderOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


