/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the NigeriaNinMatch2Input type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NigeriaNinMatch2Input{}

// NigeriaNinMatch2Input struct for NigeriaNinMatch2Input
type NigeriaNinMatch2Input struct {
	// The user's Nigerian National ID number (NIN)
	IdNumber NullableString `json:"idNumber,omitempty"`
	// The user's first name as it appears in their National ID
	GivenName NullableString `json:"givenName,omitempty"`
	// The user's last name as it appears in their National ID
	FamilyName NullableString `json:"familyName,omitempty"`
	// The user's middle name as it appears in their National ID (optional)
	MiddleName NullableString `json:"middleName,omitempty"`
	// The user's date of birth, in `YYYY-MM-DD` format
	DateOfBirth NullableString `json:"dateOfBirth,omitempty"`
	// The user's sex as it appears in their National ID
	Sex NullableNigeriaNinMatch2InputSex `json:"sex,omitempty"`
	// The user's phone number as it appears in their National ID (optional). Must be in E.164 international format: \"+234XXXXXXXXX\"
	PhoneNumber NullableString `json:"phoneNumber,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NigeriaNinMatch2Input NigeriaNinMatch2Input

// NewNigeriaNinMatch2Input instantiates a new NigeriaNinMatch2Input object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNigeriaNinMatch2Input() *NigeriaNinMatch2Input {
	this := NigeriaNinMatch2Input{}
	return &this
}

// NewNigeriaNinMatch2InputWithDefaults instantiates a new NigeriaNinMatch2Input object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNigeriaNinMatch2InputWithDefaults() *NigeriaNinMatch2Input {
	this := NigeriaNinMatch2Input{}
	return &this
}

// GetIdNumber returns the IdNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NigeriaNinMatch2Input) GetIdNumber() string {
	if o == nil || IsNil(o.IdNumber.Get()) {
		var ret string
		return ret
	}
	return *o.IdNumber.Get()
}

// GetIdNumberOk returns a tuple with the IdNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NigeriaNinMatch2Input) GetIdNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IdNumber.Get(), o.IdNumber.IsSet()
}

// HasIdNumber returns a boolean if a field has been set.
func (o *NigeriaNinMatch2Input) HasIdNumber() bool {
	if o != nil && o.IdNumber.IsSet() {
		return true
	}

	return false
}

// SetIdNumber gets a reference to the given NullableString and assigns it to the IdNumber field.
func (o *NigeriaNinMatch2Input) SetIdNumber(v string) {
	o.IdNumber.Set(&v)
}
// SetIdNumberNil sets the value for IdNumber to be an explicit nil
func (o *NigeriaNinMatch2Input) SetIdNumberNil() {
	o.IdNumber.Set(nil)
}

// UnsetIdNumber ensures that no value is present for IdNumber, not even an explicit nil
func (o *NigeriaNinMatch2Input) UnsetIdNumber() {
	o.IdNumber.Unset()
}

// GetGivenName returns the GivenName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NigeriaNinMatch2Input) GetGivenName() string {
	if o == nil || IsNil(o.GivenName.Get()) {
		var ret string
		return ret
	}
	return *o.GivenName.Get()
}

// GetGivenNameOk returns a tuple with the GivenName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NigeriaNinMatch2Input) GetGivenNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GivenName.Get(), o.GivenName.IsSet()
}

// HasGivenName returns a boolean if a field has been set.
func (o *NigeriaNinMatch2Input) HasGivenName() bool {
	if o != nil && o.GivenName.IsSet() {
		return true
	}

	return false
}

// SetGivenName gets a reference to the given NullableString and assigns it to the GivenName field.
func (o *NigeriaNinMatch2Input) SetGivenName(v string) {
	o.GivenName.Set(&v)
}
// SetGivenNameNil sets the value for GivenName to be an explicit nil
func (o *NigeriaNinMatch2Input) SetGivenNameNil() {
	o.GivenName.Set(nil)
}

// UnsetGivenName ensures that no value is present for GivenName, not even an explicit nil
func (o *NigeriaNinMatch2Input) UnsetGivenName() {
	o.GivenName.Unset()
}

// GetFamilyName returns the FamilyName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NigeriaNinMatch2Input) GetFamilyName() string {
	if o == nil || IsNil(o.FamilyName.Get()) {
		var ret string
		return ret
	}
	return *o.FamilyName.Get()
}

// GetFamilyNameOk returns a tuple with the FamilyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NigeriaNinMatch2Input) GetFamilyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FamilyName.Get(), o.FamilyName.IsSet()
}

// HasFamilyName returns a boolean if a field has been set.
func (o *NigeriaNinMatch2Input) HasFamilyName() bool {
	if o != nil && o.FamilyName.IsSet() {
		return true
	}

	return false
}

// SetFamilyName gets a reference to the given NullableString and assigns it to the FamilyName field.
func (o *NigeriaNinMatch2Input) SetFamilyName(v string) {
	o.FamilyName.Set(&v)
}
// SetFamilyNameNil sets the value for FamilyName to be an explicit nil
func (o *NigeriaNinMatch2Input) SetFamilyNameNil() {
	o.FamilyName.Set(nil)
}

// UnsetFamilyName ensures that no value is present for FamilyName, not even an explicit nil
func (o *NigeriaNinMatch2Input) UnsetFamilyName() {
	o.FamilyName.Unset()
}

// GetMiddleName returns the MiddleName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NigeriaNinMatch2Input) GetMiddleName() string {
	if o == nil || IsNil(o.MiddleName.Get()) {
		var ret string
		return ret
	}
	return *o.MiddleName.Get()
}

// GetMiddleNameOk returns a tuple with the MiddleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NigeriaNinMatch2Input) GetMiddleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MiddleName.Get(), o.MiddleName.IsSet()
}

// HasMiddleName returns a boolean if a field has been set.
func (o *NigeriaNinMatch2Input) HasMiddleName() bool {
	if o != nil && o.MiddleName.IsSet() {
		return true
	}

	return false
}

// SetMiddleName gets a reference to the given NullableString and assigns it to the MiddleName field.
func (o *NigeriaNinMatch2Input) SetMiddleName(v string) {
	o.MiddleName.Set(&v)
}
// SetMiddleNameNil sets the value for MiddleName to be an explicit nil
func (o *NigeriaNinMatch2Input) SetMiddleNameNil() {
	o.MiddleName.Set(nil)
}

// UnsetMiddleName ensures that no value is present for MiddleName, not even an explicit nil
func (o *NigeriaNinMatch2Input) UnsetMiddleName() {
	o.MiddleName.Unset()
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NigeriaNinMatch2Input) GetDateOfBirth() string {
	if o == nil || IsNil(o.DateOfBirth.Get()) {
		var ret string
		return ret
	}
	return *o.DateOfBirth.Get()
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NigeriaNinMatch2Input) GetDateOfBirthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfBirth.Get(), o.DateOfBirth.IsSet()
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *NigeriaNinMatch2Input) HasDateOfBirth() bool {
	if o != nil && o.DateOfBirth.IsSet() {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given NullableString and assigns it to the DateOfBirth field.
func (o *NigeriaNinMatch2Input) SetDateOfBirth(v string) {
	o.DateOfBirth.Set(&v)
}
// SetDateOfBirthNil sets the value for DateOfBirth to be an explicit nil
func (o *NigeriaNinMatch2Input) SetDateOfBirthNil() {
	o.DateOfBirth.Set(nil)
}

// UnsetDateOfBirth ensures that no value is present for DateOfBirth, not even an explicit nil
func (o *NigeriaNinMatch2Input) UnsetDateOfBirth() {
	o.DateOfBirth.Unset()
}

// GetSex returns the Sex field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NigeriaNinMatch2Input) GetSex() NigeriaNinMatch2InputSex {
	if o == nil || IsNil(o.Sex.Get()) {
		var ret NigeriaNinMatch2InputSex
		return ret
	}
	return *o.Sex.Get()
}

// GetSexOk returns a tuple with the Sex field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NigeriaNinMatch2Input) GetSexOk() (*NigeriaNinMatch2InputSex, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sex.Get(), o.Sex.IsSet()
}

// HasSex returns a boolean if a field has been set.
func (o *NigeriaNinMatch2Input) HasSex() bool {
	if o != nil && o.Sex.IsSet() {
		return true
	}

	return false
}

// SetSex gets a reference to the given NullableNigeriaNinMatch2InputSex and assigns it to the Sex field.
func (o *NigeriaNinMatch2Input) SetSex(v NigeriaNinMatch2InputSex) {
	o.Sex.Set(&v)
}
// SetSexNil sets the value for Sex to be an explicit nil
func (o *NigeriaNinMatch2Input) SetSexNil() {
	o.Sex.Set(nil)
}

// UnsetSex ensures that no value is present for Sex, not even an explicit nil
func (o *NigeriaNinMatch2Input) UnsetSex() {
	o.Sex.Unset()
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NigeriaNinMatch2Input) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneNumber.Get()
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NigeriaNinMatch2Input) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneNumber.Get(), o.PhoneNumber.IsSet()
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *NigeriaNinMatch2Input) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber.IsSet() {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given NullableString and assigns it to the PhoneNumber field.
func (o *NigeriaNinMatch2Input) SetPhoneNumber(v string) {
	o.PhoneNumber.Set(&v)
}
// SetPhoneNumberNil sets the value for PhoneNumber to be an explicit nil
func (o *NigeriaNinMatch2Input) SetPhoneNumberNil() {
	o.PhoneNumber.Set(nil)
}

// UnsetPhoneNumber ensures that no value is present for PhoneNumber, not even an explicit nil
func (o *NigeriaNinMatch2Input) UnsetPhoneNumber() {
	o.PhoneNumber.Unset()
}

func (o NigeriaNinMatch2Input) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NigeriaNinMatch2Input) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.IdNumber.IsSet() {
		toSerialize["idNumber"] = o.IdNumber.Get()
	}
	if o.GivenName.IsSet() {
		toSerialize["givenName"] = o.GivenName.Get()
	}
	if o.FamilyName.IsSet() {
		toSerialize["familyName"] = o.FamilyName.Get()
	}
	if o.MiddleName.IsSet() {
		toSerialize["middleName"] = o.MiddleName.Get()
	}
	if o.DateOfBirth.IsSet() {
		toSerialize["dateOfBirth"] = o.DateOfBirth.Get()
	}
	if o.Sex.IsSet() {
		toSerialize["sex"] = o.Sex.Get()
	}
	if o.PhoneNumber.IsSet() {
		toSerialize["phoneNumber"] = o.PhoneNumber.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NigeriaNinMatch2Input) UnmarshalJSON(data []byte) (err error) {
	varNigeriaNinMatch2Input := _NigeriaNinMatch2Input{}

	err = json.Unmarshal(data, &varNigeriaNinMatch2Input)

	if err != nil {
		return err
	}

	*o = NigeriaNinMatch2Input(varNigeriaNinMatch2Input)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "idNumber")
		delete(additionalProperties, "givenName")
		delete(additionalProperties, "familyName")
		delete(additionalProperties, "middleName")
		delete(additionalProperties, "dateOfBirth")
		delete(additionalProperties, "sex")
		delete(additionalProperties, "phoneNumber")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNigeriaNinMatch2Input struct {
	value *NigeriaNinMatch2Input
	isSet bool
}

func (v NullableNigeriaNinMatch2Input) Get() *NigeriaNinMatch2Input {
	return v.value
}

func (v *NullableNigeriaNinMatch2Input) Set(val *NigeriaNinMatch2Input) {
	v.value = val
	v.isSet = true
}

func (v NullableNigeriaNinMatch2Input) IsSet() bool {
	return v.isSet
}

func (v *NullableNigeriaNinMatch2Input) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNigeriaNinMatch2Input(val *NigeriaNinMatch2Input) *NullableNigeriaNinMatch2Input {
	return &NullableNigeriaNinMatch2Input{value: val, isSet: true}
}

func (v NullableNigeriaNinMatch2Input) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNigeriaNinMatch2Input) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


