/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the AadhaarClaims type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AadhaarClaims{}

// AadhaarClaims struct for AadhaarClaims
type AadhaarClaims struct {
	// The full name.
	Name NullableString `json:"name,omitempty"`
	// The date of birth.              The format is YYYY-MM-DD.
	DateOfBirth NullableString `json:"dateOfBirth,omitempty"`
	// The gender of the individual.              Possible values: - M (Male) - F (Female) - T (Transgender)
	Gender NullableString `json:"gender,omitempty"`
	// The structured Indian address.
	Address NullableAadhaarAddress `json:"address,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AadhaarClaims AadhaarClaims

// NewAadhaarClaims instantiates a new AadhaarClaims object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAadhaarClaims() *AadhaarClaims {
	this := AadhaarClaims{}
	return &this
}

// NewAadhaarClaimsWithDefaults instantiates a new AadhaarClaims object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAadhaarClaimsWithDefaults() *AadhaarClaims {
	this := AadhaarClaims{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AadhaarClaims) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AadhaarClaims) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *AadhaarClaims) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *AadhaarClaims) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *AadhaarClaims) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *AadhaarClaims) UnsetName() {
	o.Name.Unset()
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AadhaarClaims) GetDateOfBirth() string {
	if o == nil || IsNil(o.DateOfBirth.Get()) {
		var ret string
		return ret
	}
	return *o.DateOfBirth.Get()
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AadhaarClaims) GetDateOfBirthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfBirth.Get(), o.DateOfBirth.IsSet()
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *AadhaarClaims) HasDateOfBirth() bool {
	if o != nil && o.DateOfBirth.IsSet() {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given NullableString and assigns it to the DateOfBirth field.
func (o *AadhaarClaims) SetDateOfBirth(v string) {
	o.DateOfBirth.Set(&v)
}
// SetDateOfBirthNil sets the value for DateOfBirth to be an explicit nil
func (o *AadhaarClaims) SetDateOfBirthNil() {
	o.DateOfBirth.Set(nil)
}

// UnsetDateOfBirth ensures that no value is present for DateOfBirth, not even an explicit nil
func (o *AadhaarClaims) UnsetDateOfBirth() {
	o.DateOfBirth.Unset()
}

// GetGender returns the Gender field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AadhaarClaims) GetGender() string {
	if o == nil || IsNil(o.Gender.Get()) {
		var ret string
		return ret
	}
	return *o.Gender.Get()
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AadhaarClaims) GetGenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gender.Get(), o.Gender.IsSet()
}

// HasGender returns a boolean if a field has been set.
func (o *AadhaarClaims) HasGender() bool {
	if o != nil && o.Gender.IsSet() {
		return true
	}

	return false
}

// SetGender gets a reference to the given NullableString and assigns it to the Gender field.
func (o *AadhaarClaims) SetGender(v string) {
	o.Gender.Set(&v)
}
// SetGenderNil sets the value for Gender to be an explicit nil
func (o *AadhaarClaims) SetGenderNil() {
	o.Gender.Set(nil)
}

// UnsetGender ensures that no value is present for Gender, not even an explicit nil
func (o *AadhaarClaims) UnsetGender() {
	o.Gender.Unset()
}

// GetAddress returns the Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AadhaarClaims) GetAddress() AadhaarAddress {
	if o == nil || IsNil(o.Address.Get()) {
		var ret AadhaarAddress
		return ret
	}
	return *o.Address.Get()
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AadhaarClaims) GetAddressOk() (*AadhaarAddress, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address.Get(), o.Address.IsSet()
}

// HasAddress returns a boolean if a field has been set.
func (o *AadhaarClaims) HasAddress() bool {
	if o != nil && o.Address.IsSet() {
		return true
	}

	return false
}

// SetAddress gets a reference to the given NullableAadhaarAddress and assigns it to the Address field.
func (o *AadhaarClaims) SetAddress(v AadhaarAddress) {
	o.Address.Set(&v)
}
// SetAddressNil sets the value for Address to be an explicit nil
func (o *AadhaarClaims) SetAddressNil() {
	o.Address.Set(nil)
}

// UnsetAddress ensures that no value is present for Address, not even an explicit nil
func (o *AadhaarClaims) UnsetAddress() {
	o.Address.Unset()
}

func (o AadhaarClaims) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AadhaarClaims) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.DateOfBirth.IsSet() {
		toSerialize["dateOfBirth"] = o.DateOfBirth.Get()
	}
	if o.Gender.IsSet() {
		toSerialize["gender"] = o.Gender.Get()
	}
	if o.Address.IsSet() {
		toSerialize["address"] = o.Address.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AadhaarClaims) UnmarshalJSON(data []byte) (err error) {
	varAadhaarClaims := _AadhaarClaims{}

	err = json.Unmarshal(data, &varAadhaarClaims)

	if err != nil {
		return err
	}

	*o = AadhaarClaims(varAadhaarClaims)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "dateOfBirth")
		delete(additionalProperties, "gender")
		delete(additionalProperties, "address")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAadhaarClaims struct {
	value *AadhaarClaims
	isSet bool
}

func (v NullableAadhaarClaims) Get() *AadhaarClaims {
	return v.value
}

func (v *NullableAadhaarClaims) Set(val *AadhaarClaims) {
	v.value = val
	v.isSet = true
}

func (v NullableAadhaarClaims) IsSet() bool {
	return v.isSet
}

func (v *NullableAadhaarClaims) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAadhaarClaims(val *AadhaarClaims) *NullableAadhaarClaims {
	return &NullableAadhaarClaims{value: val, isSet: true}
}

func (v NullableAadhaarClaims) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAadhaarClaims) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


