/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the KenyaNidMatch2ProviderOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KenyaNidMatch2ProviderOutput{}

// KenyaNidMatch2ProviderOutput Exposed properties for the `kenya-nid-match-2` Provider which do not directly map to the normalized IdentityData model.
type KenyaNidMatch2ProviderOutput struct {
	// Outcome of the verification of the national ID number.
	NationalIdNumber NullableKenyaNidMatch2NationalIdNumberField `json:"nationalIdNumber,omitempty"`
	// Outcome of the verification of the full name.
	FullName NullableKenyaNidMatch2FullNameField `json:"fullName,omitempty"`
	// Outcome of the verification of the date of birth.
	DateOfBirth NullableKenyaNidMatch2DateOfBirthField `json:"dateOfBirth,omitempty"`
	// Outcome of the verification of the sex.
	Sex NullableKenyaNidMatch2SexField `json:"sex,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _KenyaNidMatch2ProviderOutput KenyaNidMatch2ProviderOutput

// NewKenyaNidMatch2ProviderOutput instantiates a new KenyaNidMatch2ProviderOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKenyaNidMatch2ProviderOutput() *KenyaNidMatch2ProviderOutput {
	this := KenyaNidMatch2ProviderOutput{}
	return &this
}

// NewKenyaNidMatch2ProviderOutputWithDefaults instantiates a new KenyaNidMatch2ProviderOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKenyaNidMatch2ProviderOutputWithDefaults() *KenyaNidMatch2ProviderOutput {
	this := KenyaNidMatch2ProviderOutput{}
	return &this
}

// GetNationalIdNumber returns the NationalIdNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KenyaNidMatch2ProviderOutput) GetNationalIdNumber() KenyaNidMatch2NationalIdNumberField {
	if o == nil || IsNil(o.NationalIdNumber.Get()) {
		var ret KenyaNidMatch2NationalIdNumberField
		return ret
	}
	return *o.NationalIdNumber.Get()
}

// GetNationalIdNumberOk returns a tuple with the NationalIdNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KenyaNidMatch2ProviderOutput) GetNationalIdNumberOk() (*KenyaNidMatch2NationalIdNumberField, bool) {
	if o == nil {
		return nil, false
	}
	return o.NationalIdNumber.Get(), o.NationalIdNumber.IsSet()
}

// HasNationalIdNumber returns a boolean if a field has been set.
func (o *KenyaNidMatch2ProviderOutput) HasNationalIdNumber() bool {
	if o != nil && o.NationalIdNumber.IsSet() {
		return true
	}

	return false
}

// SetNationalIdNumber gets a reference to the given NullableKenyaNidMatch2NationalIdNumberField and assigns it to the NationalIdNumber field.
func (o *KenyaNidMatch2ProviderOutput) SetNationalIdNumber(v KenyaNidMatch2NationalIdNumberField) {
	o.NationalIdNumber.Set(&v)
}
// SetNationalIdNumberNil sets the value for NationalIdNumber to be an explicit nil
func (o *KenyaNidMatch2ProviderOutput) SetNationalIdNumberNil() {
	o.NationalIdNumber.Set(nil)
}

// UnsetNationalIdNumber ensures that no value is present for NationalIdNumber, not even an explicit nil
func (o *KenyaNidMatch2ProviderOutput) UnsetNationalIdNumber() {
	o.NationalIdNumber.Unset()
}

// GetFullName returns the FullName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KenyaNidMatch2ProviderOutput) GetFullName() KenyaNidMatch2FullNameField {
	if o == nil || IsNil(o.FullName.Get()) {
		var ret KenyaNidMatch2FullNameField
		return ret
	}
	return *o.FullName.Get()
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KenyaNidMatch2ProviderOutput) GetFullNameOk() (*KenyaNidMatch2FullNameField, bool) {
	if o == nil {
		return nil, false
	}
	return o.FullName.Get(), o.FullName.IsSet()
}

// HasFullName returns a boolean if a field has been set.
func (o *KenyaNidMatch2ProviderOutput) HasFullName() bool {
	if o != nil && o.FullName.IsSet() {
		return true
	}

	return false
}

// SetFullName gets a reference to the given NullableKenyaNidMatch2FullNameField and assigns it to the FullName field.
func (o *KenyaNidMatch2ProviderOutput) SetFullName(v KenyaNidMatch2FullNameField) {
	o.FullName.Set(&v)
}
// SetFullNameNil sets the value for FullName to be an explicit nil
func (o *KenyaNidMatch2ProviderOutput) SetFullNameNil() {
	o.FullName.Set(nil)
}

// UnsetFullName ensures that no value is present for FullName, not even an explicit nil
func (o *KenyaNidMatch2ProviderOutput) UnsetFullName() {
	o.FullName.Unset()
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KenyaNidMatch2ProviderOutput) GetDateOfBirth() KenyaNidMatch2DateOfBirthField {
	if o == nil || IsNil(o.DateOfBirth.Get()) {
		var ret KenyaNidMatch2DateOfBirthField
		return ret
	}
	return *o.DateOfBirth.Get()
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KenyaNidMatch2ProviderOutput) GetDateOfBirthOk() (*KenyaNidMatch2DateOfBirthField, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfBirth.Get(), o.DateOfBirth.IsSet()
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *KenyaNidMatch2ProviderOutput) HasDateOfBirth() bool {
	if o != nil && o.DateOfBirth.IsSet() {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given NullableKenyaNidMatch2DateOfBirthField and assigns it to the DateOfBirth field.
func (o *KenyaNidMatch2ProviderOutput) SetDateOfBirth(v KenyaNidMatch2DateOfBirthField) {
	o.DateOfBirth.Set(&v)
}
// SetDateOfBirthNil sets the value for DateOfBirth to be an explicit nil
func (o *KenyaNidMatch2ProviderOutput) SetDateOfBirthNil() {
	o.DateOfBirth.Set(nil)
}

// UnsetDateOfBirth ensures that no value is present for DateOfBirth, not even an explicit nil
func (o *KenyaNidMatch2ProviderOutput) UnsetDateOfBirth() {
	o.DateOfBirth.Unset()
}

// GetSex returns the Sex field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KenyaNidMatch2ProviderOutput) GetSex() KenyaNidMatch2SexField {
	if o == nil || IsNil(o.Sex.Get()) {
		var ret KenyaNidMatch2SexField
		return ret
	}
	return *o.Sex.Get()
}

// GetSexOk returns a tuple with the Sex field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KenyaNidMatch2ProviderOutput) GetSexOk() (*KenyaNidMatch2SexField, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sex.Get(), o.Sex.IsSet()
}

// HasSex returns a boolean if a field has been set.
func (o *KenyaNidMatch2ProviderOutput) HasSex() bool {
	if o != nil && o.Sex.IsSet() {
		return true
	}

	return false
}

// SetSex gets a reference to the given NullableKenyaNidMatch2SexField and assigns it to the Sex field.
func (o *KenyaNidMatch2ProviderOutput) SetSex(v KenyaNidMatch2SexField) {
	o.Sex.Set(&v)
}
// SetSexNil sets the value for Sex to be an explicit nil
func (o *KenyaNidMatch2ProviderOutput) SetSexNil() {
	o.Sex.Set(nil)
}

// UnsetSex ensures that no value is present for Sex, not even an explicit nil
func (o *KenyaNidMatch2ProviderOutput) UnsetSex() {
	o.Sex.Unset()
}

func (o KenyaNidMatch2ProviderOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KenyaNidMatch2ProviderOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.NationalIdNumber.IsSet() {
		toSerialize["nationalIdNumber"] = o.NationalIdNumber.Get()
	}
	if o.FullName.IsSet() {
		toSerialize["fullName"] = o.FullName.Get()
	}
	if o.DateOfBirth.IsSet() {
		toSerialize["dateOfBirth"] = o.DateOfBirth.Get()
	}
	if o.Sex.IsSet() {
		toSerialize["sex"] = o.Sex.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KenyaNidMatch2ProviderOutput) UnmarshalJSON(data []byte) (err error) {
	varKenyaNidMatch2ProviderOutput := _KenyaNidMatch2ProviderOutput{}

	err = json.Unmarshal(data, &varKenyaNidMatch2ProviderOutput)

	if err != nil {
		return err
	}

	*o = KenyaNidMatch2ProviderOutput(varKenyaNidMatch2ProviderOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "nationalIdNumber")
		delete(additionalProperties, "fullName")
		delete(additionalProperties, "dateOfBirth")
		delete(additionalProperties, "sex")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKenyaNidMatch2ProviderOutput struct {
	value *KenyaNidMatch2ProviderOutput
	isSet bool
}

func (v NullableKenyaNidMatch2ProviderOutput) Get() *KenyaNidMatch2ProviderOutput {
	return v.value
}

func (v *NullableKenyaNidMatch2ProviderOutput) Set(val *KenyaNidMatch2ProviderOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableKenyaNidMatch2ProviderOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableKenyaNidMatch2ProviderOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKenyaNidMatch2ProviderOutput(val *KenyaNidMatch2ProviderOutput) *NullableKenyaNidMatch2ProviderOutput {
	return &NullableKenyaNidMatch2ProviderOutput{value: val, isSet: true}
}

func (v NullableKenyaNidMatch2ProviderOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKenyaNidMatch2ProviderOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


