/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
	"fmt"
)

// checks if the UgandaNidMatch2SecondaryIdNumberField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UgandaNidMatch2SecondaryIdNumberField{}

// UgandaNidMatch2SecondaryIdNumberField struct for UgandaNidMatch2SecondaryIdNumberField
type UgandaNidMatch2SecondaryIdNumberField struct {
	// The card number on the national ID document, distinct from the National ID number.              Format: - 9 numeric digits - There is no publicly documented encoding scheme for encoding personal information in the card number - No check digit or algorithm has been publicly documented by NIRA
	InputValue string `json:"inputValue"`
	// The outcome of comparing the submitted card number with NIRA database.              Possible values: - Exact Match - No Match - Not Returned
	Outcome string `json:"outcome"`
	AdditionalProperties map[string]interface{}
}

type _UgandaNidMatch2SecondaryIdNumberField UgandaNidMatch2SecondaryIdNumberField

// NewUgandaNidMatch2SecondaryIdNumberField instantiates a new UgandaNidMatch2SecondaryIdNumberField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUgandaNidMatch2SecondaryIdNumberField(inputValue string, outcome string) *UgandaNidMatch2SecondaryIdNumberField {
	this := UgandaNidMatch2SecondaryIdNumberField{}
	this.InputValue = inputValue
	this.Outcome = outcome
	return &this
}

// NewUgandaNidMatch2SecondaryIdNumberFieldWithDefaults instantiates a new UgandaNidMatch2SecondaryIdNumberField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUgandaNidMatch2SecondaryIdNumberFieldWithDefaults() *UgandaNidMatch2SecondaryIdNumberField {
	this := UgandaNidMatch2SecondaryIdNumberField{}
	return &this
}

// GetInputValue returns the InputValue field value
func (o *UgandaNidMatch2SecondaryIdNumberField) GetInputValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InputValue
}

// GetInputValueOk returns a tuple with the InputValue field value
// and a boolean to check if the value has been set.
func (o *UgandaNidMatch2SecondaryIdNumberField) GetInputValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InputValue, true
}

// SetInputValue sets field value
func (o *UgandaNidMatch2SecondaryIdNumberField) SetInputValue(v string) {
	o.InputValue = v
}

// GetOutcome returns the Outcome field value
func (o *UgandaNidMatch2SecondaryIdNumberField) GetOutcome() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value
// and a boolean to check if the value has been set.
func (o *UgandaNidMatch2SecondaryIdNumberField) GetOutcomeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outcome, true
}

// SetOutcome sets field value
func (o *UgandaNidMatch2SecondaryIdNumberField) SetOutcome(v string) {
	o.Outcome = v
}

func (o UgandaNidMatch2SecondaryIdNumberField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UgandaNidMatch2SecondaryIdNumberField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["inputValue"] = o.InputValue
	toSerialize["outcome"] = o.Outcome

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UgandaNidMatch2SecondaryIdNumberField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"inputValue",
		"outcome",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUgandaNidMatch2SecondaryIdNumberField := _UgandaNidMatch2SecondaryIdNumberField{}

	err = json.Unmarshal(data, &varUgandaNidMatch2SecondaryIdNumberField)

	if err != nil {
		return err
	}

	*o = UgandaNidMatch2SecondaryIdNumberField(varUgandaNidMatch2SecondaryIdNumberField)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "inputValue")
		delete(additionalProperties, "outcome")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUgandaNidMatch2SecondaryIdNumberField struct {
	value *UgandaNidMatch2SecondaryIdNumberField
	isSet bool
}

func (v NullableUgandaNidMatch2SecondaryIdNumberField) Get() *UgandaNidMatch2SecondaryIdNumberField {
	return v.value
}

func (v *NullableUgandaNidMatch2SecondaryIdNumberField) Set(val *UgandaNidMatch2SecondaryIdNumberField) {
	v.value = val
	v.isSet = true
}

func (v NullableUgandaNidMatch2SecondaryIdNumberField) IsSet() bool {
	return v.isSet
}

func (v *NullableUgandaNidMatch2SecondaryIdNumberField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUgandaNidMatch2SecondaryIdNumberField(val *UgandaNidMatch2SecondaryIdNumberField) *NullableUgandaNidMatch2SecondaryIdNumberField {
	return &NullableUgandaNidMatch2SecondaryIdNumberField{value: val, isSet: true}
}

func (v NullableUgandaNidMatch2SecondaryIdNumberField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUgandaNidMatch2SecondaryIdNumberField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


