/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
	"fmt"
)

// checks if the NetherlandsIdinAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetherlandsIdinAddress{}

// NetherlandsIdinAddress struct for NetherlandsIdinAddress
type NetherlandsIdinAddress struct {
	// Street name of the individual's address.
	Street string `json:"street"`
	// House number of the individual's address.
	HouseNumber string `json:"houseNumber"`
	// Postal code of the individual's address.              A postal code in The Netherlands is a 4-digit number and two letters.
	PostalCode string `json:"postalCode"`
	// City of the individual's address.
	City string `json:"city"`
	// Country code of the individual's address in ISO 3166-1 alpha-2 format.
	CountryCode string `json:"countryCode"`
	AdditionalProperties map[string]interface{}
}

type _NetherlandsIdinAddress NetherlandsIdinAddress

// NewNetherlandsIdinAddress instantiates a new NetherlandsIdinAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetherlandsIdinAddress(street string, houseNumber string, postalCode string, city string, countryCode string) *NetherlandsIdinAddress {
	this := NetherlandsIdinAddress{}
	this.Street = street
	this.HouseNumber = houseNumber
	this.PostalCode = postalCode
	this.City = city
	this.CountryCode = countryCode
	return &this
}

// NewNetherlandsIdinAddressWithDefaults instantiates a new NetherlandsIdinAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetherlandsIdinAddressWithDefaults() *NetherlandsIdinAddress {
	this := NetherlandsIdinAddress{}
	return &this
}

// GetStreet returns the Street field value
func (o *NetherlandsIdinAddress) GetStreet() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Street
}

// GetStreetOk returns a tuple with the Street field value
// and a boolean to check if the value has been set.
func (o *NetherlandsIdinAddress) GetStreetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Street, true
}

// SetStreet sets field value
func (o *NetherlandsIdinAddress) SetStreet(v string) {
	o.Street = v
}

// GetHouseNumber returns the HouseNumber field value
func (o *NetherlandsIdinAddress) GetHouseNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HouseNumber
}

// GetHouseNumberOk returns a tuple with the HouseNumber field value
// and a boolean to check if the value has been set.
func (o *NetherlandsIdinAddress) GetHouseNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HouseNumber, true
}

// SetHouseNumber sets field value
func (o *NetherlandsIdinAddress) SetHouseNumber(v string) {
	o.HouseNumber = v
}

// GetPostalCode returns the PostalCode field value
func (o *NetherlandsIdinAddress) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *NetherlandsIdinAddress) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *NetherlandsIdinAddress) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetCity returns the City field value
func (o *NetherlandsIdinAddress) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *NetherlandsIdinAddress) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *NetherlandsIdinAddress) SetCity(v string) {
	o.City = v
}

// GetCountryCode returns the CountryCode field value
func (o *NetherlandsIdinAddress) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *NetherlandsIdinAddress) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *NetherlandsIdinAddress) SetCountryCode(v string) {
	o.CountryCode = v
}

func (o NetherlandsIdinAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetherlandsIdinAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["street"] = o.Street
	toSerialize["houseNumber"] = o.HouseNumber
	toSerialize["postalCode"] = o.PostalCode
	toSerialize["city"] = o.City
	toSerialize["countryCode"] = o.CountryCode

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NetherlandsIdinAddress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"street",
		"houseNumber",
		"postalCode",
		"city",
		"countryCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetherlandsIdinAddress := _NetherlandsIdinAddress{}

	err = json.Unmarshal(data, &varNetherlandsIdinAddress)

	if err != nil {
		return err
	}

	*o = NetherlandsIdinAddress(varNetherlandsIdinAddress)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "street")
		delete(additionalProperties, "houseNumber")
		delete(additionalProperties, "postalCode")
		delete(additionalProperties, "city")
		delete(additionalProperties, "countryCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNetherlandsIdinAddress struct {
	value *NetherlandsIdinAddress
	isSet bool
}

func (v NullableNetherlandsIdinAddress) Get() *NetherlandsIdinAddress {
	return v.value
}

func (v *NullableNetherlandsIdinAddress) Set(val *NetherlandsIdinAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableNetherlandsIdinAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableNetherlandsIdinAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetherlandsIdinAddress(val *NetherlandsIdinAddress) *NullableNetherlandsIdinAddress {
	return &NullableNetherlandsIdinAddress{value: val, isSet: true}
}

func (v NullableNetherlandsIdinAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetherlandsIdinAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


