/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the ChinaResidentIdMatchOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChinaResidentIdMatchOutput{}

// ChinaResidentIdMatchOutput Exposed properties for the `china-resident-id-match` Provider which do not directly map to the normalized IdentityData model.
type ChinaResidentIdMatchOutput struct {
	// The fullname of the individual in Chinese.
	FullName NullableString `json:"fullName,omitempty"`
	// The birthdate of the individual.
	DateOfBirth NullableString `json:"dateOfBirth,omitempty"`
	// The Resident ID number from the People's Republic of China (PRC) ID card.              The Resident ID number is an 18-digit number follows the format (AAAAAAYYYYMMDDXXX@): - Six digits (AAAAAA) are the area code of where the person was born or the area of first issuance for those who were born before the resident system was created. - Eight digits are the birthdate of the individual in YYYYMMDD format - Three digits are the order code assigned to individual. Males are assigned odd numbers and females even numbers. - Final digit is the checksum confirming the validity of the ID number's first 17 digits using ISO 7064:1983, MOD 11-2.
	ResidentIdNumber NullableString `json:"residentIdNumber,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ChinaResidentIdMatchOutput ChinaResidentIdMatchOutput

// NewChinaResidentIdMatchOutput instantiates a new ChinaResidentIdMatchOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChinaResidentIdMatchOutput() *ChinaResidentIdMatchOutput {
	this := ChinaResidentIdMatchOutput{}
	return &this
}

// NewChinaResidentIdMatchOutputWithDefaults instantiates a new ChinaResidentIdMatchOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChinaResidentIdMatchOutputWithDefaults() *ChinaResidentIdMatchOutput {
	this := ChinaResidentIdMatchOutput{}
	return &this
}

// GetFullName returns the FullName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChinaResidentIdMatchOutput) GetFullName() string {
	if o == nil || IsNil(o.FullName.Get()) {
		var ret string
		return ret
	}
	return *o.FullName.Get()
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChinaResidentIdMatchOutput) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FullName.Get(), o.FullName.IsSet()
}

// HasFullName returns a boolean if a field has been set.
func (o *ChinaResidentIdMatchOutput) HasFullName() bool {
	if o != nil && o.FullName.IsSet() {
		return true
	}

	return false
}

// SetFullName gets a reference to the given NullableString and assigns it to the FullName field.
func (o *ChinaResidentIdMatchOutput) SetFullName(v string) {
	o.FullName.Set(&v)
}
// SetFullNameNil sets the value for FullName to be an explicit nil
func (o *ChinaResidentIdMatchOutput) SetFullNameNil() {
	o.FullName.Set(nil)
}

// UnsetFullName ensures that no value is present for FullName, not even an explicit nil
func (o *ChinaResidentIdMatchOutput) UnsetFullName() {
	o.FullName.Unset()
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChinaResidentIdMatchOutput) GetDateOfBirth() string {
	if o == nil || IsNil(o.DateOfBirth.Get()) {
		var ret string
		return ret
	}
	return *o.DateOfBirth.Get()
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChinaResidentIdMatchOutput) GetDateOfBirthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfBirth.Get(), o.DateOfBirth.IsSet()
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *ChinaResidentIdMatchOutput) HasDateOfBirth() bool {
	if o != nil && o.DateOfBirth.IsSet() {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given NullableString and assigns it to the DateOfBirth field.
func (o *ChinaResidentIdMatchOutput) SetDateOfBirth(v string) {
	o.DateOfBirth.Set(&v)
}
// SetDateOfBirthNil sets the value for DateOfBirth to be an explicit nil
func (o *ChinaResidentIdMatchOutput) SetDateOfBirthNil() {
	o.DateOfBirth.Set(nil)
}

// UnsetDateOfBirth ensures that no value is present for DateOfBirth, not even an explicit nil
func (o *ChinaResidentIdMatchOutput) UnsetDateOfBirth() {
	o.DateOfBirth.Unset()
}

// GetResidentIdNumber returns the ResidentIdNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChinaResidentIdMatchOutput) GetResidentIdNumber() string {
	if o == nil || IsNil(o.ResidentIdNumber.Get()) {
		var ret string
		return ret
	}
	return *o.ResidentIdNumber.Get()
}

// GetResidentIdNumberOk returns a tuple with the ResidentIdNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChinaResidentIdMatchOutput) GetResidentIdNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResidentIdNumber.Get(), o.ResidentIdNumber.IsSet()
}

// HasResidentIdNumber returns a boolean if a field has been set.
func (o *ChinaResidentIdMatchOutput) HasResidentIdNumber() bool {
	if o != nil && o.ResidentIdNumber.IsSet() {
		return true
	}

	return false
}

// SetResidentIdNumber gets a reference to the given NullableString and assigns it to the ResidentIdNumber field.
func (o *ChinaResidentIdMatchOutput) SetResidentIdNumber(v string) {
	o.ResidentIdNumber.Set(&v)
}
// SetResidentIdNumberNil sets the value for ResidentIdNumber to be an explicit nil
func (o *ChinaResidentIdMatchOutput) SetResidentIdNumberNil() {
	o.ResidentIdNumber.Set(nil)
}

// UnsetResidentIdNumber ensures that no value is present for ResidentIdNumber, not even an explicit nil
func (o *ChinaResidentIdMatchOutput) UnsetResidentIdNumber() {
	o.ResidentIdNumber.Unset()
}

func (o ChinaResidentIdMatchOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChinaResidentIdMatchOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.FullName.IsSet() {
		toSerialize["fullName"] = o.FullName.Get()
	}
	if o.DateOfBirth.IsSet() {
		toSerialize["dateOfBirth"] = o.DateOfBirth.Get()
	}
	if o.ResidentIdNumber.IsSet() {
		toSerialize["residentIdNumber"] = o.ResidentIdNumber.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChinaResidentIdMatchOutput) UnmarshalJSON(data []byte) (err error) {
	varChinaResidentIdMatchOutput := _ChinaResidentIdMatchOutput{}

	err = json.Unmarshal(data, &varChinaResidentIdMatchOutput)

	if err != nil {
		return err
	}

	*o = ChinaResidentIdMatchOutput(varChinaResidentIdMatchOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fullName")
		delete(additionalProperties, "dateOfBirth")
		delete(additionalProperties, "residentIdNumber")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChinaResidentIdMatchOutput struct {
	value *ChinaResidentIdMatchOutput
	isSet bool
}

func (v NullableChinaResidentIdMatchOutput) Get() *ChinaResidentIdMatchOutput {
	return v.value
}

func (v *NullableChinaResidentIdMatchOutput) Set(val *ChinaResidentIdMatchOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableChinaResidentIdMatchOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableChinaResidentIdMatchOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChinaResidentIdMatchOutput(val *ChinaResidentIdMatchOutput) *NullableChinaResidentIdMatchOutput {
	return &NullableChinaResidentIdMatchOutput{value: val, isSet: true}
}

func (v NullableChinaResidentIdMatchOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChinaResidentIdMatchOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


