/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
	"fmt"
)

// checks if the SpidBillingInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpidBillingInformation{}

// SpidBillingInformation Billing information for a SPID Verification.
type SpidBillingInformation struct {
	// Whether this SPID verification has resulted in a billable event.
	IsBillable bool `json:"isBillable"`
	// The billable verification type for this SPID verification.              Possible values: \"Authentication\" | \"Registration\"
	VerificationType string `json:"verificationType"`
	// The billable verification level for this SPID verification.              Possible values: 1 | 2 | 3
	VerificationLevel int32 `json:"verificationLevel"`
	AdditionalProperties map[string]interface{}
}

type _SpidBillingInformation SpidBillingInformation

// NewSpidBillingInformation instantiates a new SpidBillingInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpidBillingInformation(isBillable bool, verificationType string, verificationLevel int32) *SpidBillingInformation {
	this := SpidBillingInformation{}
	this.IsBillable = isBillable
	this.VerificationType = verificationType
	this.VerificationLevel = verificationLevel
	return &this
}

// NewSpidBillingInformationWithDefaults instantiates a new SpidBillingInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpidBillingInformationWithDefaults() *SpidBillingInformation {
	this := SpidBillingInformation{}
	return &this
}

// GetIsBillable returns the IsBillable field value
func (o *SpidBillingInformation) GetIsBillable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsBillable
}

// GetIsBillableOk returns a tuple with the IsBillable field value
// and a boolean to check if the value has been set.
func (o *SpidBillingInformation) GetIsBillableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsBillable, true
}

// SetIsBillable sets field value
func (o *SpidBillingInformation) SetIsBillable(v bool) {
	o.IsBillable = v
}

// GetVerificationType returns the VerificationType field value
func (o *SpidBillingInformation) GetVerificationType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerificationType
}

// GetVerificationTypeOk returns a tuple with the VerificationType field value
// and a boolean to check if the value has been set.
func (o *SpidBillingInformation) GetVerificationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationType, true
}

// SetVerificationType sets field value
func (o *SpidBillingInformation) SetVerificationType(v string) {
	o.VerificationType = v
}

// GetVerificationLevel returns the VerificationLevel field value
func (o *SpidBillingInformation) GetVerificationLevel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VerificationLevel
}

// GetVerificationLevelOk returns a tuple with the VerificationLevel field value
// and a boolean to check if the value has been set.
func (o *SpidBillingInformation) GetVerificationLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationLevel, true
}

// SetVerificationLevel sets field value
func (o *SpidBillingInformation) SetVerificationLevel(v int32) {
	o.VerificationLevel = v
}

func (o SpidBillingInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpidBillingInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["isBillable"] = o.IsBillable
	toSerialize["verificationType"] = o.VerificationType
	toSerialize["verificationLevel"] = o.VerificationLevel

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SpidBillingInformation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isBillable",
		"verificationType",
		"verificationLevel",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpidBillingInformation := _SpidBillingInformation{}

	err = json.Unmarshal(data, &varSpidBillingInformation)

	if err != nil {
		return err
	}

	*o = SpidBillingInformation(varSpidBillingInformation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "isBillable")
		delete(additionalProperties, "verificationType")
		delete(additionalProperties, "verificationLevel")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSpidBillingInformation struct {
	value *SpidBillingInformation
	isSet bool
}

func (v NullableSpidBillingInformation) Get() *SpidBillingInformation {
	return v.value
}

func (v *NullableSpidBillingInformation) Set(val *SpidBillingInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableSpidBillingInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableSpidBillingInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpidBillingInformation(val *SpidBillingInformation) *NullableSpidBillingInformation {
	return &NullableSpidBillingInformation{value: val, isSet: true}
}

func (v NullableSpidBillingInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpidBillingInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


