/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the PortugalIdCardProviderOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PortugalIdCardProviderOutput{}

// PortugalIdCardProviderOutput Exposed properties for the `a-pt-id-login` Provider which do not directly map to the normalized IdentityData model.
type PortugalIdCardProviderOutput struct {
	// The first name of the verified individual
	FirstName NullableString `json:"firstName,omitempty"`
	// The last name of the verified individual
	LastName NullableString `json:"lastName,omitempty"`
	// The date of birth of the verified individual
	DateOfBirth NullableString `json:"dateOfBirth,omitempty"`
	// The 8-digit Portuguese Civil Identification Number (número de identificação civil) of the verified individual.
	CivilIdentificationNumber NullableString `json:"civilIdentificationNumber,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PortugalIdCardProviderOutput PortugalIdCardProviderOutput

// NewPortugalIdCardProviderOutput instantiates a new PortugalIdCardProviderOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPortugalIdCardProviderOutput() *PortugalIdCardProviderOutput {
	this := PortugalIdCardProviderOutput{}
	return &this
}

// NewPortugalIdCardProviderOutputWithDefaults instantiates a new PortugalIdCardProviderOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPortugalIdCardProviderOutputWithDefaults() *PortugalIdCardProviderOutput {
	this := PortugalIdCardProviderOutput{}
	return &this
}

// GetFirstName returns the FirstName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PortugalIdCardProviderOutput) GetFirstName() string {
	if o == nil || IsNil(o.FirstName.Get()) {
		var ret string
		return ret
	}
	return *o.FirstName.Get()
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PortugalIdCardProviderOutput) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirstName.Get(), o.FirstName.IsSet()
}

// HasFirstName returns a boolean if a field has been set.
func (o *PortugalIdCardProviderOutput) HasFirstName() bool {
	if o != nil && o.FirstName.IsSet() {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given NullableString and assigns it to the FirstName field.
func (o *PortugalIdCardProviderOutput) SetFirstName(v string) {
	o.FirstName.Set(&v)
}
// SetFirstNameNil sets the value for FirstName to be an explicit nil
func (o *PortugalIdCardProviderOutput) SetFirstNameNil() {
	o.FirstName.Set(nil)
}

// UnsetFirstName ensures that no value is present for FirstName, not even an explicit nil
func (o *PortugalIdCardProviderOutput) UnsetFirstName() {
	o.FirstName.Unset()
}

// GetLastName returns the LastName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PortugalIdCardProviderOutput) GetLastName() string {
	if o == nil || IsNil(o.LastName.Get()) {
		var ret string
		return ret
	}
	return *o.LastName.Get()
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PortugalIdCardProviderOutput) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastName.Get(), o.LastName.IsSet()
}

// HasLastName returns a boolean if a field has been set.
func (o *PortugalIdCardProviderOutput) HasLastName() bool {
	if o != nil && o.LastName.IsSet() {
		return true
	}

	return false
}

// SetLastName gets a reference to the given NullableString and assigns it to the LastName field.
func (o *PortugalIdCardProviderOutput) SetLastName(v string) {
	o.LastName.Set(&v)
}
// SetLastNameNil sets the value for LastName to be an explicit nil
func (o *PortugalIdCardProviderOutput) SetLastNameNil() {
	o.LastName.Set(nil)
}

// UnsetLastName ensures that no value is present for LastName, not even an explicit nil
func (o *PortugalIdCardProviderOutput) UnsetLastName() {
	o.LastName.Unset()
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PortugalIdCardProviderOutput) GetDateOfBirth() string {
	if o == nil || IsNil(o.DateOfBirth.Get()) {
		var ret string
		return ret
	}
	return *o.DateOfBirth.Get()
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PortugalIdCardProviderOutput) GetDateOfBirthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DateOfBirth.Get(), o.DateOfBirth.IsSet()
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *PortugalIdCardProviderOutput) HasDateOfBirth() bool {
	if o != nil && o.DateOfBirth.IsSet() {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given NullableString and assigns it to the DateOfBirth field.
func (o *PortugalIdCardProviderOutput) SetDateOfBirth(v string) {
	o.DateOfBirth.Set(&v)
}
// SetDateOfBirthNil sets the value for DateOfBirth to be an explicit nil
func (o *PortugalIdCardProviderOutput) SetDateOfBirthNil() {
	o.DateOfBirth.Set(nil)
}

// UnsetDateOfBirth ensures that no value is present for DateOfBirth, not even an explicit nil
func (o *PortugalIdCardProviderOutput) UnsetDateOfBirth() {
	o.DateOfBirth.Unset()
}

// GetCivilIdentificationNumber returns the CivilIdentificationNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PortugalIdCardProviderOutput) GetCivilIdentificationNumber() string {
	if o == nil || IsNil(o.CivilIdentificationNumber.Get()) {
		var ret string
		return ret
	}
	return *o.CivilIdentificationNumber.Get()
}

// GetCivilIdentificationNumberOk returns a tuple with the CivilIdentificationNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PortugalIdCardProviderOutput) GetCivilIdentificationNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CivilIdentificationNumber.Get(), o.CivilIdentificationNumber.IsSet()
}

// HasCivilIdentificationNumber returns a boolean if a field has been set.
func (o *PortugalIdCardProviderOutput) HasCivilIdentificationNumber() bool {
	if o != nil && o.CivilIdentificationNumber.IsSet() {
		return true
	}

	return false
}

// SetCivilIdentificationNumber gets a reference to the given NullableString and assigns it to the CivilIdentificationNumber field.
func (o *PortugalIdCardProviderOutput) SetCivilIdentificationNumber(v string) {
	o.CivilIdentificationNumber.Set(&v)
}
// SetCivilIdentificationNumberNil sets the value for CivilIdentificationNumber to be an explicit nil
func (o *PortugalIdCardProviderOutput) SetCivilIdentificationNumberNil() {
	o.CivilIdentificationNumber.Set(nil)
}

// UnsetCivilIdentificationNumber ensures that no value is present for CivilIdentificationNumber, not even an explicit nil
func (o *PortugalIdCardProviderOutput) UnsetCivilIdentificationNumber() {
	o.CivilIdentificationNumber.Unset()
}

func (o PortugalIdCardProviderOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PortugalIdCardProviderOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.FirstName.IsSet() {
		toSerialize["firstName"] = o.FirstName.Get()
	}
	if o.LastName.IsSet() {
		toSerialize["lastName"] = o.LastName.Get()
	}
	if o.DateOfBirth.IsSet() {
		toSerialize["dateOfBirth"] = o.DateOfBirth.Get()
	}
	if o.CivilIdentificationNumber.IsSet() {
		toSerialize["civilIdentificationNumber"] = o.CivilIdentificationNumber.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PortugalIdCardProviderOutput) UnmarshalJSON(data []byte) (err error) {
	varPortugalIdCardProviderOutput := _PortugalIdCardProviderOutput{}

	err = json.Unmarshal(data, &varPortugalIdCardProviderOutput)

	if err != nil {
		return err
	}

	*o = PortugalIdCardProviderOutput(varPortugalIdCardProviderOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "firstName")
		delete(additionalProperties, "lastName")
		delete(additionalProperties, "dateOfBirth")
		delete(additionalProperties, "civilIdentificationNumber")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePortugalIdCardProviderOutput struct {
	value *PortugalIdCardProviderOutput
	isSet bool
}

func (v NullablePortugalIdCardProviderOutput) Get() *PortugalIdCardProviderOutput {
	return v.value
}

func (v *NullablePortugalIdCardProviderOutput) Set(val *PortugalIdCardProviderOutput) {
	v.value = val
	v.isSet = true
}

func (v NullablePortugalIdCardProviderOutput) IsSet() bool {
	return v.isSet
}

func (v *NullablePortugalIdCardProviderOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePortugalIdCardProviderOutput(val *PortugalIdCardProviderOutput) *NullablePortugalIdCardProviderOutput {
	return &NullablePortugalIdCardProviderOutput{value: val, isSet: true}
}

func (v NullablePortugalIdCardProviderOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePortugalIdCardProviderOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


