/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the IdemiaPreviewProviderAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdemiaPreviewProviderAddress{}

// IdemiaPreviewProviderAddress struct for IdemiaPreviewProviderAddress
type IdemiaPreviewProviderAddress struct {
	// The formatted address.
	Formatted NullableString `json:"formatted,omitempty"`
	// The street address.
	StreetAddress NullableString `json:"streetAddress,omitempty"`
	// The city or locality.
	Locality NullableString `json:"locality,omitempty"`
	// The state, province, region, or other subdivision.
	Region NullableString `json:"region,omitempty"`
	// The postal code.
	PostalCode NullableString `json:"postalCode,omitempty"`
	// The country.
	Country NullableString `json:"country,omitempty"`
	// The room number.
	RoomNumber NullableString `json:"roomNumber,omitempty"`
	// The post office box.
	PostOfficeBox NullableString `json:"postOfficeBox,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IdemiaPreviewProviderAddress IdemiaPreviewProviderAddress

// NewIdemiaPreviewProviderAddress instantiates a new IdemiaPreviewProviderAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdemiaPreviewProviderAddress() *IdemiaPreviewProviderAddress {
	this := IdemiaPreviewProviderAddress{}
	return &this
}

// NewIdemiaPreviewProviderAddressWithDefaults instantiates a new IdemiaPreviewProviderAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdemiaPreviewProviderAddressWithDefaults() *IdemiaPreviewProviderAddress {
	this := IdemiaPreviewProviderAddress{}
	return &this
}

// GetFormatted returns the Formatted field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IdemiaPreviewProviderAddress) GetFormatted() string {
	if o == nil || IsNil(o.Formatted.Get()) {
		var ret string
		return ret
	}
	return *o.Formatted.Get()
}

// GetFormattedOk returns a tuple with the Formatted field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdemiaPreviewProviderAddress) GetFormattedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Formatted.Get(), o.Formatted.IsSet()
}

// HasFormatted returns a boolean if a field has been set.
func (o *IdemiaPreviewProviderAddress) HasFormatted() bool {
	if o != nil && o.Formatted.IsSet() {
		return true
	}

	return false
}

// SetFormatted gets a reference to the given NullableString and assigns it to the Formatted field.
func (o *IdemiaPreviewProviderAddress) SetFormatted(v string) {
	o.Formatted.Set(&v)
}
// SetFormattedNil sets the value for Formatted to be an explicit nil
func (o *IdemiaPreviewProviderAddress) SetFormattedNil() {
	o.Formatted.Set(nil)
}

// UnsetFormatted ensures that no value is present for Formatted, not even an explicit nil
func (o *IdemiaPreviewProviderAddress) UnsetFormatted() {
	o.Formatted.Unset()
}

// GetStreetAddress returns the StreetAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IdemiaPreviewProviderAddress) GetStreetAddress() string {
	if o == nil || IsNil(o.StreetAddress.Get()) {
		var ret string
		return ret
	}
	return *o.StreetAddress.Get()
}

// GetStreetAddressOk returns a tuple with the StreetAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdemiaPreviewProviderAddress) GetStreetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StreetAddress.Get(), o.StreetAddress.IsSet()
}

// HasStreetAddress returns a boolean if a field has been set.
func (o *IdemiaPreviewProviderAddress) HasStreetAddress() bool {
	if o != nil && o.StreetAddress.IsSet() {
		return true
	}

	return false
}

// SetStreetAddress gets a reference to the given NullableString and assigns it to the StreetAddress field.
func (o *IdemiaPreviewProviderAddress) SetStreetAddress(v string) {
	o.StreetAddress.Set(&v)
}
// SetStreetAddressNil sets the value for StreetAddress to be an explicit nil
func (o *IdemiaPreviewProviderAddress) SetStreetAddressNil() {
	o.StreetAddress.Set(nil)
}

// UnsetStreetAddress ensures that no value is present for StreetAddress, not even an explicit nil
func (o *IdemiaPreviewProviderAddress) UnsetStreetAddress() {
	o.StreetAddress.Unset()
}

// GetLocality returns the Locality field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IdemiaPreviewProviderAddress) GetLocality() string {
	if o == nil || IsNil(o.Locality.Get()) {
		var ret string
		return ret
	}
	return *o.Locality.Get()
}

// GetLocalityOk returns a tuple with the Locality field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdemiaPreviewProviderAddress) GetLocalityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locality.Get(), o.Locality.IsSet()
}

// HasLocality returns a boolean if a field has been set.
func (o *IdemiaPreviewProviderAddress) HasLocality() bool {
	if o != nil && o.Locality.IsSet() {
		return true
	}

	return false
}

// SetLocality gets a reference to the given NullableString and assigns it to the Locality field.
func (o *IdemiaPreviewProviderAddress) SetLocality(v string) {
	o.Locality.Set(&v)
}
// SetLocalityNil sets the value for Locality to be an explicit nil
func (o *IdemiaPreviewProviderAddress) SetLocalityNil() {
	o.Locality.Set(nil)
}

// UnsetLocality ensures that no value is present for Locality, not even an explicit nil
func (o *IdemiaPreviewProviderAddress) UnsetLocality() {
	o.Locality.Unset()
}

// GetRegion returns the Region field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IdemiaPreviewProviderAddress) GetRegion() string {
	if o == nil || IsNil(o.Region.Get()) {
		var ret string
		return ret
	}
	return *o.Region.Get()
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdemiaPreviewProviderAddress) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Region.Get(), o.Region.IsSet()
}

// HasRegion returns a boolean if a field has been set.
func (o *IdemiaPreviewProviderAddress) HasRegion() bool {
	if o != nil && o.Region.IsSet() {
		return true
	}

	return false
}

// SetRegion gets a reference to the given NullableString and assigns it to the Region field.
func (o *IdemiaPreviewProviderAddress) SetRegion(v string) {
	o.Region.Set(&v)
}
// SetRegionNil sets the value for Region to be an explicit nil
func (o *IdemiaPreviewProviderAddress) SetRegionNil() {
	o.Region.Set(nil)
}

// UnsetRegion ensures that no value is present for Region, not even an explicit nil
func (o *IdemiaPreviewProviderAddress) UnsetRegion() {
	o.Region.Unset()
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IdemiaPreviewProviderAddress) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode.Get()) {
		var ret string
		return ret
	}
	return *o.PostalCode.Get()
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdemiaPreviewProviderAddress) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PostalCode.Get(), o.PostalCode.IsSet()
}

// HasPostalCode returns a boolean if a field has been set.
func (o *IdemiaPreviewProviderAddress) HasPostalCode() bool {
	if o != nil && o.PostalCode.IsSet() {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given NullableString and assigns it to the PostalCode field.
func (o *IdemiaPreviewProviderAddress) SetPostalCode(v string) {
	o.PostalCode.Set(&v)
}
// SetPostalCodeNil sets the value for PostalCode to be an explicit nil
func (o *IdemiaPreviewProviderAddress) SetPostalCodeNil() {
	o.PostalCode.Set(nil)
}

// UnsetPostalCode ensures that no value is present for PostalCode, not even an explicit nil
func (o *IdemiaPreviewProviderAddress) UnsetPostalCode() {
	o.PostalCode.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IdemiaPreviewProviderAddress) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdemiaPreviewProviderAddress) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *IdemiaPreviewProviderAddress) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *IdemiaPreviewProviderAddress) SetCountry(v string) {
	o.Country.Set(&v)
}
// SetCountryNil sets the value for Country to be an explicit nil
func (o *IdemiaPreviewProviderAddress) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *IdemiaPreviewProviderAddress) UnsetCountry() {
	o.Country.Unset()
}

// GetRoomNumber returns the RoomNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IdemiaPreviewProviderAddress) GetRoomNumber() string {
	if o == nil || IsNil(o.RoomNumber.Get()) {
		var ret string
		return ret
	}
	return *o.RoomNumber.Get()
}

// GetRoomNumberOk returns a tuple with the RoomNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdemiaPreviewProviderAddress) GetRoomNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoomNumber.Get(), o.RoomNumber.IsSet()
}

// HasRoomNumber returns a boolean if a field has been set.
func (o *IdemiaPreviewProviderAddress) HasRoomNumber() bool {
	if o != nil && o.RoomNumber.IsSet() {
		return true
	}

	return false
}

// SetRoomNumber gets a reference to the given NullableString and assigns it to the RoomNumber field.
func (o *IdemiaPreviewProviderAddress) SetRoomNumber(v string) {
	o.RoomNumber.Set(&v)
}
// SetRoomNumberNil sets the value for RoomNumber to be an explicit nil
func (o *IdemiaPreviewProviderAddress) SetRoomNumberNil() {
	o.RoomNumber.Set(nil)
}

// UnsetRoomNumber ensures that no value is present for RoomNumber, not even an explicit nil
func (o *IdemiaPreviewProviderAddress) UnsetRoomNumber() {
	o.RoomNumber.Unset()
}

// GetPostOfficeBox returns the PostOfficeBox field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IdemiaPreviewProviderAddress) GetPostOfficeBox() string {
	if o == nil || IsNil(o.PostOfficeBox.Get()) {
		var ret string
		return ret
	}
	return *o.PostOfficeBox.Get()
}

// GetPostOfficeBoxOk returns a tuple with the PostOfficeBox field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdemiaPreviewProviderAddress) GetPostOfficeBoxOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PostOfficeBox.Get(), o.PostOfficeBox.IsSet()
}

// HasPostOfficeBox returns a boolean if a field has been set.
func (o *IdemiaPreviewProviderAddress) HasPostOfficeBox() bool {
	if o != nil && o.PostOfficeBox.IsSet() {
		return true
	}

	return false
}

// SetPostOfficeBox gets a reference to the given NullableString and assigns it to the PostOfficeBox field.
func (o *IdemiaPreviewProviderAddress) SetPostOfficeBox(v string) {
	o.PostOfficeBox.Set(&v)
}
// SetPostOfficeBoxNil sets the value for PostOfficeBox to be an explicit nil
func (o *IdemiaPreviewProviderAddress) SetPostOfficeBoxNil() {
	o.PostOfficeBox.Set(nil)
}

// UnsetPostOfficeBox ensures that no value is present for PostOfficeBox, not even an explicit nil
func (o *IdemiaPreviewProviderAddress) UnsetPostOfficeBox() {
	o.PostOfficeBox.Unset()
}

func (o IdemiaPreviewProviderAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdemiaPreviewProviderAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Formatted.IsSet() {
		toSerialize["formatted"] = o.Formatted.Get()
	}
	if o.StreetAddress.IsSet() {
		toSerialize["streetAddress"] = o.StreetAddress.Get()
	}
	if o.Locality.IsSet() {
		toSerialize["locality"] = o.Locality.Get()
	}
	if o.Region.IsSet() {
		toSerialize["region"] = o.Region.Get()
	}
	if o.PostalCode.IsSet() {
		toSerialize["postalCode"] = o.PostalCode.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}
	if o.RoomNumber.IsSet() {
		toSerialize["roomNumber"] = o.RoomNumber.Get()
	}
	if o.PostOfficeBox.IsSet() {
		toSerialize["postOfficeBox"] = o.PostOfficeBox.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IdemiaPreviewProviderAddress) UnmarshalJSON(data []byte) (err error) {
	varIdemiaPreviewProviderAddress := _IdemiaPreviewProviderAddress{}

	err = json.Unmarshal(data, &varIdemiaPreviewProviderAddress)

	if err != nil {
		return err
	}

	*o = IdemiaPreviewProviderAddress(varIdemiaPreviewProviderAddress)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "formatted")
		delete(additionalProperties, "streetAddress")
		delete(additionalProperties, "locality")
		delete(additionalProperties, "region")
		delete(additionalProperties, "postalCode")
		delete(additionalProperties, "country")
		delete(additionalProperties, "roomNumber")
		delete(additionalProperties, "postOfficeBox")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIdemiaPreviewProviderAddress struct {
	value *IdemiaPreviewProviderAddress
	isSet bool
}

func (v NullableIdemiaPreviewProviderAddress) Get() *IdemiaPreviewProviderAddress {
	return v.value
}

func (v *NullableIdemiaPreviewProviderAddress) Set(val *IdemiaPreviewProviderAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableIdemiaPreviewProviderAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableIdemiaPreviewProviderAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdemiaPreviewProviderAddress(val *IdemiaPreviewProviderAddress) *NullableIdemiaPreviewProviderAddress {
	return &NullableIdemiaPreviewProviderAddress{value: val, isSet: true}
}

func (v NullableIdemiaPreviewProviderAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdemiaPreviewProviderAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


