/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
)

// checks if the Iso180135AamvaWeightRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Iso180135AamvaWeightRange{}

// Iso180135AamvaWeightRange AAMVA approximate weight range, expressed in kilograms.
type Iso180135AamvaWeightRange struct {
	// Minimum weight in the range, in kilograms.
	MinKilograms NullableInt32 `json:"minKilograms,omitempty"`
	// Maximum weight in the range, in kilograms.              If null, the maximum weight has no limit.
	MaxKilograms NullableInt32 `json:"maxKilograms,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Iso180135AamvaWeightRange Iso180135AamvaWeightRange

// NewIso180135AamvaWeightRange instantiates a new Iso180135AamvaWeightRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIso180135AamvaWeightRange() *Iso180135AamvaWeightRange {
	this := Iso180135AamvaWeightRange{}
	return &this
}

// NewIso180135AamvaWeightRangeWithDefaults instantiates a new Iso180135AamvaWeightRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIso180135AamvaWeightRangeWithDefaults() *Iso180135AamvaWeightRange {
	this := Iso180135AamvaWeightRange{}
	return &this
}

// GetMinKilograms returns the MinKilograms field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Iso180135AamvaWeightRange) GetMinKilograms() int32 {
	if o == nil || IsNil(o.MinKilograms.Get()) {
		var ret int32
		return ret
	}
	return *o.MinKilograms.Get()
}

// GetMinKilogramsOk returns a tuple with the MinKilograms field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Iso180135AamvaWeightRange) GetMinKilogramsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MinKilograms.Get(), o.MinKilograms.IsSet()
}

// HasMinKilograms returns a boolean if a field has been set.
func (o *Iso180135AamvaWeightRange) HasMinKilograms() bool {
	if o != nil && o.MinKilograms.IsSet() {
		return true
	}

	return false
}

// SetMinKilograms gets a reference to the given NullableInt32 and assigns it to the MinKilograms field.
func (o *Iso180135AamvaWeightRange) SetMinKilograms(v int32) {
	o.MinKilograms.Set(&v)
}
// SetMinKilogramsNil sets the value for MinKilograms to be an explicit nil
func (o *Iso180135AamvaWeightRange) SetMinKilogramsNil() {
	o.MinKilograms.Set(nil)
}

// UnsetMinKilograms ensures that no value is present for MinKilograms, not even an explicit nil
func (o *Iso180135AamvaWeightRange) UnsetMinKilograms() {
	o.MinKilograms.Unset()
}

// GetMaxKilograms returns the MaxKilograms field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Iso180135AamvaWeightRange) GetMaxKilograms() int32 {
	if o == nil || IsNil(o.MaxKilograms.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxKilograms.Get()
}

// GetMaxKilogramsOk returns a tuple with the MaxKilograms field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Iso180135AamvaWeightRange) GetMaxKilogramsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxKilograms.Get(), o.MaxKilograms.IsSet()
}

// HasMaxKilograms returns a boolean if a field has been set.
func (o *Iso180135AamvaWeightRange) HasMaxKilograms() bool {
	if o != nil && o.MaxKilograms.IsSet() {
		return true
	}

	return false
}

// SetMaxKilograms gets a reference to the given NullableInt32 and assigns it to the MaxKilograms field.
func (o *Iso180135AamvaWeightRange) SetMaxKilograms(v int32) {
	o.MaxKilograms.Set(&v)
}
// SetMaxKilogramsNil sets the value for MaxKilograms to be an explicit nil
func (o *Iso180135AamvaWeightRange) SetMaxKilogramsNil() {
	o.MaxKilograms.Set(nil)
}

// UnsetMaxKilograms ensures that no value is present for MaxKilograms, not even an explicit nil
func (o *Iso180135AamvaWeightRange) UnsetMaxKilograms() {
	o.MaxKilograms.Unset()
}

func (o Iso180135AamvaWeightRange) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Iso180135AamvaWeightRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.MinKilograms.IsSet() {
		toSerialize["minKilograms"] = o.MinKilograms.Get()
	}
	if o.MaxKilograms.IsSet() {
		toSerialize["maxKilograms"] = o.MaxKilograms.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Iso180135AamvaWeightRange) UnmarshalJSON(data []byte) (err error) {
	varIso180135AamvaWeightRange := _Iso180135AamvaWeightRange{}

	err = json.Unmarshal(data, &varIso180135AamvaWeightRange)

	if err != nil {
		return err
	}

	*o = Iso180135AamvaWeightRange(varIso180135AamvaWeightRange)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "minKilograms")
		delete(additionalProperties, "maxKilograms")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIso180135AamvaWeightRange struct {
	value *Iso180135AamvaWeightRange
	isSet bool
}

func (v NullableIso180135AamvaWeightRange) Get() *Iso180135AamvaWeightRange {
	return v.value
}

func (v *NullableIso180135AamvaWeightRange) Set(val *Iso180135AamvaWeightRange) {
	v.value = val
	v.isSet = true
}

func (v NullableIso180135AamvaWeightRange) IsSet() bool {
	return v.isSet
}

func (v *NullableIso180135AamvaWeightRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIso180135AamvaWeightRange(val *Iso180135AamvaWeightRange) *NullableIso180135AamvaWeightRange {
	return &NullableIso180135AamvaWeightRange{value: val, isSet: true}
}

func (v NullableIso180135AamvaWeightRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIso180135AamvaWeightRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


