/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
	"fmt"
)

// checks if the Iso180132BiometricTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Iso180132BiometricTemplate{}

// Iso180132BiometricTemplate A single biometric template per ISO 18013-2 Table C.12.
type Iso180132BiometricTemplate struct {
	// Header describing the biometric template.
	Header Iso180132BiometricTemplateHeader `json:"header"`
	// The raw data block, in a biometric type- and format-specific encoding.              For `face` and `signature_usual_mark`, this is a raw JPEG or JPEG2000 image.              See ISO 18013-2 and 18013-5.
	DataBlock string `json:"dataBlock"`
	// Whether the data block is encrypted.
	DataIsEncrypted bool `json:"dataIsEncrypted"`
	// Optional Biometric Information Record payload, containing arbitrary domestic data.
	BiometricInformationRecordPayload NullableString `json:"biometricInformationRecordPayload,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Iso180132BiometricTemplate Iso180132BiometricTemplate

// NewIso180132BiometricTemplate instantiates a new Iso180132BiometricTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIso180132BiometricTemplate(header Iso180132BiometricTemplateHeader, dataBlock string, dataIsEncrypted bool) *Iso180132BiometricTemplate {
	this := Iso180132BiometricTemplate{}
	this.Header = header
	this.DataBlock = dataBlock
	this.DataIsEncrypted = dataIsEncrypted
	return &this
}

// NewIso180132BiometricTemplateWithDefaults instantiates a new Iso180132BiometricTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIso180132BiometricTemplateWithDefaults() *Iso180132BiometricTemplate {
	this := Iso180132BiometricTemplate{}
	return &this
}

// GetHeader returns the Header field value
func (o *Iso180132BiometricTemplate) GetHeader() Iso180132BiometricTemplateHeader {
	if o == nil {
		var ret Iso180132BiometricTemplateHeader
		return ret
	}

	return o.Header
}

// GetHeaderOk returns a tuple with the Header field value
// and a boolean to check if the value has been set.
func (o *Iso180132BiometricTemplate) GetHeaderOk() (*Iso180132BiometricTemplateHeader, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Header, true
}

// SetHeader sets field value
func (o *Iso180132BiometricTemplate) SetHeader(v Iso180132BiometricTemplateHeader) {
	o.Header = v
}

// GetDataBlock returns the DataBlock field value
func (o *Iso180132BiometricTemplate) GetDataBlock() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DataBlock
}

// GetDataBlockOk returns a tuple with the DataBlock field value
// and a boolean to check if the value has been set.
func (o *Iso180132BiometricTemplate) GetDataBlockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataBlock, true
}

// SetDataBlock sets field value
func (o *Iso180132BiometricTemplate) SetDataBlock(v string) {
	o.DataBlock = v
}

// GetDataIsEncrypted returns the DataIsEncrypted field value
func (o *Iso180132BiometricTemplate) GetDataIsEncrypted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DataIsEncrypted
}

// GetDataIsEncryptedOk returns a tuple with the DataIsEncrypted field value
// and a boolean to check if the value has been set.
func (o *Iso180132BiometricTemplate) GetDataIsEncryptedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataIsEncrypted, true
}

// SetDataIsEncrypted sets field value
func (o *Iso180132BiometricTemplate) SetDataIsEncrypted(v bool) {
	o.DataIsEncrypted = v
}

// GetBiometricInformationRecordPayload returns the BiometricInformationRecordPayload field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Iso180132BiometricTemplate) GetBiometricInformationRecordPayload() string {
	if o == nil || IsNil(o.BiometricInformationRecordPayload.Get()) {
		var ret string
		return ret
	}
	return *o.BiometricInformationRecordPayload.Get()
}

// GetBiometricInformationRecordPayloadOk returns a tuple with the BiometricInformationRecordPayload field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Iso180132BiometricTemplate) GetBiometricInformationRecordPayloadOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BiometricInformationRecordPayload.Get(), o.BiometricInformationRecordPayload.IsSet()
}

// HasBiometricInformationRecordPayload returns a boolean if a field has been set.
func (o *Iso180132BiometricTemplate) HasBiometricInformationRecordPayload() bool {
	if o != nil && o.BiometricInformationRecordPayload.IsSet() {
		return true
	}

	return false
}

// SetBiometricInformationRecordPayload gets a reference to the given NullableString and assigns it to the BiometricInformationRecordPayload field.
func (o *Iso180132BiometricTemplate) SetBiometricInformationRecordPayload(v string) {
	o.BiometricInformationRecordPayload.Set(&v)
}
// SetBiometricInformationRecordPayloadNil sets the value for BiometricInformationRecordPayload to be an explicit nil
func (o *Iso180132BiometricTemplate) SetBiometricInformationRecordPayloadNil() {
	o.BiometricInformationRecordPayload.Set(nil)
}

// UnsetBiometricInformationRecordPayload ensures that no value is present for BiometricInformationRecordPayload, not even an explicit nil
func (o *Iso180132BiometricTemplate) UnsetBiometricInformationRecordPayload() {
	o.BiometricInformationRecordPayload.Unset()
}

func (o Iso180132BiometricTemplate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Iso180132BiometricTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["header"] = o.Header
	toSerialize["dataBlock"] = o.DataBlock
	toSerialize["dataIsEncrypted"] = o.DataIsEncrypted
	if o.BiometricInformationRecordPayload.IsSet() {
		toSerialize["biometricInformationRecordPayload"] = o.BiometricInformationRecordPayload.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Iso180132BiometricTemplate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"header",
		"dataBlock",
		"dataIsEncrypted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIso180132BiometricTemplate := _Iso180132BiometricTemplate{}

	err = json.Unmarshal(data, &varIso180132BiometricTemplate)

	if err != nil {
		return err
	}

	*o = Iso180132BiometricTemplate(varIso180132BiometricTemplate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "header")
		delete(additionalProperties, "dataBlock")
		delete(additionalProperties, "dataIsEncrypted")
		delete(additionalProperties, "biometricInformationRecordPayload")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIso180132BiometricTemplate struct {
	value *Iso180132BiometricTemplate
	isSet bool
}

func (v NullableIso180132BiometricTemplate) Get() *Iso180132BiometricTemplate {
	return v.value
}

func (v *NullableIso180132BiometricTemplate) Set(val *Iso180132BiometricTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableIso180132BiometricTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableIso180132BiometricTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIso180132BiometricTemplate(val *Iso180132BiometricTemplate) *NullableIso180132BiometricTemplate {
	return &NullableIso180132BiometricTemplate{value: val, isSet: true}
}

func (v NullableIso180132BiometricTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIso180132BiometricTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


