/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PhilippinesDigitalNidProviderOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PhilippinesDigitalNidProviderOutput{}

// PhilippinesDigitalNidProviderOutput struct for PhilippinesDigitalNidProviderOutput
type PhilippinesDigitalNidProviderOutput struct {
	// The PhilSys card number.
	PhilsysCardNumber string `json:"philsysCardNumber"`
}

type _PhilippinesDigitalNidProviderOutput PhilippinesDigitalNidProviderOutput

// NewPhilippinesDigitalNidProviderOutput instantiates a new PhilippinesDigitalNidProviderOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPhilippinesDigitalNidProviderOutput(philsysCardNumber string) *PhilippinesDigitalNidProviderOutput {
	this := PhilippinesDigitalNidProviderOutput{}
	this.PhilsysCardNumber = philsysCardNumber
	return &this
}

// NewPhilippinesDigitalNidProviderOutputWithDefaults instantiates a new PhilippinesDigitalNidProviderOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPhilippinesDigitalNidProviderOutputWithDefaults() *PhilippinesDigitalNidProviderOutput {
	this := PhilippinesDigitalNidProviderOutput{}
	return &this
}

// GetPhilsysCardNumber returns the PhilsysCardNumber field value
func (o *PhilippinesDigitalNidProviderOutput) GetPhilsysCardNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhilsysCardNumber
}

// GetPhilsysCardNumberOk returns a tuple with the PhilsysCardNumber field value
// and a boolean to check if the value has been set.
func (o *PhilippinesDigitalNidProviderOutput) GetPhilsysCardNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhilsysCardNumber, true
}

// SetPhilsysCardNumber sets field value
func (o *PhilippinesDigitalNidProviderOutput) SetPhilsysCardNumber(v string) {
	o.PhilsysCardNumber = v
}

func (o PhilippinesDigitalNidProviderOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PhilippinesDigitalNidProviderOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["philsysCardNumber"] = o.PhilsysCardNumber
	return toSerialize, nil
}

func (o *PhilippinesDigitalNidProviderOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"philsysCardNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPhilippinesDigitalNidProviderOutput := _PhilippinesDigitalNidProviderOutput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPhilippinesDigitalNidProviderOutput)

	if err != nil {
		return err
	}

	*o = PhilippinesDigitalNidProviderOutput(varPhilippinesDigitalNidProviderOutput)

	return err
}

type NullablePhilippinesDigitalNidProviderOutput struct {
	value *PhilippinesDigitalNidProviderOutput
	isSet bool
}

func (v NullablePhilippinesDigitalNidProviderOutput) Get() *PhilippinesDigitalNidProviderOutput {
	return v.value
}

func (v *NullablePhilippinesDigitalNidProviderOutput) Set(val *PhilippinesDigitalNidProviderOutput) {
	v.value = val
	v.isSet = true
}

func (v NullablePhilippinesDigitalNidProviderOutput) IsSet() bool {
	return v.isSet
}

func (v *NullablePhilippinesDigitalNidProviderOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePhilippinesDigitalNidProviderOutput(val *PhilippinesDigitalNidProviderOutput) *NullablePhilippinesDigitalNidProviderOutput {
	return &NullablePhilippinesDigitalNidProviderOutput{value: val, isSet: true}
}

func (v NullablePhilippinesDigitalNidProviderOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePhilippinesDigitalNidProviderOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


