/*
Trinsic API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package trinsic_api

import (
	"encoding/json"
	"fmt"
)

// checks if the KenyaNidMatch2DateOfBirthField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KenyaNidMatch2DateOfBirthField{}

// KenyaNidMatch2DateOfBirthField struct for KenyaNidMatch2DateOfBirthField
type KenyaNidMatch2DateOfBirthField struct {
	// The date of birth submitted for this check.
	InputValue string `json:"inputValue"`
	// The outcome of comparing the submitted date of birth against the Integrated Population Registration System (IPRS).              Possible values: - Exact Match - Partial Match - Transposed - No Match - Not Returned
	Outcome string `json:"outcome"`
	AdditionalProperties map[string]interface{}
}

type _KenyaNidMatch2DateOfBirthField KenyaNidMatch2DateOfBirthField

// NewKenyaNidMatch2DateOfBirthField instantiates a new KenyaNidMatch2DateOfBirthField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKenyaNidMatch2DateOfBirthField(inputValue string, outcome string) *KenyaNidMatch2DateOfBirthField {
	this := KenyaNidMatch2DateOfBirthField{}
	this.InputValue = inputValue
	this.Outcome = outcome
	return &this
}

// NewKenyaNidMatch2DateOfBirthFieldWithDefaults instantiates a new KenyaNidMatch2DateOfBirthField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKenyaNidMatch2DateOfBirthFieldWithDefaults() *KenyaNidMatch2DateOfBirthField {
	this := KenyaNidMatch2DateOfBirthField{}
	return &this
}

// GetInputValue returns the InputValue field value
func (o *KenyaNidMatch2DateOfBirthField) GetInputValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InputValue
}

// GetInputValueOk returns a tuple with the InputValue field value
// and a boolean to check if the value has been set.
func (o *KenyaNidMatch2DateOfBirthField) GetInputValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InputValue, true
}

// SetInputValue sets field value
func (o *KenyaNidMatch2DateOfBirthField) SetInputValue(v string) {
	o.InputValue = v
}

// GetOutcome returns the Outcome field value
func (o *KenyaNidMatch2DateOfBirthField) GetOutcome() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value
// and a boolean to check if the value has been set.
func (o *KenyaNidMatch2DateOfBirthField) GetOutcomeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outcome, true
}

// SetOutcome sets field value
func (o *KenyaNidMatch2DateOfBirthField) SetOutcome(v string) {
	o.Outcome = v
}

func (o KenyaNidMatch2DateOfBirthField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KenyaNidMatch2DateOfBirthField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["inputValue"] = o.InputValue
	toSerialize["outcome"] = o.Outcome

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KenyaNidMatch2DateOfBirthField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"inputValue",
		"outcome",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKenyaNidMatch2DateOfBirthField := _KenyaNidMatch2DateOfBirthField{}

	err = json.Unmarshal(data, &varKenyaNidMatch2DateOfBirthField)

	if err != nil {
		return err
	}

	*o = KenyaNidMatch2DateOfBirthField(varKenyaNidMatch2DateOfBirthField)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "inputValue")
		delete(additionalProperties, "outcome")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKenyaNidMatch2DateOfBirthField struct {
	value *KenyaNidMatch2DateOfBirthField
	isSet bool
}

func (v NullableKenyaNidMatch2DateOfBirthField) Get() *KenyaNidMatch2DateOfBirthField {
	return v.value
}

func (v *NullableKenyaNidMatch2DateOfBirthField) Set(val *KenyaNidMatch2DateOfBirthField) {
	v.value = val
	v.isSet = true
}

func (v NullableKenyaNidMatch2DateOfBirthField) IsSet() bool {
	return v.isSet
}

func (v *NullableKenyaNidMatch2DateOfBirthField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKenyaNidMatch2DateOfBirthField(val *KenyaNidMatch2DateOfBirthField) *NullableKenyaNidMatch2DateOfBirthField {
	return &NullableKenyaNidMatch2DateOfBirthField{value: val, isSet: true}
}

func (v NullableKenyaNidMatch2DateOfBirthField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKenyaNidMatch2DateOfBirthField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


